Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2022-12, with the labels that each got.

#658 chore: cleanup
  .github/workflows/merge-commit-topic-branch-pr-to-feat-branch.yml
Labels: size/xs

#652 chore: update ETC
  common/changes/@aws/swb-app/update-ETC_2022-11-30-20-36.json
  common/changes/@aws/workbench-core-base/update-ETC_2022-11-30-23-40.json
  common/changes/@aws/workbench-core-environments/update-ETC_2022-11-30-20-36.json
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/environments-ui/src/models/EnvironmentTypeConfig.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/environmentTypeHandler.ts
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/handlers/statusHandler.ts
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/models/createEnvironmentTypeConfigRequest.ts
  workbench-core/environments/src/models/environmentConnectionLinkPlaceholder.ts
  workbench-core/environments/src/models/environmentConnectionService.ts
  workbench-core/environments/src/models/environmentLifecycleService.ts
  workbench-core/environments/src/models/environmentType.ts
  workbench-core/environments/src/models/environmentTypeConfig.ts
  workbench-core/environments/src/models/eventBridgeEventToDDB.ts
  workbench-core/environments/src/models/listEnvironmentTypeConfigsRequest.test.ts
  workbench-core/environments/src/models/listEnvironmentTypeConfigsRequest.ts
  workbench-core/environments/src/models/listEnvironmentTypesRequest.test.ts
  workbench-core/environments/src/models/listEnvironmentTypesRequest.ts
  workbench-core/environments/src/models/updateEnvironmentTypeConfigsRequest.ts
  workbench-core/environments/src/schemas/createEnvironmentTypeConfig.ts
  workbench-core/environments/src/schemas/updateEnvironmentTypeConfig.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentTypeConfigService.test.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
  workbench-core/environments/src/services/environmentTypeService.ts
Labels: size/l

#659 feat(workbench-core/datasets): BREAKING CHANGE - add fileName param to DatasetService.createPresignedUploadUrl() and add datasets presigned singe file upload integ tests
  common/changes/@aws/workbench-core-base/topic-presigned-file-upload-integ-tests_2022-12-01-23-00.json
  common/changes/@aws/workbench-core-datasets/topic-presigned-file-upload-integ-tests_2022-12-01-23-00.json
  workbench-core/base/src/aws/helpers/s3Service.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsStoragePlugin.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.test.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
  workbench-core/datasets/src/schemas/createPresignedSinglePartFileUploadUrl.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/complex/datasetHelper.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/fileUpload.test.ts
Labels: size/m

#663 feat: user management api
  .viperlightignore
  common/changes/@aws/swb-app/sevu-features-user-api_2022-12-02-19-28.json
  common/changes/@aws/workbench-core-authentication/sevu-features-user-api_2022-12-02-19-28.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/base/collectionResource.ts
  solutions/swb-reference/integration-tests/support/resources/base/resource.ts
  solutions/swb-reference/integration-tests/support/resources/users/user.ts
  solutions/swb-reference/integration-tests/support/resources/users/users.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/activateDeactivateUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userApi.test.ts
  solutions/swb-reference/jest.config.js
  solutions/swb-reference/src/SWBStack.ts
  workbench-core/authentication/package.json
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/models/updateUserRequest.ts
Labels: size/xl

#661 test: add datasets iam role creation integ tests
  common/changes/@aws/workbench-core-datasets/topic-datasets-iam-role-creation-integ-tests_2022-12-05-20-35.json
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/schemas/addDatasetPermissionsToRoleSchema.ts
  workbench-core/datasets/src/schemas/createRegisterExternalBucketRoleSchema.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/iamRoles.test.ts
Labels: size/m

#666 feat: etc delete
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/environmentTypeHandler.ts
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/models/environmentTypeConfigs/createEnvironmentTypeConfigRequest.ts
  workbench-core/environments/src/models/environmentTypeConfigs/deleteEnvironmentTypeConfigRequest.ts
  workbench-core/environments/src/models/environmentTypeConfigs/environmentTypeConfig.ts
  workbench-core/environments/src/models/environmentTypeConfigs/listEnvironmentTypeConfigsRequest.test.ts
  workbench-core/environments/src/models/environmentTypeConfigs/listEnvironmentTypeConfigsRequest.ts
  workbench-core/environments/src/models/environmentTypeConfigs/updateEnvironmentTypeConfigsRequest.ts
  workbench-core/environments/src/models/environmentTypes/environmentType.ts
  workbench-core/environments/src/models/environmentTypes/listEnvironmentTypesRequest.test.ts
  workbench-core/environments/src/models/environmentTypes/listEnvironmentTypesRequest.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/services/environmentTypeConfigService.test.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
  workbench-core/environments/src/services/environmentTypeService.ts
Labels: size/m

#667 feat: Bootstrap IT Admin User
  common/changes/@aws/workbench-core-environments/sevu-features-post-deployment-script_2022-12-06-15-50.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/package.json
  solutions/swb-reference/src/postDeployment.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/postDeployment/authorizationSetup.test.ts
  workbench-core/environments/src/postDeployment/authorizationSetup.ts
Labels: size/m

#631 feat: GALI-1787 Account Integration Tests
  solutions/swb-app/src/accountRoutes.ts
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/resources/accounts/account.ts
  solutions/swb-reference/integration-tests/support/resources/accounts/accounts.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/aws-accounts/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/aws-account.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/accountHandlerLambda.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/constants.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/handlers/accountHandler.ts
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/schemas/updateAccount.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/src/services/hostingAccountService.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/base/README.md
  workbench-core/base/src/cognitoTokenService.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/services/secretsService.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/settings.ts
Labels: size/l

#671 feat: GALI-2036 update account
  solutions/swb-app/src/accountRoutes.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
Labels: size/s

#669 feat: Host UI on ECS with ALB
  solutions/example-ui-app/src/context/NotificationContext.tsx
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
  solutions/swb-ui/infrastructure/src/SWBUIStack.ts
  solutions/swb-ui/infrastructure/src/constants.ts
  solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
  solutions/swb-ui/infrastructure/src/index.ts
  solutions/swb-ui/ui/Dockerfile
  solutions/swb-ui/ui/README.md
  solutions/swb-ui/ui/package.json
  solutions/swb-ui/ui/scripts/image-deploy.sh
Labels: size/l

#676 docs(readme.md): adding jq to prerequisites
  workbench-core/example/infrastructure/README.md
Labels: size/xs

#673 fix: move AuditLogger into the Audit package
  common/changes/@aws/workbench-core-audit/fix-moveAuditLogger_2022-12-08-00-32.json
  common/changes/@aws/workbench-core-base/fix-moveAuditLogger_2022-12-08-00-32.json
  common/changes/@aws/workbench-core-environments/fix-moveAuditLogger_2022-12-08-00-32.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/audit/README.md
  workbench-core/audit/package.json
  workbench-core/audit/src/auditLogger.test.ts
  workbench-core/audit/src/auditLogger.ts
  workbench-core/audit/src/index.ts
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/index.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
  workbench-core/example/app/src/services/datasetService.ts
Labels: size/s

#678 fix(swb): fix accountId needed for using an existing VPC and update AccessLog Cfn Export name
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-ui/infrastructure/src/constants.ts
  solutions/swb-ui/ui/scripts/image-deploy.sh
Labels: size/s

#679 feat(projects): update project API
  common/changes/@aws/swb-app/maghirardelli-gali-1923-update-proj-api_2022-12-09-17-36.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-gali-1923-update-proj-api_2022-12-09-17-36.json
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/projects/listProjectsRequest.ts
  workbench-core/accounts/src/models/projects/updateProjectRequest.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/services/projectService.ts
Labels: size/m

#683 feat(swb-ui): enable ECS Fargate Service autoscaling and remove EC2 instance
  solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
Labels: size/s

#681 feat: dynamic authorization service interfaces added
  workbench-core/authorization/README.md
  workbench-core/authorization/config/jest.config.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/addUserToGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/doesGroupExist.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/dynamicOperation.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupUsers.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsBySubject.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getUserGroups.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/identityPermission.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/init.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isAuthorizedOnRoute.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isAuthorizedOnSubject.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteIgnored.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteProtected.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isUserAssignedToGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/removeUserFromGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/base/README.md
Labels: size/l

#691 chore: update github's hostingAccountHandlerRoleArn value for integration tests
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
Labels: size/s

#688 feat: dynamic authorization permissions plugin interfaces
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getDynamicOperationsByRoute.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsByIdentity.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationPermissionsPlugin.ts
Labels: size/m

#693 chore: integration test hosting acount handler role arn update part 2
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
Labels: size/s

#695 chore: make Account tests use environment variables
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
Labels: size/xs

#696 chore: integration test hosting acount handler role arn update part 4
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
Labels: size/xs

#692 chore(environment type): remove json schema and update et with zod
  solutions/swb-app/src/environmentTypeRoutes.ts
  solutions/swb-reference/integration-tests/support/complex/environmentTypeHelper.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
  solutions/swb-reference/src/accountHandlerLambda.ts
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/cloudFormationTemplate.ts
  workbench-core/base/src/index.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/environmentTypeHandler.ts
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/models/environmentTypes/environmentType.ts
  workbench-core/environments/src/models/environmentTypes/updateEnvironmentTypeRequest.ts
  workbench-core/environments/src/schemas/createEnvironmentType.ts
  workbench-core/environments/src/schemas/updateEnvironmentType.ts
  workbench-core/environments/src/services/environmentTypeConfigService.test.ts
  workbench-core/environments/src/services/environmentTypeService.test.ts
  workbench-core/environments/src/services/environmentTypeService.ts
Labels: size/m

#694 feat: add dataSetsAuthorizationPlugin interface and associated objects
  common/changes/@aws/workbench-core-datasets/topic-datasets-authz-interfaces_2022-12-14-02-59.json
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsAuthorizationPlugin.ts
  workbench-core/datasets/src/models/addRemoveAccessPermissionRequest.ts
  workbench-core/datasets/src/models/createProvisionDatasetRequest.ts
  workbench-core/datasets/src/models/dataSetPermission.ts
  workbench-core/datasets/src/models/dataSetsAccessLevel.ts
  workbench-core/datasets/src/models/getAccessPermissionRequest.ts
  workbench-core/datasets/src/models/getDataSetMountPointRequest.ts
  workbench-core/datasets/src/models/permissionsResponse.ts
Labels: size/m

#689 chore: maf cdk constructs
  common/changes/@aws/workbench-core-infrastructure/dynamoDB-construct_2022-12-13-20-11.json
  workbench-core/example/infrastructure/README.md
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/infrastructure/config/jest.config.json
  workbench-core/infrastructure/docs/WorkbenchDynamodb.md
  workbench-core/infrastructure/docs/WorkbenchEncryptionKeyWithRotation.md
  workbench-core/infrastructure/docs/WorkbenchSecureS3Bucket.md
  workbench-core/infrastructure/docs/workbenchCognito.md
  workbench-core/infrastructure/src/index.ts
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
  workbench-core/infrastructure/src/workbenchDynamodb.test.ts
  workbench-core/infrastructure/src/workbenchDynamodb.ts
  workbench-core/infrastructure/src/workbenchEncryptionKeyWithRotation.test.ts
  workbench-core/infrastructure/src/workbenchEncryptionKeyWithRotation.ts
  workbench-core/infrastructure/src/workbenchSecureS3Bucket.test.ts
  workbench-core/infrastructure/src/workbenchSecureS3Bucket.ts
Labels: size/l

#697 feat: enable auditing SWB requests
  common/changes/@aws/swb-app/thingut-gali-1509-auditing_2022-12-16-04-08.json
  common/changes/@aws/workbench-core-audit/thingut-gali-1509-auditing_2022-12-16-04-08.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/package.json
  solutions/swb-app/src/audit/swbAuditExtractor.test.ts
  solutions/swb-app/src/audit/swbAuditExtractor.ts
  solutions/swb-app/src/audit/swbAuditLogger.test.ts
  solutions/swb-app/src/audit/swbAuditLogger.ts
  solutions/swb-app/src/audit/swbAuditPlugin.test.ts
  solutions/swb-app/src/audit/swbAuditPlugin.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
  workbench-core/audit/README.md
  workbench-core/audit/src/auditMiddleware.test.ts
  workbench-core/audit/src/auditMiddleware.ts
  workbench-core/audit/src/baseExtractor.test.ts
  workbench-core/audit/src/baseExtractor.ts
Labels: size/m

#706 chore: update demo.yaml with fieldsToMaskWhenAuditing
  solutions/swb-reference/src/config/demo.yaml
Labels: size/xs

#690 feat: [GALI-2005] swb-app DataSet domain objects
  common/changes/@aws/swb-app/atmikev-GALI-2005_swb-app-dataset-interfaces_2022-12-13-22-01.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/package.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/createProvisionDatasetRequest.ts
  solutions/swb-app/src/dataSets/dataSet.ts
  solutions/swb-app/src/dataSets/dataSetExternalEndpointRequest.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/dataSetStoragePlugin.ts
  solutions/swb-app/src/dataSets/endpointConnectionStrings.ts
  solutions/swb-app/src/dataSets/externalEndpoint.ts
  solutions/swb-app/src/dataSets/storageLocation.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/index.ts
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/l

#703 feat: implement getGroupStatus and setGroupStatus
  common/changes/@aws/workbench-core-authorization/topic-implement-get-set-group-status_2022-12-16-20-22.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/authorization/README.md
  workbench-core/authorization/config/jest.config.json
  workbench-core/authorization/package.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/setGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/groupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/models/GroupMetadata.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/authorization/src/errors/errors.test.ts
  workbench-core/authorization/src/errors/tooManyRequestsError.ts
  workbench-core/authorization/src/index.ts
Labels: size/m

#707 chore: dynamic auth infrastructure
  common/changes/@aws/workbench-core-infrastructure/dynamicAuth-infrastructure_2022-12-19-20-23.json
  workbench-core/example/app/src/services/awsService.ts
  workbench-core/example/app/src/services/datasetService.ts
  workbench-core/example/infrastructure/README.md
  workbench-core/example/infrastructure/integration-tests/support/complex/datasetHelper.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/jest.config.js
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/infrastructure/README.md
  workbench-core/infrastructure/src/workbenchDynamodb.test.ts
  workbench-core/infrastructure/src/workbenchDynamodb.ts
Labels: size/m

#708 feat: proxy lambda updates
  solutions/swb-reference/src/proxyHandlerLambda.ts
Labels: size/s

#709 feat: [GALI-2124] data set with environment
  common/changes/@aws/workbench-core-base/atmikev-GALI-2124_DataSetWithEnvironment_2022-12-20-18-23.json
  common/changes/@aws/workbench-core-environments/atmikev-GALI-2124_DataSetWithEnvironment_2022-12-20-18-23.json
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.test.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/handlers/statusHandler.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/m

#699 feat: add addPutItems and change addPutRequests to include other options for ddbService
  common/changes/@aws/workbench-core-base/feat-ddbServiceAddPutRequests_2022-12-15-11-09.json
  common/changes/@aws/workbench-core-environments/feat-ddbServiceAddPutRequests_2022-12-15-11-09.json
  solutions/swb-reference/src/config/demo.yaml
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/transactEdit.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/transactEdit.ts
  workbench-core/base/src/services/metadataService.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
Labels: size/m

#711 feat: dynamic authorization interfaces and implementation
  common/changes/@aws/workbench-core-authorization/topic-group-management-interfaces_2022-12-12-22-57.json
  common/changes/@aws/workbench-core-authorization/topic-implement-get-set-group-status_2022-12-16-20-22.json
  common/changes/@aws/workbench-core-base/topic-group-management-interfaces_2022-12-12-22-57.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/authorization/README.md
  workbench-core/authorization/config/jest.config.json
  workbench-core/authorization/package.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/addUserToGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/doesGroupExist.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/dynamicOperation.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getDynamicOperationsByRoute.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupUsers.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsByIdentity.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsBySubject.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getUserGroups.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/identityPermission.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/init.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isAuthorizedOnRoute.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isAuthorizedOnSubject.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteIgnored.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteProtected.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isUserAssignedToGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/removeUserFromGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/setGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/models/GroupMetadata.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/authorization/src/errors/errors.test.ts
  workbench-core/authorization/src/errors/tooManyRequestsError.ts
  workbench-core/authorization/src/index.ts
  workbench-core/base/package.json
Labels: size/xl

#710 feat: [GALI-2125] add fields to data set creation
  common/changes/@aws/swb-app/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-16-55.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-16-55.json
  common/changes/@aws/workbench-core-datasets/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-00-43.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  workbench-core/base/README.md
  workbench-core/datasets/src/schemas/createDataSet.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
Labels: size/m

#714 chore: REVERT [GALI-2125] add fields to data set creation
  common/changes/@aws/swb-app/revert-710-atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-19-23.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-16-55.json
  common/changes/@aws/workbench-core-datasets/revert-710-atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-19-23.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  workbench-core/datasets/src/schemas/createDataSet.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
Labels: size/m

#712 feat: implement create group
  common/changes/@aws/workbench-core-audit/topic-implement-create-group_2022-12-21-18-14.json
  common/changes/@aws/workbench-core-authorization/topic-implement-create-group_2022-12-21-18-14.json
  common/changes/@aws/workbench-core-datasets-ui/topic-implement-create-group_2022-12-21-18-14.json
  common/changes/@aws/workbench-core-environments-ui/topic-implement-create-group_2022-12-21-18-14.json
  common/changes/@aws/workbench-core-swb-common-ui/topic-implement-create-group_2022-12-21-18-14.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/audit/tsconfig.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/setGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/authorization/src/index.ts
  workbench-core/authorization/src/models/createGroup.ts
  workbench-core/datasets-ui/.eslintrc.js
  workbench-core/environments-ui/.eslintrc.js
  workbench-core/example/app/src/configs/constants.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/generateRouter.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/app/src/services/dynamicAuthorizationService.ts
  workbench-core/example/infrastructure/integration-tests/support/complex/dynamicAuthorizationHelper.ts
  workbench-core/example/infrastructure/integration-tests/support/resources.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/group.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/groups.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
  workbench-core/swb-common-ui/.eslintrc.js
Labels: size/l

#715 feat: [GALI-2125] add fields to data set creation
  common/changes/@aws/swb-app/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-16-55.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-2125_AddFieldsToDataSetCreation_2022-12-21-16-55.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/createDataSetRequestParser.ts
  solutions/swb-app/src/dataSets/createExternalEndpointRequestParser.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
Labels: size/m

#718 feat: Project-environment type configs relationship
  common/changes/@aws/swb-app/farandac-GALI-2025-Proj-etc-relationship_2022-12-22-16-31.json
  common/changes/@aws/workbench-core-base/farandac-GALI-2025-Proj-etc-relationship_2022-12-22-16-31.json
  common/changes/@aws/workbench-core-environments/farandac-GALI-2025-Proj-etc-relationship_2022-12-22-16-31.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigs/environmentTypeConfig.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listProjectEnvTypeConfigsRequest.test.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listProjectEnvTypeConfigsRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/projectEnvTypeConfigPlugin.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/environmentTypeConfigs/environmentTypeConfig.ts
  solutions/swb-reference/integration-tests/support/resources/environmentTypes/environmentTypes.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/support/resources/projects/projects.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/projectEnvTypeConfig.test.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.ts
  workbench-core/base/README.md
  workbench-core/base/config/jest.config.json
  workbench-core/base/src/aws/helpers/dynamoDB/ddbUtil.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/base/src/services/metadataService.ts
  workbench-core/base/src/types/relationshipDDBItem.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/services/environmentTypeConfigService.test.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
Labels: size/xl

#719 feat: [GALI-2097] DataSetAuthService
  common/changes/@aws/swb-app/atmikev-GALI-2097_DataSetAuthService_2022-12-22-15-42.json
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/dataSets/addRemoveAccessPermissionRequest.ts
  solutions/swb-app/src/dataSets/dataSetPermissionParser.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/getAccessPermissionRequestParser.ts
  solutions/swb-app/src/dataSets/permissionsResponseParser.ts
  solutions/swb-app/src/index.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/m

#717 chore: swb dynamic authorization infrastructure
  common/changes/@aws/swb-app/swb-dynamicAuth-infrastructure_2022-12-22-00-39.json
  common/changes/@aws/workbench-core-infrastructure/swb-dynamicAuth-infrastructure_2022-12-22-00-39.json
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/constants.ts
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/infrastructure/README.md
  workbench-core/infrastructure/src/workbenchDynamodb.test.ts
  workbench-core/infrastructure/src/workbenchDynamodb.ts
Labels: size/m

#723 chore(projects): clean up project service
  common/changes/@aws/swb-app/maghirardelli-project-api-clean-up_2022-12-22-23-11.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-project-api-clean-up_2022-12-22-23-11.json
  common/changes/@aws/workbench-core-base/maghirardelli-project-api-clean-up_2022-12-22-23-11.json
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/schemas/projects/createProjectSchema.ts
  solutions/swb-app/src/schemas/projects/getProjectSchema.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/projects/createProjectRequest.ts
  workbench-core/accounts/src/models/projects/deleteProjectRequest.ts
  workbench-core/accounts/src/models/projects/getProjectRequest.ts
  workbench-core/accounts/src/models/projects/listProjectsRequest.test.ts
  workbench-core/accounts/src/models/projects/listProjectsResponse.ts
  workbench-core/accounts/src/models/projects/updateProjectRequest.test.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/services/projectService.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/interfaces/getItemParams.ts
Labels: size/l

#423 feat: enable ddb pitr
  solutions/swb-reference/src/SWBStack.ts
Labels: size/xs

#726 feat(dynamicauthorizationservice.ts): implementing addUserToGroup
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/topic-implement-add-user-to-group_2022-12-27-16-27.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/addUserToGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/authorization/src/models/assignUserToGroup.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/group.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/groups.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
Labels: size/m

#728 fix: add user to group integration test
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
Labels: size/s

#725 feat(authorization): createIdentityPermissions implemented with integration tests
  common/changes/@aws/workbench-core-audit/topic-createIdentityPermissions_2022-12-23-05-34.json
  common/changes/@aws/workbench-core-authorization/topic-createIdentityPermissions_2022-12-23-05-34.json
  common/changes/@aws/workbench-core-base/topic-createIdentityPermissions_2022-12-23-05-34.json
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/audit/README.md
  workbench-core/audit/package.json
  workbench-core/audit/src/baseExtractor.test.ts
  workbench-core/audit/src/baseExtractor.ts
  workbench-core/authorization/README.md
  workbench-core/authorization/config/jest.config.json
  workbench-core/authorization/package.json
  workbench-core/authorization/src/action.ts
  workbench-core/authorization/src/authenticatedUser.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/identityPermission.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/effect.ts
  workbench-core/authorization/src/errors/errors.test.ts
  workbench-core/authorization/src/errors/identityPermissionCreationError.ts
  workbench-core/authorization/src/errors/throughputExceededError.ts
  workbench-core/authorization/src/index.ts
  workbench-core/authorization/src/models/identityPermission.ts
  workbench-core/authorization/src/permission.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/app/src/services/auditService.ts
  workbench-core/example/app/src/services/dynamicAuthorizationService.ts
  workbench-core/example/infrastructure/integration-tests/support/complex/dynamicAuthorizationHelper.ts
  workbench-core/example/infrastructure/integration-tests/support/resources.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermission.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Labels: size/xl

#731 chore: implement getGroupUsers API
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/GetGroupUsers_2022-12-29-22-28.json
  common/changes/@aws/workbench-core-base/GetGroupUsers_2022-12-30-17-37.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupUsers.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/group.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/groups.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
  workbench-core/example/infrastructure/package.json
Labels: size/m

#730 feat: Implement removeUserFromGroup api
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/topic-implement-remove-user-from-group_2022-12-29-21-36.json
  common/changes/@aws/workbench-core-user-management/topic-implement-remove-user-from-group_2022-12-30-18-41.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/removeUserFromGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/authorization/src/errors/errors.test.ts
  workbench-core/authorization/src/index.ts
  workbench-core/example/app/package.json
  workbench-core/example/app/src/configs/constants.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/models/dynamicAuthorization/addUserToGroup.ts
  workbench-core/example/app/src/models/dynamicAuthorization/createGroup.ts
  workbench-core/example/app/src/models/dynamicAuthorization/removeUserFromGroup.ts
  workbench-core/example/app/src/models/user/addUserToRole.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/app/src/routes/userRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/group.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/groups.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/userManagement/role.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/getUserRoles.test.ts
  workbench-core/user-management/src/errors/errors.test.ts
  workbench-core/user-management/src/errors/tooManyRequestsError.ts
  workbench-core/user-management/src/index.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/user-management/src/userManagementPlugin.ts
  workbench-core/user-management/src/userManagementService.ts
Labels: size/l
