Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2022-11, with the labels that each got.

#582 feat(pb): update LIST Projects API
  common/changes/@aws/swb-app/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json
  common/changes/@aws/workbench-core-base/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json
  common/changes/@aws/workbench-core-environments/maghirardelli-gali-1739-list-project-api_2022-10-28-16-33.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/schemas/projects/listProjectsSchema.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/listProjectsRequest.ts
  workbench-core/accounts/src/models/listProjectsResponse.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/services/projectService.ts
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/getter.test.ts
  workbench-core/base/src/constants/queryParams.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/paginationHelper.test.ts
  workbench-core/base/src/utilities/paginationHelper.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
  workbench-core/environments/src/services/environmentTypeService.ts
Labels: size/l

#589 chore: fix dynamic authorization
  workbench-core/example/infrastructure/README.md
  workbench-core/example/infrastructure/package.json
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/infrastructure-stack.test.ts.snap
Labels: size/m

#591 feat: add GET project API
  common/changes/@aws/swb-app/maghirardelli-gali-1956-get-project-api_2022-11-02-20-03.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-gali-1956-get-project-api_2022-11-02-20-03.json
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/schemas/projects/getProjectSchema.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/accounts/README.md
  workbench-core/accounts/package.json
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/getProjectRequest.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/services/projectService.ts
Labels: size/m

#592 fix(utilities): refactor utilities, add tests, typo fixes
  common/changes/@aws/workbench-core-accounts/maghirardelli-push-common-code-from-proj-api-to-develop_2022-11-02-21-10.json
  common/changes/@aws/workbench-core-base/maghirardelli-push-common-code-from-proj-api-to-develop_2022-11-02-21-10.json
  common/changes/@aws/workbench-core-environments/maghirardelli-push-common-code-from-proj-api-to-develop_2022-11-02-21-10.json
  common/config/rush/pnpm-lock.yaml
  workbench-core/accounts/src/constants/hostingAccountStatus.ts
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/getter.test.ts
  workbench-core/base/src/constants/queryParams.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/paginationHelper.test.ts
  workbench-core/base/src/utilities/paginationHelper.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
  workbench-core/environments/src/services/environmentTypeService.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
Labels: size/m

#597 chore: fix e2e-test build failure
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-ui/ui/README.md
  solutions/swb-ui/ui/cypress.config.ts
Labels: size/s

#600 chore: fix example package snapshot error and some cleanup
  workbench-core/example/infrastructure/package.json
Labels: size/xs

#594 feat: GALI-1557: Create user-configurable network on Main account
  solutions/swb-reference/README.md
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
  solutions/swb-reference/src/infra/SWBVpc.test.ts
  solutions/swb-reference/src/infra/SWBVpc.ts
Labels: size/m

#596 chore: Add filter and sorting utilities
  common/changes/@aws/workbench-core-base/FilterAndSortingUtilities_2022-11-02-23-10.json
  common/config/rush/pnpm-lock.yaml
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/filterRequest.ts
  workbench-core/base/src/interfaces/queryParameterFilter.ts
  workbench-core/base/src/interfaces/queryParams.ts
  workbench-core/base/src/interfaces/sortRequest.ts
  workbench-core/base/src/schemas/queryParameterFilterSchema.ts
  workbench-core/base/src/utilities/paginationHelper.ts
  workbench-core/base/src/utilities/queryParamsFiltersUtils.test.ts
  workbench-core/base/src/utilities/queryParamsFiltersUtils.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
Labels: size/m

#599 feat: [GALI-1966] DatabaseService.executeQuery() method
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-1966_ExecuteQueryMethod_2022-11-08-17-42.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-1966_ExecuteQueryMethod_2022-11-08-17-42.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  workbench-core/accounts/package.json
  workbench-core/accounts/src/models/account.ts
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/tsconfig.json
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/interfaces/paginatedItemsResponse.ts
  workbench-core/base/src/types/json.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
Labels: size/m

#607 chore: merge develop
  README.md
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-1966_ExecuteQueryMethod_2022-11-08-17-42.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-1966_ExecuteQueryMethod_2022-11-08-17-42.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  workbench-core/accounts/README.md
  workbench-core/accounts/package.json
  workbench-core/accounts/src/models/account.ts
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/tsconfig.json
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/interfaces/paginatedItemsResponse.ts
  workbench-core/base/src/types/json.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
Labels: size/m

#609 feat: delete user api
  common/changes/@aws/swb-app/sevu-features-delete-user-api_2022-11-09-16-01.json
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/base/collectionResource.ts
  solutions/swb-reference/integration-tests/support/resources/base/resource.ts
  solutions/swb-reference/integration-tests/support/resources/users/user.ts
  solutions/swb-reference/integration-tests/support/resources/users/users.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
Labels: size/m

#603 chore: maf integration test workflow update+ suppress cfn/cdk nag
  .github/actions/baseAction/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/deploy-integration-example-app.yml
  .github/workflows/deploy-integration-example.yml
  .github/workflows/deploy-integration-swb-reference.yml
  .github/workflows/merge-develop-to-stage.yml
  .gitignore
  .viperlightignore
  common/config/rush/pnpm-lock.yaml
  workbench-core/example/app/src/generateRouter.ts
  workbench-core/example/app/src/services/awsService.ts
  workbench-core/example/infrastructure/README.md
  workbench-core/example/infrastructure/config/jest.config.json
  workbench-core/example/infrastructure/integration-tests/config/example.yaml
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
  workbench-core/example/infrastructure/jest.config.js
  workbench-core/example/infrastructure/package.json
  workbench-core/example/infrastructure/scripts/cleanup.sh
  workbench-core/example/infrastructure/scripts/setupCognito.sh
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
  workbench-core/example/infrastructure/src/constructs/encryptionKeyWithRotation.ts
  workbench-core/example/infrastructure/src/constructs/secureS3Bucket.ts
  workbench-core/example/infrastructure/src/example-stack.ts
Labels: size/xl

#602 test: added create user integration tests
  .viperlightignore
  common/changes/@aws/workbench-core-authentication/test-create-user-integ-tests_2022-11-07-22-34.json
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/authentication/src/user.ts
  workbench-core/authentication/src/userManagementPlugin.ts
  workbench-core/authentication/src/userManagementService.test.ts
  workbench-core/authentication/src/userManagementService.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/userRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/base/resource.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/users/user.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/users/users.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/createUser.test.ts
  workbench-core/example/infrastructure/jest.config.js
  workbench-core/example/infrastructure/package.json
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
Labels: size/l

#614 chore: merge from dev
  .github/actions/baseAction/action.yml
  .github/workflows/build-and-test.yml
  .github/workflows/deploy-integration-example-app.yml
  .github/workflows/deploy-integration-example.yml
  .github/workflows/deploy-integration-swb-reference.yml
  .github/workflows/merge-develop-to-stage.yml
  .gitignore
  .viperlightignore
  README.md
  common/changes/@aws/workbench-core-infrastructure/pbabz-fix-buildbreak_2022-11-09-17-46.json
  common/config/rush/pnpm-lock.yaml
  workbench-core/example/app/src/generateRouter.ts
  workbench-core/example/app/src/services/awsService.ts
  workbench-core/example/infrastructure/README.md
  workbench-core/example/infrastructure/config/jest.config.json
  workbench-core/example/infrastructure/integration-tests/config/example.yaml
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
  workbench-core/example/infrastructure/jest.config.js
  workbench-core/example/infrastructure/package.json
  workbench-core/example/infrastructure/scripts/cleanup.sh
  workbench-core/example/infrastructure/scripts/setupCognito.sh
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
  workbench-core/example/infrastructure/src/constructs/encryptionKeyWithRotation.ts
  workbench-core/example/infrastructure/src/constructs/secureS3Bucket.ts
  workbench-core/example/infrastructure/src/example-stack.ts
Labels: size/xl

#615 chore: fix example app
  workbench-core/example/infrastructure/README.md
  workbench-core/example/infrastructure/package.json
  workbench-core/example/infrastructure/scripts/cleanup.sh
  workbench-core/example/infrastructure/scripts/getResources.sh
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
  workbench-core/example/infrastructure/src/__tests__/example-stack.test.ts
  workbench-core/example/infrastructure/src/constructs/secureS3Bucket.ts
  workbench-core/example/infrastructure/src/example-stack.ts
Labels: size/xl

#606 test: activate/deactiveUser integration tests
  .viperlightignore
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/userRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/users/user.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/activateDeactivateUser.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/createUser.test.ts
  workbench-core/example/infrastructure/src/example-stack.ts
Labels: size/m

#613 feat: [GALI-1785] list hosting accounts
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/package.json
  solutions/swb-app/src/accountRoutes.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/validatorHelper.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/accounts/README.md
  workbench-core/accounts/package.json
  workbench-core/accounts/src/handlers/accountHandler.ts
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/account.ts
  workbench-core/accounts/src/models/accounts/account.ts
  workbench-core/accounts/src/models/accounts/listAccountsRequest.test.ts
  workbench-core/accounts/src/models/accounts/listAccountsRequest.ts
  workbench-core/accounts/src/models/costCenter.ts
  workbench-core/accounts/src/models/costCenter/costCenter.ts
  workbench-core/accounts/src/models/costCenter/createCostCenterRequest.ts
  workbench-core/accounts/src/schemas/createAccount.ts
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/src/services/hostingAccountService.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/query.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/paginatedJsonResponse.ts
  workbench-core/base/src/interfaces/paginatedResponse.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/example-stack.test.ts.snap
Labels: size/l

#619 test: added listUsers integration tests
  .viperlightignore
  workbench-core/example/infrastructure/integration-tests/support/resources/base/collectionResource.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/base/resource.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/createUser.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/listUsers.test.ts
Labels: size/s

#616 feat: Metadata service
  common/changes/@aws/swb-app/metadataService_2022-11-11-05-56.json
  common/changes/@aws/workbench-core-base/metadataService_2022-11-11-05-56.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/transactEdit.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/transactEdit.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/base/src/services/metadataService.ts
Labels: size/m

#624 chore: add mock dynamic authz service
  common/changes/@aws/workbench-core-authorization/sevu-tasks-mock-dynamic-auth_2022-11-15-18-25.json
  workbench-core/authorization/src/errors/errors.test.ts
  workbench-core/authorization/src/errors/groupAlreadyExistsError.ts
  workbench-core/authorization/src/errors/groupNotFoundError.ts
  workbench-core/authorization/src/index.ts
  workbench-core/authorization/src/mockDynamicAuthorizationService.test.ts
  workbench-core/authorization/src/mockDynamicAuthorizationService.ts
  workbench-core/authorization/src/models/assignUserToGroup.ts
  workbench-core/authorization/src/models/createGroup.ts
  workbench-core/authorization/src/models/createIdentityPermissions.ts
  workbench-core/authorization/src/models/deleteGroup.ts
  workbench-core/authorization/src/models/deleteIdentityPermissions.ts
  workbench-core/authorization/src/models/deleteSubjectPermissions.ts
  workbench-core/authorization/src/models/getIdentityPermissionsByIdentity.ts
  workbench-core/authorization/src/models/getIdentityPermissionsBySubject.ts
  workbench-core/authorization/src/models/getUserGroups.ts
  workbench-core/authorization/src/models/getUsersFromGroup.ts
  workbench-core/authorization/src/models/identityPermission.ts
  workbench-core/authorization/src/models/permissionsService.ts
  workbench-core/authorization/src/models/removeUserFromGroup.ts
Labels: size/l

#623 feat: cost center list API
  common/changes/@aws/swb-app/thingut-GALI-1779-list-api_2022-11-16-17-25.json
  common/changes/@aws/workbench-core-accounts/thingut-GALI-1779-list-api_2022-11-16-17-25.json
  common/changes/@aws/workbench-core-base/thingut-GALI-1779-list-api_2022-11-16-17-25.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/package.json
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/validatorHelper.ts
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/costCenter.ts
  workbench-core/accounts/src/models/costCenters/costCenter.ts
  workbench-core/accounts/src/models/costCenters/listCostCentersRequest.test.ts
  workbench-core/accounts/src/models/costCenters/listCostCentersRequest.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/filterRequest.ts
  workbench-core/base/src/interfaces/paginatedResponse.ts
  workbench-core/base/src/interfaces/queryNumberParamFilter.ts
  workbench-core/base/src/interfaces/queryParameterFilter.ts
  workbench-core/base/src/interfaces/queryStringParamFilter.ts
  workbench-core/base/src/schemas/queryParameterFilterSchema.ts
  workbench-core/base/src/utilities/queryParamsFiltersUtils.test.ts
Labels: size/l

#629 feat: add common code for filter using Zod
  common/changes/@aws/swb-app/fix-zod-filter-sort-requests_2022-11-17-16-41.json
  common/changes/@aws/workbench-core-base/fix-zod-filter-sort-requests_2022-11-17-16-41.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/package.json
  solutions/swb-app/src/validatorHelper.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/filterRequest.ts
  workbench-core/base/src/interfaces/paginatedResponse.ts
  workbench-core/base/src/interfaces/queryNumberParamFilter.ts
  workbench-core/base/src/interfaces/queryParameterFilter.ts
  workbench-core/base/src/interfaces/queryStringParamFilter.ts
  workbench-core/base/src/schemas/queryParameterFilterSchema.ts
  workbench-core/base/src/utilities/queryParamsFiltersUtils.test.ts
Labels: size/m

#618 feat: add user to project
  .viperlightignore
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/schemas/assignUserToProject.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/support/resources/projects/projects.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/assignUserToProject.test.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/authorization/src/index.ts
  workbench-core/authorization/src/mockDynamicAuthorizationService.test.ts
Labels: size/m

#633 chore: readme update build fix
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/repo-scripts/repo-toolbox/package.json
Labels: size/s

#634 feat: remove user from project
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
Labels: size/m

#635 fix(ddb): replace old update method which returns mutated type
  common/changes/@aws/workbench-core-accounts/ddb-update-execute-type-fix_2022-11-18-14-54.json
  common/changes/@aws/workbench-core-base/ddb-update-execute-type-fix_2022-11-18-14-54.json
  common/changes/@aws/workbench-core-datasets/ddb-update-execute-type-fix_2022-11-18-14-54.json
  common/changes/@aws/workbench-core-environments/ddb-update-execute-type-fix_2022-11-18-14-54.json
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/interfaces/updateParams.ts
  workbench-core/base/src/aws/helpers/dynamoDB/interfaces/updateUnmarshalledOutput.ts
  workbench-core/base/src/aws/helpers/dynamoDB/updater.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
  workbench-core/environments/src/services/environmentTypeService.ts
Labels: size/m

#632 feat: Update and Delete CostCenter APIs
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/costCenters/costCenter.ts
  workbench-core/accounts/src/models/costCenters/deleteCostCenterRequest.ts
  workbench-core/accounts/src/models/costCenters/updateCostCenterRequest.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/src/services/projectService.ts
Labels: size/l

#642 test: CostCenter integ tests
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/base/resource.ts
  solutions/swb-reference/integration-tests/support/resources/costCenters/costCenter.ts
  solutions/swb-reference/integration-tests/support/resources/costCenters/costCenters.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/costCenter.test.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/src/services/projectService.ts
Labels: size/m

#643 feat: cost center update/list/delete APIs and Integ Tests
  common/changes/@aws/swb-app/thingut-GALI-1779-list-api_2022-11-16-17-25.json
  common/changes/@aws/workbench-core-accounts/thingut-GALI-1779-list-api_2022-11-16-17-25.json
  common/changes/@aws/workbench-core-base/thingut-GALI-1779-list-api_2022-11-16-17-25.json
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/base/resource.ts
  solutions/swb-reference/integration-tests/support/resources/costCenters/costCenter.ts
  solutions/swb-reference/integration-tests/support/resources/costCenters/costCenters.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/costCenter.test.ts
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/costCenter.ts
  workbench-core/accounts/src/models/costCenters/costCenter.ts
  workbench-core/accounts/src/models/costCenters/deleteCostCenterRequest.ts
  workbench-core/accounts/src/models/costCenters/listCostCentersRequest.test.ts
  workbench-core/accounts/src/models/costCenters/listCostCentersRequest.ts
  workbench-core/accounts/src/models/costCenters/updateCostCenterRequest.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/src/services/projectService.ts
  workbench-core/base/src/index.ts
Labels: size/xl

#645 fix: cost center checkDependency
  common/changes/@aws/workbench-core-accounts/fix-costCenter-check-dependency_2022-11-22-21-49.json
  workbench-core/accounts/src/services/costCenterService.ts
Labels: size/s

#646 feat: add check dependency function to dataset service
  common/changes/@aws/workbench-core-datasets/sevu-tasks-add-check-dependency-function_2022-11-23-20-40.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
Labels: size/s

#641 feat: check if dataset mounted
  .viperlightignore
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/datasetRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/schemas/datasetEnvironmentMetadataParser.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/validatorHelper.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.test.ts
  workbench-core/base/README.md
  workbench-core/base/src/index.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/base/src/services/metadataService.ts
  workbench-core/base/src/utilities/paginationHelper.ts
  workbench-core/base/src/utilities/validatorHelper.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
Labels: size/l

#648 feat: added manage metadata methods to metadata service
  common/changes/@aws/swb-app/sevu-tasks-add-metadata-service-methods_2022-11-25-21-00.json
  common/changes/@aws/workbench-core-base/sevu-tasks-add-metadata-service-methods_2022-11-25-21-00.json
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/validatorHelper.ts
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/base/README.md
  workbench-core/base/src/index.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/base/src/services/metadataService.ts
  workbench-core/base/src/utilities/paginationHelper.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/m

#644 feat(project): delete project API
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/schemas/projects/getProjectSchema.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/project.ts
  workbench-core/accounts/src/models/projects/createProjectRequest.ts
  workbench-core/accounts/src/models/projects/deleteProjectRequest.ts
  workbench-core/accounts/src/models/projects/getProjectRequest.ts
  workbench-core/accounts/src/models/projects/listProjectsRequest.ts
  workbench-core/accounts/src/models/projects/listProjectsResponse.ts
  workbench-core/accounts/src/models/projects/project.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/services/projectService.ts
  workbench-core/accounts/src/utilities/projectUtils.test.ts
  workbench-core/accounts/src/utilities/projectUtils.ts
  workbench-core/base/src/utilities/paginationHelper.test.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
Labels: size/l

#650 fix(projects): DELETE project API uses MetadataService
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/schemas/projects/projectMetadataParser.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/services/projectService.ts
Labels: size/m

#651 feat: list users for project by role
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  workbench-core/base/README.md
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/promiseUtils.test.ts
  workbench-core/base/src/utilities/promiseUtils.ts
  workbench-core/base/src/utilities/textUtil.ts
Labels: size/m

#654 chore: test merge commit from topic branch
  .github/workflows/merge-commit-topic-branch-pr-to-feat-branch.yml
Labels: size/s

#655 chore: allow merge commits on feat branch workflow and fix merge-rele…
  .github/workflows/merge-release-pr-to-main.yml
Labels: size/s
