Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2022-10, with the labels that each got.

#502 fix: use CfnDocument
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/package.json
  solutions/swb-reference/src/environment/workflow.ts
Labels: size/s

#503 fix: allow cdk synth in swb-ui without stage file
  solutions/swb-ui/infrastructure/src/constants.ts
Labels: size/s

#511 chore: test branch deletion
  .github/workflows/build-and-test.yml
  .github/workflows/cfn-nag.yml
  .github/workflows/test-deletion.yml
Labels: size/s

#512 chore: Test delete test on merge
  .github/workflows/test-deletion.yml
Labels: size/xs

#513 chore: Test delete test on merge
  .github/workflows/test-deletion.yml
Labels: size/s

#516 chore: Test delete test on merge
  .github/workflows/test-deletion.yml
Labels: size/xs

#518 chore: topic branch test
  .github/workflows/test-deletion.yml
  .github/workflows/test-protection.yml
Labels: size/xs

#517 chore: Test delete test on merge
  .github/workflows/test-deletion.yml
  .github/workflows/test-protection.yml
Labels: size/s

#500 feat: implement remove dataset api
  common/changes/@aws/workbench-core-datasets/feat-implement-removDataset-api_2022-09-30-23-01.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetMetadataPlugin.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsStoragePlugin.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
Labels: size/m

#498 feat: add vpc compatible access points
  common/changes/@aws/workbench-core-accounts-ui/feat-add-vpc-compatible-access-points_2022-09-28-20-17.json
  common/changes/@aws/workbench-core-datasets/feat-add-vpc-compatible-access-points_2022-09-28-19-54.json
  common/changes/@aws/workbench-core-environments-ui/feat-add-vpc-compatible-access-points_2022-09-28-20-17.json
  common/changes/@aws/workbench-core-environments/feat-add-vpc-compatible-access-points_2022-09-28-20-17.json
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/support/complex/accountHelper.ts
  solutions/swb-reference/integration-tests/tests/multiStep/aws-account.test.ts
  solutions/swb-ui/src/pages/environments/new.tsx
  workbench-core/accounts-ui/src/api/projects.ts
  workbench-core/accounts-ui/src/index.tsx
  workbench-core/accounts-ui/src/pages/index.tsx
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsStoragePlugin.ts
  workbench-core/datasets/src/iamHelper.test.ts
  workbench-core/datasets/src/iamHelper.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.test.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
  workbench-core/environments-ui/src/api/environmentTypeConfigs.ts
  workbench-core/environments-ui/src/api/environmentTypes.ts
  workbench-core/environments-ui/src/index.tsx
Labels: size/m

#520 chore: Test delete test on merge
  .github/workflows/test-deletion.yml
Labels: size/xs

#519 chore: feat/* branch protection/deletion
  .github/workflows/enable-feat-protection.yml
  .github/workflows/feat-deletion.yml
Labels: size/s

#505 feat: onboarding template byon
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
Labels: size/l

#526 feat: Create ECS cluster
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-ui/infrastructure/src/SWBUIStack.ts
  solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
Labels: size/s

#523 fix(ui): add missing eslint config
  common/changes/@aws/workbench-core-accounts-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
  common/changes/@aws/workbench-core-datasets-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
  common/changes/@aws/workbench-core-environments-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
  common/changes/@aws/workbench-core-swb-common-ui/sevu-fix-add-eslint-config_2022-10-06-22-09.json
  common/config/rush/pnpm-lock.yaml
  workbench-core/accounts-ui/package.json
  workbench-core/datasets-ui/package.json
  workbench-core/environments-ui/package.json
  workbench-core/swb-common-ui/package.json
Labels: size/s

#525 feat: file upload component
  common/changes/@aws/workbench-core-swb-common-ui/sevu-feat-GALI-1889-file-upload-component_2022-10-07-21-45.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  workbench-core/swb-common-ui/package.json
  workbench-core/swb-common-ui/src/common/utils.ts
  workbench-core/swb-common-ui/src/components/FileUpload/FileUploadComponent.tsx
  workbench-core/swb-common-ui/src/components/FileUpload/SelectedFile.tsx
  workbench-core/swb-common-ui/src/components/FileUpload/SelectedFileList.tsx
  workbench-core/swb-common-ui/src/components/FileUpload/models/FileUpload.ts
  workbench-core/swb-common-ui/src/components/FileUpload/utils.ts
  workbench-core/swb-common-ui/src/index.tsx
Labels: size/l

#510 chore: Update Environment Model
  common/changes/@aws/workbench-core-environments/tmikev-GALI-1789_Remove-datasetIds_2022-10-05-21-01.json
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.test.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/m

#528 refactor: move AuditLogger from base to audit
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/audit/README.md
  workbench-core/audit/package.json
  workbench-core/audit/src/auditLogger.test.ts
  workbench-core/audit/src/auditLogger.ts
  workbench-core/audit/src/index.ts
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/index.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/infrastructure-stack.test.ts.snap
Labels: size/s

#524 feat: implement listStorageLocations API
  common/changes/@aws/swb-app/topic-implement-list-storage-locations-api_2022-10-07-19-38.json
  common/changes/@aws/workbench-core-datasets/topic-implement-list-storage-locations-api_2022-10-07-19-08.json
  common/changes/@aws/workbench-core-environments/topic-implement-list-storage-locations-api_2022-10-13-16-43.json
  solutions/swb-app/src/datasetRoutes.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSet.ts
  workbench-core/datasets/src/dataSetMetadataPlugin.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/schemas/createDataSet.ts
  workbench-core/datasets/src/storageLocation.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
Labels: size/m

#508 refactor: add prefixes to resource IDs
  common/changes/@aws/swb-app/refactor-id-prefixes_2022-10-06-03-45.json
  common/changes/@aws/swb-app/refactor-id-prefixes_2022-10-12-21-38.json
  common/changes/@aws/workbench-core-accounts/refactor-id-prefixes_2022-10-06-03-45.json
  common/changes/@aws/workbench-core-accounts/refactor-id-prefixes_2022-10-12-21-38.json
  common/changes/@aws/workbench-core-base/refactor-id-prefixes_2022-10-12-21-38.json
  common/changes/@aws/workbench-core-datasets/refactor-id-prefixes_2022-10-06-03-45.json
  common/changes/@aws/workbench-core-environments/refactor-id-prefixes_2022-10-06-03-45.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/package.json
  solutions/swb-app/src/datasetRoutes.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/utils/regExpressions.ts
  solutions/swb-reference/integration-tests/support/utils/utilities.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/connections.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/stop.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookLaunchSSM.yaml
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookTerminateSSM.yaml
  solutions/swb-ui/README.md
  workbench-core/accounts/README.md
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
  workbench-core/environments/src/services/environmentTypeService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/m

#533 fix: fix datasets integration tests
  common/changes/@aws/swb-app/fix-integration-tests-fix_2022-10-13-20-02.json
  common/changes/@aws/workbench-core-base/fix-integration-tests-fix_2022-10-13-20-02.json
  common/changes/@aws/workbench-core-datasets/fix-integration-tests-fix_2022-10-13-20-02.json
  solutions/swb-app/package.json
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  workbench-core/base/package.json
  workbench-core/datasets/src/dataSetMetadataPlugin.ts
  workbench-core/datasets/src/dataSetService.ts
Labels: size/s

#537 fix: datasets integration test fix
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/package.json
Labels: size/xs

#535 feat(swb-reference): adding VPC and ALB resources
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.test.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
  solutions/swb-reference/src/infra/SWBVpc.test.ts
  solutions/swb-reference/src/infra/SWBVpc.ts
  workbench-core/environments/README.md
Labels: size/m

#534 feat: updated @aws-sdk/* dependencies
  common/changes/@aws/workbench-core-accounts/topic-aws-sdk-package-updates_2022-10-14-00-28.json
  common/changes/@aws/workbench-core-authentication/topic-aws-sdk-package-updates_2022-10-14-00-28.json
  common/changes/@aws/workbench-core-base/topic-aws-sdk-package-updates_2022-10-14-00-28.json
  common/changes/@aws/workbench-core-datasets/topic-aws-sdk-package-updates_2022-10-14-00-28.json
  common/changes/@aws/workbench-core-environments/topic-aws-sdk-package-updates_2022-10-14-00-28.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/package.json
  workbench-core/accounts/package.json
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/authentication/package.json
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/base/package.json
  workbench-core/datasets/package.json
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/environments/package.json
  workbench-core/environments/src/postDeployment/cognitoSetup.test.ts
Labels: size/m

#531 feat: add CFN dataset IAM role
  common/changes/@aws/workbench-core-datasets/topic-cfn-dataset-iam-role_2022-10-14-14-45.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/awsUtilities/addDatasetPermissionsToRole.test.ts
  workbench-core/datasets/src/awsUtilities/addDatasetPermissionsToRole.ts
  workbench-core/datasets/src/awsUtilities/createRegisterExternalBucketRole.test.ts
  workbench-core/datasets/src/awsUtilities/createRegisterExternalBucketRole.ts
  workbench-core/datasets/src/awsUtilities/iamHelper.test.ts
  workbench-core/datasets/src/awsUtilities/iamHelper.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/errors/errors.test.ts
  workbench-core/datasets/src/errors/invalidIamRoleError.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
Labels: size/l

#542 feat: implement single part file upload api
  common/changes/@aws/workbench-core-base/topic-implement-single-part-file-upload-api_2022-10-18-17-02.json
  common/changes/@aws/workbench-core-datasets/topic-implement-single-part-file-upload-api_2022-10-18-17-02.json
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/s3Service.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsStoragePlugin.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.test.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
Labels: size/m

#545 fix: ecs resource separated from ALB
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/package.json
  solutions/swb-reference/scripts/buildLambda.js
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
  solutions/swb-ui/infrastructure/src/SWBUIStack.ts
  solutions/swb-ui/infrastructure/src/constants.ts
  solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
Labels: size/m

#550 feat: add optional dataset fields
  common/changes/@aws/workbench-core-datasets/topic-optional-dataset-fields_2022-10-18-16-41.json
  solutions/swb-app/src/datasetRoutes.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSet.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
Labels: size/m

#551 fix: viperlight scans
  .viperlightignore
  common/changes/@aws/workbench-core-base/fix-viperlight-scans_2022-10-18-18-17.json
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/scripts/generateCognitoTokens.js
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/postDeployment.ts
  workbench-core/base/src/cognitoTokenService.ts
Labels: size/m

#543 chore: gh workflow update
  .github/workflows/check-and-add-license-header.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/create-release-pr-to-main.yml
  .github/workflows/enable-feat-protection.yml
  .github/workflows/feat-deletion.yml
  .github/workflows/merge-develop-to-stage.yml
  .github/workflows/merge-release-pr-to-main.yml
  .github/workflows/publish-and-merge-to-develop.yml
  .github/workflows/readme-commit.yml
Labels: size/m

#544 feat: env type creation
  common/changes/@aws/swb-app/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
  common/changes/@aws/workbench-core-base/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
  common/changes/@aws/workbench-core-datasets/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
  common/changes/@aws/workbench-core-environments/GALI-1839_EnvTypeCreation_2022-10-15-06-01.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-app/src/environmentTypeRoutes.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/accountHandlerLambda.ts
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/aws/helpers/cloudFormationTemplate.ts
  workbench-core/base/src/aws/helpers/s3Service.ts
  workbench-core/base/src/aws/helpers/serviceCatalogService.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/environmentTypeHandler.test.ts
  workbench-core/environments/src/handlers/environmentTypeHandler.ts
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/interfaces/environmentType.ts
  workbench-core/environments/src/schemas/createEnvironmentType.ts
  workbench-core/environments/src/services/environmentTypeService.test.ts
  workbench-core/environments/src/services/environmentTypeService.ts
Labels: size/l

#552 chore: update codeowners
  .github/CODEOWNERS
Labels: size/s

#555 feat: route alb to apigw
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
Labels: size/s

#557 chore: add viperlight scan as a pre-commit hook
  .github/workflows/pull-request-workflow.yml
  .github/workflows/scripts/viperlight-scan.sh
  .github/workflows/solutions-pipeline-checks.yml
  .viperlightignore
  common/config/rush/command-line.json
  common/git-hooks/pre-commit
Labels: size/m

#553 feat: activate/deactivate user api
  common/changes/@aws/swb-app/topic-activate-deactivate-user-api_2022-10-19-19-39.json
  common/changes/@aws/workbench-core-authentication/topic-activate-deactivate-user-api_2022-10-19-19-39.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/authentication/package.json
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/authentication/src/userManagementPlugin.ts
  workbench-core/authentication/src/userManagementService.test.ts
  workbench-core/authentication/src/userManagementService.ts
Labels: size/l

#558 fix: no such entity exception
  common/changes/@aws/workbench-core-base/sevu-bugs-fix-no-such-entity_2022-10-20-16-00.json
  workbench-core/base/README.md
  workbench-core/base/src/utilities/iamRoleCloneService.test.ts
  workbench-core/base/src/utilities/iamRoleCloneService.ts
Labels: size/s

#562 feat: cognito construct update
  common/changes/@aws/workbench-core-infrastructure/fix-cognito-construct-update_2022-10-20-20-33.json
  workbench-core/infrastructure/docs/workbenchCognito.md
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/m

#563 fix(swb-reference): updated postDeployment file path parsing
  common/changes/@aws/workbench-core-environments/patch-post-deployment-script-update_2022-10-20-22-12.json
  workbench-core/environments/src/postDeployment/serviceCatalogSetup.ts
Labels: size/s

#556 feat(workbench-core/authentication): updated User interface to include status
  common/changes/@aws/workbench-core-authentication/topic-user-interface-update_2022-10-20-18-23.json
  common/git-hooks/pre-commit
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/authentication/src/user.ts
  workbench-core/authentication/src/userManagementPlugin.ts
  workbench-core/authentication/src/userManagementService.test.ts
  workbench-core/authentication/src/userManagementService.ts
Labels: size/m

#560 feat: [GALI-1784] GET /aws-account/:id
  solutions/swb-app/src/accountRoutes.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/hostingAccountService.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/base/src/constants/resourceTypeToKey.ts
Labels: size/m

#564 fix: cognito construct fix
  common/changes/@aws/workbench-core-infrastructure/fix-cognito-construct-fix_2022-10-20-23-53.json
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/s

#559 feat(workbench-core/authentication): listUsers refactor
  common/changes/@aws/swb-app/topic-list-users-refactor_2022-10-21-00-43.json
  common/changes/@aws/workbench-core-authentication/topic-list-users-refactor_2022-10-21-00-43.json
  solutions/swb-app/src/userRoutes.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/authentication/src/userManagementPlugin.ts
  workbench-core/authentication/src/userManagementService.ts
Labels: size/m

#565 fix: consistent error response from ALB vs APIGW
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/utils/HttpError.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
  solutions/swb-ui/infrastructure/src/SWBUIStack.ts
  solutions/swb-ui/infrastructure/src/constants.ts
Labels: size/m

#567 feat(workbench-core/authentication): BREAKING CHANGE - createUser returns created User
  common/changes/@aws/workbench-core-authentication/topic-refactor-create-user_2022-10-21-16-39.json
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/authentication/src/userManagementPlugin.ts
  workbench-core/authentication/src/userManagementService.test.ts
  workbench-core/authentication/src/userManagementService.ts
Labels: size/s

#568 fix: route validation for ETC
  common/changes/@aws/swb-app/fix-route-validation-etc_2022-10-21-21-40.json
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
Labels: size/s

#566 feat(authorization): DynamoDBDynamicPermissionsPlugin implemented
  common/config/rush/pnpm-lock.yaml
  workbench-core/authorization/README.md
  workbench-core/authorization/config/jest.config.json
  workbench-core/authorization/package.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicPermissionsPluginInputs.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamoDBDynamicPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamoDBDynamicPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamoDbIdentityItem.ts
  workbench-core/authorization/src/dynamicAuthorization/errors/badConfigurationError.ts
  workbench-core/authorization/src/dynamicAuthorization/errors/groupAlreadyExistsError.ts
  workbench-core/authorization/src/dynamicAuthorization/errors/groupNotFoundError.ts
  workbench-core/authorization/src/dynamicAuthorization/errors/throughputExceededError.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/updater.ts
Labels: size/xl

#569 feat: [GALI-1777 & 1778] GET & POST /costCenter
  common/changes/@aws/swb-app/atmikev-GALI-1777_CreateCostCenter_2022-10-21-22-05.json
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-1777_CreateCostCenter_2022-10-21-22-05.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-1777_CreateCostCenter_2022-10-21-22-05.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/integration-tests/tests/isolated/aws-accounts/create.test.ts
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/account.ts
  workbench-core/accounts/src/models/costCenter.ts
  workbench-core/accounts/src/models/createCostCenterRequest.ts
  workbench-core/accounts/src/schemas/createAccount.ts
  workbench-core/accounts/src/schemas/createCostCenter.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/ddUtil.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/ddbUtil.ts
  workbench-core/base/src/constants/resourceTypeToKey.ts
  workbench-core/base/src/index.ts
Labels: size/l

#572 chore: Add Cost Center to Postman
  solutions/swb-reference/SWBv2.postman_collection.json
Labels: size/s

#515 fix: environment launch metadata error handling
  common/changes/@aws/workbench-core-environments/refactor-environment-launch-metadata-error-handling_2022-10-24-23-59.json
  common/changes/@aws/workbench-core-environments/refactor-environment-launch-metadata-error-handling_2022-10-25-00-22.json
  workbench-core/environments/README.md
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
Labels: size/m

#574 feat: CREATE Project API
  README.md
  common/changes/@aws/swb-app/maghirardelli-gali-1737-create-project-api_2022-10-25-19-39.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-gali-1737-create-project-api_2022-10-25-19-39.json
  common/changes/@aws/workbench-core-base/maghirardelli-gali-1737-create-project-api_2022-10-25-19-39.json
  common/changes/@aws/workbench-core-environments/maghirardelli-gali-1737-create-project-api_2022-10-25-19-39.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/schemas/projects/createProjectSchema.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  workbench-core/accounts/README.md
  workbench-core/accounts/package.json
  workbench-core/accounts/src/constants/hostingAccountStatus.ts
  workbench-core/accounts/src/constants/projectStatus.ts
  workbench-core/accounts/src/models/createProjectRequest.ts
  workbench-core/accounts/src/models/project.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/services/projectService.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/services/environmentService.ts
Labels: size/l

#571 feat: add isAuthorizedOnDynamicOperations to CASL Authorization Plugin
  workbench-core/authorization/README.md
  workbench-core/authorization/src/__mocks__/authorizationPlugin.ts
  workbench-core/authorization/src/authorizationPlugin.ts
  workbench-core/authorization/src/authorizationService.ts
  workbench-core/authorization/src/caslAuthorizationPlugin.test.ts
  workbench-core/authorization/src/caslAuthorizationPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicPermissionsPluginInputs.ts
  workbench-core/authorization/src/index.ts
  workbench-core/authorization/src/operation.ts
  workbench-core/authorization/src/permissionsPlugin.ts
  workbench-core/authorization/src/routesMap.ts
  workbench-core/authorization/src/staticPermissionsPlugin.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/infrastructure-stack.test.ts.snap
Labels: size/m

#580 chore: accounts api develop update
  README.md
  common/changes/@aws/swb-app/atmikev-GALI-1777_CreateCostCenter_2022-10-21-22-05.json
  common/changes/@aws/swb-app/fix-route-validation-etc_2022-10-21-21-40.json
  common/changes/@aws/swb-app/topic-list-users-refactor_2022-10-21-00-43.json
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-1777_CreateCostCenter_2022-10-21-22-05.json
  common/changes/@aws/workbench-core-authentication/topic-list-users-refactor_2022-10-21-00-43.json
  common/changes/@aws/workbench-core-authentication/topic-refactor-create-user_2022-10-21-16-39.json
  common/changes/@aws/workbench-core-authentication/topic-user-interface-update_2022-10-20-18-23.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-1777_CreateCostCenter_2022-10-21-22-05.json
  common/changes/@aws/workbench-core-base/sevu-bugs-fix-no-such-entity_2022-10-20-16-00.json
  common/changes/@aws/workbench-core-environments/patch-post-deployment-script-update_2022-10-20-22-12.json
  common/changes/@aws/workbench-core-environments/refactor-environment-launch-metadata-error-handling_2022-10-24-23-59.json
  common/changes/@aws/workbench-core-environments/refactor-environment-launch-metadata-error-handling_2022-10-25-00-22.json
  common/changes/@aws/workbench-core-infrastructure/fix-cognito-construct-fix_2022-10-20-23-53.json
  common/changes/@aws/workbench-core-infrastructure/fix-cognito-construct-update_2022-10-20-20-33.json
  common/git-hooks/pre-commit
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/account.ts
  workbench-core/accounts/src/models/costCenter.ts
  workbench-core/accounts/src/models/createCostCenterRequest.ts
  workbench-core/accounts/src/schemas/createAccount.ts
  workbench-core/accounts/src/schemas/createCostCenter.ts
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
  workbench-core/accounts/src/services/hostingAccountService.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/authentication/src/user.ts
  workbench-core/authentication/src/userManagementPlugin.ts
  workbench-core/authentication/src/userManagementService.test.ts
  workbench-core/authentication/src/userManagementService.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/ddUtil.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/ddbUtil.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/iamRoleCloneService.test.ts
  workbench-core/base/src/utilities/iamRoleCloneService.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/postDeployment/serviceCatalogSetup.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/infrastructure/docs/workbenchCognito.md
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/xl

#570 feat: use cert provided by admin
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
Labels: size/s

#575 refactor(workbench-core/authentication): refactored error messages
  common/changes/@aws/workbench-core-authentication/topic-user-management-error-message-refactor_2022-10-26-22-59.json
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/authentication/src/userManagementPlugin.ts
  workbench-core/authentication/src/userManagementService.ts
Labels: size/m

#576 feat(environment type filter): add dynamic operators capability to en…
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/environmentTypeRoutes.ts
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/FilterRequest.ts
  workbench-core/base/src/interfaces/SortRequest.ts
  workbench-core/base/src/interfaces/queryParameterFilter.ts
  workbench-core/base/src/schemas/queryParameterFilterSchema.ts
  workbench-core/base/src/utilities/queryParamsFiltersUtils.test.ts
  workbench-core/base/src/utilities/queryParamsFiltersUtils.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/interfaces/listEnvironmentTypesRequest.ts
  workbench-core/environments/src/schemas/listEnvironmentTypes.ts
  workbench-core/environments/src/services/environmentTypeService.test.ts
  workbench-core/environments/src/services/environmentTypeService.ts
Labels: size/l

#583 feat(byon): transit gateway enablement
  solutions/swb-reference/src/templates/README.md
  solutions/swb-reference/src/templates/new-firewall-vpc.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
Labels: size/xl

#577 feat: dynamic authorization service implemented
  common/config/rush/pnpm-lock.yaml
  workbench-core/audit/tsconfig.json
  workbench-core/authorization/README.md
  workbench-core/authorization/config/jest.config.json
  workbench-core/authorization/package.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicPermissionsPluginInputs.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamoDBDynamicPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/errors/errors.test.ts
  workbench-core/authorization/src/index.ts
  workbench-core/example/infrastructure/src/__tests__/__snapshots__/infrastructure-stack.test.ts.snap
Labels: size/l
