Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2022-08, with the labels that each got.

#439 docs: add datasets APIs
  solutions/swb-reference/SWBv2.postman_collection.json
Labels: size/m

#431 feat: get cognito access_token programmatically
  solutions/swb-reference/README.md
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/stop.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  solutions/swb-reference/scripts/generateCognitoTokens.js
  workbench-core/base/src/cognitoTokenService.ts
  workbench-core/base/src/index.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/m

#438 feat: automate deployment script
  solutions/swb-ui/.env. production
  solutions/swb-ui/.env.development
  solutions/swb-ui/README.md
  solutions/swb-ui/package.json
  solutions/swb-ui/scripts/deploy.sh
  solutions/swb-ui/scripts/dev.sh
Labels: size/s

#442 chore: hpc fixes
  solutions/swb-reference/scripts/runLocally.sh
  solutions/swb-reference/src/HPC/README.md
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
  solutions/swb-ui/scripts/updatePlugins.sh
Labels: size/s

#441 fix: launch constraint role needs 'sagemaker:AddTags' permission
  solutions/swb-reference/src/SWBStack.ts
Labels: size/xs

#443 chore: remove HPC specific code
  common/config/rush/pnpm-lock.yaml
  rush.json
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/HPC/AWS ParallelClusters.postman_collection.json
  solutions/swb-reference/src/HPC/HPCService.test.ts
  solutions/swb-reference/src/HPC/HPCService.ts
  solutions/swb-reference/src/HPC/HPCServiceHelper.test.ts
  solutions/swb-reference/src/HPC/HPCServiceHelper.ts
  solutions/swb-reference/src/HPC/HPCTypes.ts
  solutions/swb-reference/src/HPC/README.md
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
  solutions/swb-ui/package.json
  solutions/swb-ui/scripts/apps_menu.js
  solutions/swb-ui/scripts/updatePlugins.sh
  solutions/swb-ui/src/pages/apps/My_Create_React_App_Using_TS.tsx
  solutions/swb-ui/src/pages/apps/placeholder
Labels: size/xl

#444 docs(component): updated readME and added test job folder
  solutions/swb-reference/src/HPC/README.md
  solutions/swb-reference/src/HPC/artifacts/AWS ParallelClusters.postman_collection.json
  solutions/swb-reference/src/HPC/artifacts/test_job/data.txt
  solutions/swb-reference/src/HPC/artifacts/test_job/test.sh
Labels: size/s

#446 fix: runLocally script
  solutions/swb-reference/scripts/runLocally.sh
Labels: size/xs

#447 feat: release workbench-core-base v0.1.2 and workbench-core-infrastructure v0.1.1
  .github/codeql/codeql-config.yml
  .github/workflows/security-code-scanning.yml
  README.md
  solutions/swb-app/CHANGELOG.json
  solutions/swb-app/CHANGELOG.md
  solutions/swb-app/NOTICE
  solutions/swb-app/package.json
  solutions/swb-reference/README.md
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/stop.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  solutions/swb-reference/scripts/generateCognitoTokens.js
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-ui/.env. production
  solutions/swb-ui/.env.development
  solutions/swb-ui/README.md
  solutions/swb-ui/package.json
  solutions/swb-ui/scripts/deploy.sh
  solutions/swb-ui/scripts/dev.sh
  workbench-core/base/CHANGELOG.json
  workbench-core/base/CHANGELOG.md
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/cognitoTokenService.ts
  workbench-core/base/src/index.ts
  workbench-core/datasets/CHANGELOG.json
  workbench-core/datasets/CHANGELOG.md
  workbench-core/datasets/NOTICE
  workbench-core/datasets/package.json
  workbench-core/environments/CHANGELOG.json
  workbench-core/environments/CHANGELOG.md
  workbench-core/environments/NOTICE
  workbench-core/environments/package.json
  workbench-core/infrastructure/CHANGELOG.json
  workbench-core/infrastructure/CHANGELOG.md
  workbench-core/infrastructure/package.json
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/l

#440 fix: download cfn template file to create md5 sum because encrypted S3 files Etag doesn't match md5
  workbench-core/environments/src/postDeployment/serviceCatalogSetup.test.ts
  workbench-core/environments/src/postDeployment/serviceCatalogSetup.ts
Labels: size/s

#448 docs: update documentation with information about CWL
  solutions/swb-reference/README.md
  solutions/swb-reference/SETUP_v2p1.md
Labels: size/s

#455 fix(swb deployment): fix files outputs to be json
  .gitignore
  solutions/swb-reference/package.json
  solutions/swb-reference/src/constants.ts
  solutions/swb-ui/infrastructure/package.json
  solutions/swb-ui/infrastructure/src/constants.ts
  solutions/swb-ui/scripts/deploy.sh
  solutions/swb-ui/scripts/dev.sh
Labels: size/s

#453 test: integration test SWB env with DS
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/complex/datasetHelper.ts
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/base/collectionResource.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/jest.config.js
  solutions/swb-reference/package.json
  solutions/swb-reference/scripts/generateCognitoTokens.js
  workbench-core/base/src/index.ts
Labels: size/m

#457 fix: config path for integ test
  solutions/swb-reference/jest.config.js
Labels: size/xs

#451 ci: update PR process
  .github/workflows/create-release-branch.yml
  .github/workflows/license-checker.yml
  .github/workflows/publish-and-merge-to-develop.yml
  .github/workflows/verify-changefiles.yml
  common/changes/@aws/swb-app/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-audit/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-authentication/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-authorization/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-base/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-datasets/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-environments/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-infrastructure/feat-updatePRprocess_2022-08-12-02-01.json
  common/changes/@aws/workbench-core-logging/feat-updatePRprocess_2022-08-12-02-01.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/command-line.json
  common/config/rush/pnpm-lock.yaml
  solutions/example-ui-app/package.json
  solutions/swb-app/package.json
  solutions/swb-reference/package.json
  solutions/swb-ui/infrastructure/package.json
  solutions/swb-ui/package.json
  workbench-core/audit/package.json
  workbench-core/authentication/package.json
  workbench-core/authorization/package.json
  workbench-core/base/package.json
  workbench-core/datasets/package.json
  workbench-core/environments/package.json
  workbench-core/eslint-custom/package.json
  workbench-core/example/express/package.json
  workbench-core/example/infrastructure/package.json
  workbench-core/infrastructure/package.json
  workbench-core/logging/package.json
  workbench-core/repo-scripts/repo-toolbox/package.json
Labels: size/m

#445 fix: cookies not being stored correctly
  common/changes/@aws/swb-app/fix-re-enable-cookie-based-authentication_2022-08-15-17-33.json
  common/changes/@aws/workbench-core-authentication/fix-re-enable-cookie-based-authentication_2022-08-15-17-33.json
  common/changes/@aws/workbench-core-environments/fix-re-enable-cookie-based-authentication_2022-08-15-17-33.json
  common/changes/@aws/workbench-core-infrastructure/fix-re-enable-cookie-based-authentication_2022-08-15-17-33.json
  solutions/swb-app/src/authRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/package.json
  solutions/swb-ui/package.json
  solutions/swb-ui/src/api/apiHelper.ts
  solutions/swb-ui/src/api/auth.ts
  workbench-core/authentication/src/__mocks__/utils.ts
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationMiddleware.ts
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/tokens.ts
  workbench-core/authentication/src/utils.test.ts
  workbench-core/authentication/src/utils.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/l

#461 test: valid and invalid env status
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
Labels: size/s

#463 fix: authN verify token fix
  common/changes/@aws/workbench-core-authentication/fix-authn-verify-token-fix_2022-08-16-19-54.json
  workbench-core/authentication/src/authenticationMiddleware.ts
Labels: size/s

#464 fix: add ignore license checker when package.json changes are not detected
  .github/workflows/ignore-license-checker.yml
Labels: size/s

#449 feat: changed authentication service to take a website param for redirection after login/logout
  common/changes/@aws/swb-app/feat-authn-dynamic-website-url_2022-08-16-20-18.json
  common/changes/@aws/workbench-core-authentication/feat-authn-dynamic-website-url_2022-08-16-20-18.json
  common/changes/@aws/workbench-core-infrastructure/feat-authn-dynamic-website-url_2022-08-16-20-18.json
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/support/complex/datasetHelper.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
  workbench-core/authentication/docs/authenticationMiddleware.md
  workbench-core/authentication/src/__mocks__/authenticationService.ts
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationMiddleware.ts
  workbench-core/authentication/src/authenticationPlugin.ts
  workbench-core/authentication/src/authenticationService.test.ts
  workbench-core/authentication/src/authenticationService.ts
  workbench-core/authentication/src/plugins/__mocks__/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.ts
  workbench-core/infrastructure/README.md
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/l

#466 chore: extend access token expiration time
  common/changes/@aws/workbench-core-infrastructure/chore-extend-access-token_2022-08-17-14-09.json
  solutions/swb-reference/src/SWBStack.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/s

#467 feat: integration test pipeline
  .github/workflows/deploy-integration-swb-reference.yml
  .gitignore
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/clientSession.ts
Labels: size/m

#458 feat(environments multi step test): add environments multi step test
  common/changes/@aws/workbench-core-infrastructure/feat-Environments-MultiStep-Test_2022-08-18-15-37.json
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/support/models/environments.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/support/utils/constants.ts
  solutions/swb-reference/integration-tests/support/utils/utilities.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/m

#468 docs: rush add instructions for developers
  DEVELOPMENT.md
Labels: size/xs

#470 refactor: UI design system refactor
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-ui/README.md
  solutions/swb-ui/next.config.js
  solutions/swb-ui/package.json
  solutions/swb-ui/src/common/alerts.tsx
  solutions/swb-ui/src/common/dateRelativeOptions.tsx
  solutions/swb-ui/src/common/dateRelativeProperties.tsx
  solutions/swb-ui/src/common/labels.tsx
  solutions/swb-ui/src/common/splitPanel.tsx
  solutions/swb-ui/src/common/tableEmptyState.tsx
  solutions/swb-ui/src/common/tableNoMatchState.tsx
  solutions/swb-ui/src/components/BaseLayout.tsx
  solutions/swb-ui/src/components/EnvTypeCards.tsx
  solutions/swb-ui/src/components/EnvTypeConfigCards.tsx
  solutions/swb-ui/src/components/EnvironmentConnectModal.tsx
  solutions/swb-ui/src/components/Header.tsx
  solutions/swb-ui/src/components/Hero.tsx
  solutions/swb-ui/src/components/Login.tsx
  solutions/swb-ui/src/components/Navigation.tsx
  solutions/swb-ui/src/context/NotificationContext.tsx
  solutions/swb-ui/src/environments-table-config/workspacesColumnDefinitions.tsx
  solutions/swb-ui/src/environments-table-config/workspacesFilteringOptions.tsx
  solutions/swb-ui/src/environments-table-config/workspacesFilteringProperties.tsx
  solutions/swb-ui/src/models/User.ts
  solutions/swb-ui/src/pages/_app.tsx
  solutions/swb-ui/src/pages/environments/index.tsx
  solutions/swb-ui/src/pages/environments/new.tsx
  solutions/swb-ui/src/pages/index.tsx
  solutions/swb-ui/src/pages/users/index.tsx
  solutions/swb-ui/src/pages/users/new.tsx
  solutions/swb-ui/src/styles/Header.module.scss
  solutions/swb-ui/src/styles/globals.scss
  solutions/swb-ui/src/users-table-config/usersColumnDefinitions.tsx
Labels: size/m

#469 docs: updated workbench cognito documentation
  common/changes/@aws/workbench-core-infrastructure/doc-workbench-cognito-cdk-construct_2022-08-19-18-47.json
  workbench-core/infrastructure/README.md
  workbench-core/infrastructure/docs/workbenchCognito.md
Labels: size/m

#476 chore: add slack notification for Merge-develop-to-stage workflow failure
  .github/actions/notification/action.yml
  .github/workflows/deploy-integration-swb-reference.yml
  .github/workflows/deploy-swb-reference-demo.yml
  .github/workflows/merge-develop-to-stage.yml
  .github/workflows/readme-commit.yml
Labels: size/s

#474 feat: add license-check-and-add to all packages. and automate adding license headers
  .github/workflows/check-and-add-license-header.yml
  .licenseignorefile
  apache-license-header.txt
  common/changes/@aws/swb-app/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-audit/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-authentication/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-authorization/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-base/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-datasets/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-environments/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-infrastructure/feat-addApacheHeader_2022-08-23-06-35.json
  common/changes/@aws/workbench-core-logging/feat-addApacheHeader_2022-08-23-06-35.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/command-line.json
  common/config/rush/pnpm-lock.yaml
  solutions/example-ui-app/license-add-config.json
  solutions/example-ui-app/package.json
  solutions/swb-app/license-add-config.json
  solutions/swb-app/package.json
  solutions/swb-reference/license-add-config.json
  solutions/swb-reference/package.json
  solutions/swb-ui/infrastructure/license-add-config.json
  solutions/swb-ui/infrastructure/package.json
  solutions/swb-ui/license-add-config.json
  solutions/swb-ui/package.json
  workbench-core/audit/license-add-config.json
  workbench-core/audit/package.json
  workbench-core/authentication/license-add-config.json
  workbench-core/authentication/package.json
  workbench-core/authorization/license-add-config.json
  workbench-core/authorization/package.json
  workbench-core/base/license-add-config.json
  workbench-core/base/package.json
  workbench-core/datasets/license-add-config.json
  workbench-core/datasets/package.json
  workbench-core/environments/license-add-config.json
  workbench-core/environments/package.json
  workbench-core/eslint-custom/license-add-config.json
  workbench-core/eslint-custom/package.json
  workbench-core/example/express/license-add-config.json
  workbench-core/example/express/package.json
  workbench-core/example/infrastructure/license-add-config.json
  workbench-core/example/infrastructure/package.json
  workbench-core/infrastructure/license-add-config.json
  workbench-core/infrastructure/package.json
  workbench-core/logging/license-add-config.json
  workbench-core/logging/package.json
  workbench-core/repo-scripts/repo-toolbox/license-add-config.json
  workbench-core/repo-scripts/repo-toolbox/package.json
Labels: size/l

#477 fix(environment multistep integration test): fix environments throttling issue
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/support/utils/constants.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
Labels: size/s

#478 chore: fix slack notification
  .github/actions/notification/action.yml
  .github/workflows/deploy-integration-swb-reference.yml
  .github/workflows/deploy-swb-reference-demo.yml
  .github/workflows/merge-develop-to-stage.yml
  .github/workflows/readme-commit.yml
Labels: size/s

#465 feat: add csrf protection
  common/changes/@aws/swb-app/feat-add-csrf-protection_2022-08-19-16-14.json
  common/changes/@aws/workbench-core-authentication/feat-add-csrf-protection_2022-08-19-16-14.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-ui/src/api/apiHelper.ts
  solutions/swb-ui/src/api/auth.ts
  solutions/swb-ui/src/context/AuthenticationContext.tsx
  workbench-core/authentication/docs/authenticationMiddleware.md
  workbench-core/authentication/package.json
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationMiddleware.ts
  workbench-core/authentication/src/index.ts
Labels: size/m

#475 docs: Adding /doc folder and workspace troubleshooting files.
  solutions/swb-reference/README.md
  solutions/swb-reference/docs/WorkspaceLifecycleTroubleshootingGuide.md
  solutions/swb-reference/docs/launch-terminate-workflow.jpg
  solutions/swb-reference/docs/start-stop-workflow.jpg
Labels: size/s

#480 fix: added csrf to integration tests and postman collection
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/README.md
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/scripts/generateCognitoTokens.js
Labels: size/m

#481 feat: cypress integration
  .gitignore
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/README.md
  solutions/swb-reference/cypress.config.ts
  solutions/swb-reference/end-to-end-tests/config/example.yaml
  solutions/swb-reference/end-to-end-tests/cypress/common/login.cy.ts
  solutions/swb-reference/end-to-end-tests/cypress/fixtures/example.json
  solutions/swb-reference/end-to-end-tests/cypress/support/commands.ts
  solutions/swb-reference/end-to-end-tests/cypress/support/constants.ts
  solutions/swb-reference/end-to-end-tests/cypress/support/e2e.ts
  solutions/swb-reference/package.json
  solutions/swb-ui/src/components/Login.tsx
  solutions/swb-ui/src/pages/environments/index.tsx
Labels: size/m
