Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2022-09, with the labels that each got.

#486 fix: datasets base UI page
  common/changes/@aws/workbench-core-datasets-ui/fix-datasets-ui_2022-09-02-17-29.json
  workbench-core/datasets-ui/src/api/datasets.ts
  workbench-core/datasets-ui/src/pages/index.tsx
Labels: size/s

#485 feat(swb-common-ui): refresh access token
  common/changes/@aws/workbench-core-swb-common-ui/feat-refresh-access-token_2022-09-02-15-27.json
  workbench-core/swb-common-ui/src/api/apiHelper.ts
  workbench-core/swb-common-ui/src/context/AuthenticationContext.tsx
Labels: size/s

#487 docs(integration testing): update readme for integration testing
  common/changes/@aws/workbench-core-datasets-ui/docs-integration-testing-readme_2022-09-07-16-15.json
  solutions/swb-reference/README.md
  solutions/swb-ui/package.json
  workbench-core/datasets-ui/package.json
Labels: size/m

#488 test: aws accounts integ test
  common/changes/@aws/workbench-core-datasets/test-aws-accounts-integ-test_2022-09-14-16-54.json
  common/changes/@aws/workbench-core-environments/test-aws-accounts-integ-test_2022-09-14-16-54.json
  common/config/rush/pnpm-lock.yaml
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/support/complex/accountHelper.ts
  solutions/swb-reference/integration-tests/support/complex/checkEventBridgePermission.ts
  solutions/swb-reference/integration-tests/support/complex/datasetHelper.ts
  solutions/swb-reference/integration-tests/support/complex/deleteAccount.ts
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/accounts/account.ts
  solutions/swb-reference/integration-tests/support/resources/accounts/accounts.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/aws-accounts/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/aws-account.test.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/SWBStack.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/iamHelper.test.ts
  workbench-core/datasets/src/iamHelper.ts
  workbench-core/environments/src/services/accountService.ts
Labels: size/l

#490 fix: readme file coverage report for new packages
  common/changes/@aws/workbench-core-accounts-ui/fix-readme-commit_2022-09-16-19-20.json
  common/changes/@aws/workbench-core-environments-ui/fix-readme-commit_2022-09-16-19-20.json
  workbench-core/accounts-ui/README.md
  workbench-core/environments-ui/README.md
Labels: size/s

#492 chore: fix for accounts-ui Readme commit build
  common/changes/@aws/workbench-core-accounts-ui/readme-commit_2022-09-19-21-22.json
  common/changes/@aws/workbench-core-environments-ui/readme-commit_2022-09-19-21-22.json
  solutions/swb-ui/package.json
  workbench-core/accounts-ui/config/heft.json
  workbench-core/accounts-ui/config/jest.config.json
  workbench-core/accounts-ui/config/rig.json
  workbench-core/environments-ui/package.json
Labels: size/m

#493 fix: env UI package heft
  common/changes/@aws/workbench-core-accounts-ui/fix-env-ui-package-heft_2022-09-19-21-56.json
  common/changes/@aws/workbench-core-environments-ui/fix-env-ui-package-heft_2022-09-19-21-56.json
  workbench-core/accounts-ui/README.md
  workbench-core/environments-ui/README.md
  workbench-core/environments-ui/config/heft.json
  workbench-core/environments-ui/config/jest.config.json
  workbench-core/environments-ui/config/rig.json
Labels: size/m

#491 feat: environments e2e test
  .github/workflows/deploy-integration-swb-reference.yml
  .gitignore
  common/changes/@aws/workbench-core-environments-ui/feat-environmentsE2ETest_2022-09-19-14-36.json
  common/changes/@aws/workbench-core-swb-common-ui/feat-environmentsE2ETest_2022-09-19-14-36.json
  solutions/swb-reference/cypress.config.ts
  solutions/swb-reference/end-to-end-tests/config/example.yaml
  solutions/swb-reference/end-to-end-tests/config/testEnv.yaml
  solutions/swb-reference/end-to-end-tests/cypress/integration/common/environments.cy.ts
  solutions/swb-reference/end-to-end-tests/cypress/integration/common/login.cy.ts
  solutions/swb-reference/end-to-end-tests/cypress/support/common-utils.ts
  solutions/swb-reference/end-to-end-tests/cypress/support/constants.ts
  solutions/swb-reference/end-to-end-tests/cypress/support/environments-utils.ts
  solutions/swb-reference/end-to-end-tests/cypress/support/models.ts
  solutions/swb-ui/scripts/deploy.sh
  workbench-core/environments-ui/src/api/environments.ts
  workbench-core/environments-ui/src/components/EnvTypeCards.tsx
  workbench-core/environments-ui/src/components/EnvTypeConfigCards.tsx
  workbench-core/environments-ui/src/components/EnvironmentConnectModal.tsx
  workbench-core/environments-ui/src/environments-table-config/workspacesColumnDefinitions.tsx
  workbench-core/environments-ui/src/pages/environments/index.tsx
  workbench-core/environments-ui/src/pages/environments/new.tsx
  workbench-core/swb-common-ui/src/components/Navigation.tsx
Labels: size/l

#494 fix: fix UI deploy script
  solutions/swb-ui/scripts/deploy.sh
Labels: size/xs

#495 fix: fix GitHub e2e pipeline
  .github/workflows/deploy-integration-swb-reference.yml
Labels: size/xs

#496 fix: Fix GitHub params
  .github/workflows/merge-develop-to-stage.yml
Labels: size/xs

#499 fix: terminate postman
  solutions/swb-reference/SWBv2.postman_collection.json
Labels: size/xs
