Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2023-02, with the labels that each got.

#810 fix(swb): fix integ tests and proxyLambda. Added swbv2-private test c…
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/integration-tests/config/swbv2-private.yaml
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/assignUserToProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/activateDeactivateUser.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
Labels: size/s

#811 chore: pnpm override -> caniuse-lite: latest
  .gitignore
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
Labels: size/xs

#813 fix: update jszip due to vulnerability
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
Labels: size/xs

#814 fix: add e2etest config for byon env
  .gitignore
  solutions/swb-ui/ui/end-to-end-tests/config/swbv2-private.yaml
Labels: size/xs

#816 fix: proxy lambda headers fix
  common/config/rush/pnpm-config.json
  solutions/swb-reference/src/proxyHandlerLambda.ts
  solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
Labels: size/s

#818 fix(swb ui): fix e2e issue with path and remove studies from e2e test
  solutions/swb-ui/ui/end-to-end-tests/config/testEnv.yaml
  solutions/swb-ui/ui/end-to-end-tests/cypress/support/commands.ts
Labels: size/xs

#819 fix: test retry attempts
  .github/workflows/merge-develop-to-stage.yml
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-ui/ui/end-to-end-tests/cypress/integration/common/environments.cy.ts
  solutions/swb-ui/ui/end-to-end-tests/cypress/integration/common/login.cy.ts
Labels: size/m

#820 fix: env list cypress
  solutions/swb-ui/ui/end-to-end-tests/cypress/support/environments-utils.ts
Labels: size/xs

#822 fix: fix audit service logging of errors and additional metadata
  common/changes/@aws/workbench-core-audit/topic-auditServiceIntegTest_2023-02-03-21-59.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/example-ui-app/cache/config.json
  workbench-core/audit/README.md
  workbench-core/audit/config/jest.config.json
  workbench-core/audit/package.json
  workbench-core/audit/src/auditEntry.ts
  workbench-core/audit/src/auditMiddleware.test.ts
  workbench-core/audit/src/auditService.test.ts
  workbench-core/audit/src/auditService.ts
  workbench-core/audit/src/baseExtractor.ts
  workbench-core/audit/src/errors/auditIncompleteError.ts
  workbench-core/audit/src/errors/errors.test.ts
  workbench-core/audit/src/index.ts
  workbench-core/audit/src/metadata.ts
  workbench-core/audit/src/plugins/auditLogger.test.ts
  workbench-core/audit/src/plugins/auditLogger.ts
  workbench-core/audit/src/plugins/baseAuditPlugin.test.ts
  workbench-core/audit/src/plugins/baseAuditPlugin.ts
Labels: size/m

#805 fix(ddb): add method with proper return type for delete
  common/changes/@aws/workbench-core-base/maghirardelli-ddb-ddbservice-delete-fix-return-type_2023-01-31-17-22.json
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.ts
  workbench-core/base/src/interfaces/deleteItemParams.ts
Labels: size/s

#803 test: added verifyToken integ tests
  common/changes/@aws/workbench-core-user-management/test-verify-token-integ-tests_2023-01-30-22-52.json
  workbench-core/example/infrastructure/integration-tests/support/resources.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/middleware.test.ts
  workbench-core/user-management/src/userManagementPlugin.ts
Labels: size/m

#817 docs: instructions to fix pnpm audit errors
  DEVELOPMENT.md
Labels: size/s

#808 test: added csurf integ tests
  workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/middleware.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/activateDeactivateUser.test.ts
Labels: size/s

#771 feat: GALI-2152 Attach Project To (New and Existing) DataSet
  common/changes/@aws/swb-app/atmikev-GALI-2152_AttachProjectToDataset_2023-01-13-23-01.json
  common/changes/@aws/workbench-core-authorization/atmikev-GALI-2152_AttachProjectToDataset_2023-01-13-23-01.json
  common/changes/@aws/workbench-core-datasets/atmikev-GALI-2152_AttachProjectToDataset_2023-01-31-21-45.json
  solutions/swb-app/README.md
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/createDataSetRequestParser.ts
  solutions/swb-app/src/dataSets/createProvisionDatasetRequest.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/permissionsResponseParser.ts
  solutions/swb-app/src/dataSets/projectAccessRequestParser.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/users/authenticatedUser.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/jest.config.js
  solutions/swb-reference/package.json
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/mocks/mockDatabaseService.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  solutions/swb-reference/src/services/databaseService.ts
  workbench-core/authorization/src/index.ts
  workbench-core/datasets/src/dataSetService.ts
Labels: size/l

#823 feat(key-pairs): delete key pairs API
  common/changes/@aws/swb-app/maghirardelli-ssh-delete_2023-02-06-16-33.json
  common/changes/@aws/workbench-core-base/maghirardelli-ssh-delete_2023-02-06-16-33.json
  solutions/swb-app/README.md
  solutions/swb-app/src/errors/databaseError.ts
  solutions/swb-app/src/errors/errors.test.ts
  solutions/swb-app/src/errors/noKeyExistsError.ts
  solutions/swb-app/src/errors/nonUniqueKeyError.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/keyPairRoutes.ts
  solutions/swb-app/src/keyPairs/deleteKeyPairRequest.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/resources/keyPairs/keyPairs.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/tests/isolated/keyPairs/delete.test.ts
  solutions/swb-reference/src/services/keyPairService.test.ts
  solutions/swb-reference/src/services/keyPairService.ts
Labels: size/l

#825 test: isUserLoggedIn integ tests
  solutions/example-ui-app/cache/config.json
  workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
Labels: size/s

#824 test: add integration tests for audit service
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/example/app/src/configs/dynamicRouteConfig.ts
  workbench-core/example/app/src/generateRouter.ts
  workbench-core/example/app/src/routes/auditRoutes.ts
  workbench-core/example/app/src/routes/sampleRoutes.ts
  workbench-core/example/app/src/services/auditService.ts
  workbench-core/example/app/src/utilities/authWrapper.ts
  workbench-core/example/infrastructure/integration-tests/support/resources.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/audit/auditEntry.ts
  workbench-core/example/infrastructure/integration-tests/tests/audit/auditEntry.test.ts
  workbench-core/example/infrastructure/package.json
Labels: size/m

#826 feat(key-pairs): GET API
  common/changes/@aws/swb-app/maghirardelli-ssh-get_2023-02-07-18-53.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/keyPairRoutes.ts
  solutions/swb-app/src/keyPairs/getKeyPairRequest.ts
  solutions/swb-app/src/keyPairs/keyPairPlugin.ts
  solutions/swb-app/src/keyPairs/listKeyPairsRequest.test.ts
  solutions/swb-app/src/keyPairs/listKeyPairsRequest.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/keyPairs/keyPairs.ts
  solutions/swb-reference/integration-tests/tests/isolated/keyPairs/get.test.ts
  solutions/swb-reference/src/services/keyPairService.test.ts
  solutions/swb-reference/src/services/keyPairService.ts
Labels: size/m

#827 ci: update all workflows to use ubuntu-20.04
  .github/workflows/enable-feat-protection.yml
  .github/workflows/feat-deletion.yml
  .github/workflows/no-response.yml
  .github/workflows/pipeline-workflow.yml
Labels: size/xs

#828 ci: Fix workflow
  .github/workflows/merge-develop-to-stage.yml
Labels: size/xs

#829 test: added refreshAccessToken integration tests
  workbench-core/example/infrastructure/integration-tests/support/clientSession.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
Labels: size/s

#830 test: added integration tests for logoutUser
  workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
Labels: size/s

#831 test: added integration tests for getTokensFromAuthorizationCode
  workbench-core/example/infrastructure/integration-tests/support/resources/authentication/authentication.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
Labels: size/s

#834 fix(ssh-keys): set up prereqs for new SSH design with EC2
  common/changes/@aws/swb-app/maghirardelli-ssh-ec2-prereqs_2023-02-09-17-15.json
  common/changes/@aws/workbench-core-base/maghirardelli-ssh-ec2-prereqs_2023-02-09-17-15.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/errors/databaseError.ts
  solutions/swb-app/src/errors/noKeyExistsError.ts
  solutions/swb-app/src/errors/nonUniqueKeyError.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/keyPairRoutes.ts
  solutions/swb-app/src/keyPairs/getKeyPairRequest.ts
  solutions/swb-app/src/keyPairs/keyPairPlugin.ts
  solutions/swb-app/src/sshKeyRoutes.ts
  solutions/swb-app/src/sshKeys/createSshKeyRequest.ts
  solutions/swb-app/src/sshKeys/createSshKeyResponse.ts
  solutions/swb-app/src/sshKeys/deleteSshKeyRequest.ts
  solutions/swb-app/src/sshKeys/listUserSshKeysForProjectRequest.ts
  solutions/swb-app/src/sshKeys/listUserSshKeysForProjectResponse.ts
  solutions/swb-app/src/sshKeys/sendPublicKeyRequest.ts
  solutions/swb-app/src/sshKeys/sendPublicKeyResponse.ts
  solutions/swb-app/src/sshKeys/sshKey.ts
  solutions/swb-app/src/sshKeys/sshKeyPlugin.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/keyPairs/keyPairs.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/get.test.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/services/keyPairService.test.ts
  solutions/swb-reference/src/services/keyPairService.ts
  solutions/swb-reference/src/services/sshKeyService.test.ts
  solutions/swb-reference/src/services/sshKeyService.ts
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
  workbench-core/base/package.json
  workbench-core/base/src/aws/awsService.ts
Labels: size/xl

#832 feat: remote dynamic route
  common/changes/@aws/swb-app/janeyu-remove_dynamic_route_2023-02-09-17-55.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/src/backendAPI.ts
Labels: size/s

#836 feat: Add ProjectEnvService/Plugin/Routes and refactor existing Environment Routes
  common/changes/@aws/swb-app/kevpark-pb-environment-changes_2023-02-09-17-58.json
  common/changes/@aws/workbench-core-environments-ui/kevpark-pb-environment-changes_2023-02-09-17-58.json
  common/changes/@aws/workbench-core-environments/kevpark-pb-environment-changes_2023-02-09-17-58.json
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/environmentRoutes.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-app/src/projectEnvs/projectEnvPlugin.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environments.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/connections.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/stop.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/services/projectEnvService.test.ts
  solutions/swb-reference/src/services/projectEnvService.ts
  workbench-core/environments-ui/src/api/environments.ts
  workbench-core/environments-ui/src/pages/environments/index.tsx
  workbench-core/environments/README.md
  workbench-core/environments/src/schemas/createEnvironment.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
Labels: size/xl

#837 fix: updating project used for integ tests
  solutions/swb-reference/integration-tests/config/testEnv.yaml
Labels: size/xs

#833 test: add static authorization service integration tests
  common/changes/@aws/workbench-core-authorization/topic-staticAuthzIntegTests_2023-02-09-12-06.json
  common/changes/@aws/workbench-core-authorization/topic-staticAuthzIntegTests_2023-02-09-22-30.json
  solutions/example-ui-app/cache/config.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/authorizationService.ts
  workbench-core/authorization/src/caslAuthorizationPlugin.test.ts
  workbench-core/authorization/src/caslAuthorizationPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/models/identityPermission.ts
  workbench-core/example/app/src/configs/dynamicRouteConfig.ts
  workbench-core/example/app/src/configs/sampleStaticRouteConfig.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/generateRouter.ts
  workbench-core/example/app/src/models/authorization/isAuthorizedOnRoute.ts
  workbench-core/example/app/src/models/authorization/isRouteIgnored.ts
  workbench-core/example/app/src/routes/staticAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/authorization/staticAuthorization.ts
  workbench-core/example/infrastructure/integration-tests/tests/authorization/routeProtection.test.ts
Labels: size/l

#839 feat: disassociate data set from project
  common/changes/@aws/swb-app/atmikev-GALI-2153_DisassociateDataSetFromProject_2023-02-10-20-01.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-2153_DisassociateDataSetFromProject_2023-02-10-20-01.json
  solutions/swb-app/README.md
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/projectAddAccessRequestParser.ts
  solutions/swb-app/src/dataSets/projectRemoveAccessRequestParser.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/mocks/mockDatabaseService.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  solutions/swb-reference/src/services/databaseService.ts
  workbench-core/base/README.md
  workbench-core/base/src/cognitoTokenService.ts
Labels: size/l

#841 chore: revert disassociate data set from project
  common/changes/@aws/swb-app/revert-839-atmikev-GALI-2153_DisassociateDataSetFromProject_2023-02-11-02-52.json
  common/changes/@aws/workbench-core-base/revert-839-atmikev-GALI-2153_DisassociateDataSetFromProject_2023-02-11-02-52.json
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/README.md
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/projectAccessRequestParser.ts
  solutions/swb-app/src/dataSets/projectRemoveAccessRequestParser.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/mocks/mockDatabaseService.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  solutions/swb-reference/src/services/databaseService.ts
  workbench-core/base/README.md
  workbench-core/base/src/cognitoTokenService.ts
Labels: size/l

#842 feat: disassociate data set from project
  common/changes/@aws/swb-app/atmikev-GALI-2153_DisassociateDataSetFromProject_2023-02-10-20-01.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-2153_DisassociateDataSetFromProject_2023-02-10-20-01.json
  solutions/swb-app/README.md
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/projectAddAccessRequestParser.ts
  solutions/swb-app/src/dataSets/projectRemoveAccessRequestParser.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/mocks/mockDatabaseService.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  solutions/swb-reference/src/services/databaseService.ts
  workbench-core/base/README.md
  workbench-core/base/src/cognitoTokenService.ts
Labels: size/l

#843 feat(ssh-keys): delete ssh keys API
  common/changes/@aws/swb-app/maghirardelli-ssh-ec2-delete_2023-02-13-15-45.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-ssh-ec2-delete_2023-02-13-15-45.json
  common/changes/@aws/workbench-core-base/maghirardelli-ssh-ec2-delete_2023-02-13-15-45.json
  solutions/swb-app/src/errors/awsServiceError.ts
  solutions/swb-app/src/errors/ec2Error.ts
  solutions/swb-app/src/errors/errors.test.ts
  solutions/swb-app/src/errors/noKeyExistsError.ts
  solutions/swb-app/src/errors/nonUniqueKeyError.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/sshKeyRoutes.ts
  solutions/swb-app/src/sshKeys/deleteSshKeyRequest.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/support/resources/sshKeys/sshKey.ts
  solutions/swb-reference/integration-tests/support/resources/sshKeys/sshKeys.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/services/sshKeyService.test.ts
  solutions/swb-reference/src/services/sshKeyService.ts
  workbench-core/accounts/src/index.ts
  workbench-core/base/src/constants/resourceTypeToKey.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/textUtil.ts
Labels: size/l

#840 chore: merge Solutions pipeline files
  CHANGELOG.md
  buildspec.yml
  common/changes/@aws/swb-app/chore-merge-develop-pipeline_2023-02-13-19-50.json
  common/changes/@aws/workbench-core-base/chore-merge-develop-pipeline_2023-02-13-19-50.json
  deployment/build-open-source-dist.sh
  deployment/build-s3-dist.sh
  deployment/cdk-solution-helper/README.md
  deployment/cdk-solution-helper/index.js
  deployment/cdk-solution-helper/package-lock.json
  deployment/cdk-solution-helper/package.json
  deployment/run-unit-tests.sh
  deployment/solution_config
  deployment/testEnv.json
  solutions/swb-app/README.md
  solutions/swb-reference/README.md
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.test.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
  solutions/swb-reference/src/infra/SWBVpc.ts
  sonar-project.properties
  workbench-core/base/README.md
Labels: size/xl

#846 chore: fix ETC integ test
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
Labels: size/s

#850 chore: fix appRegistry Construct
  .viperlightignore
  common/changes/@aws/workbench-core-infrastructure/app-registry-fix_2023-02-15-22-06.json
  workbench-core/example/infrastructure/src/config/appReg.env
  workbench-core/example/infrastructure/src/index.ts
  workbench-core/infrastructure/README.md
  workbench-core/infrastructure/docs/workbenchAppRegistry.md
  workbench-core/infrastructure/docs/workbenchAssociateStackToExistingAppRegistryApplication.md
  workbench-core/infrastructure/src/workbenchAppRegistry.test.ts
  workbench-core/infrastructure/src/workbenchAppRegistry.ts
  workbench-core/infrastructure/src/workbenchAssociateStackToExistingAppRegistryApplication.test.ts
  workbench-core/infrastructure/src/workbenchAssociateStackToExistingAppRegistryApplication.ts
Labels: size/m

#849 fix: rewrite ITAdmin permissions
  solutions/swb-reference/README.md
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/src/postDeployment.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.test.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/postDeployment/authorizationSetup.test.ts
Labels: size/m

#852 fix: updateEnvironment params order was backwards
  common/changes/@aws/swb-app/kevpark-update-env-params-fix_2023-02-16-16-52.json
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-app/src/projectEnvs/projectEnvPlugin.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environments.ts
Labels: size/s

#848 feat: listUserSshKeysForProject
  common/changes/@aws/swb-app/janeyu-ssh-ec1-list_2023-02-14-21-40.json
  common/changes/@aws/swb-app/janeyu-ssh-ec1-list_2023-02-15-23-01.json
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/sshKeyRoutes.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/get.test.ts
  solutions/swb-reference/src/services/sshKeyService.test.ts
  solutions/swb-reference/src/services/sshKeyService.ts
Labels: size/m

#854 fix(ssh-keys): fix ssh keys route mapping to not have duplicate
  common/changes/@aws/swb-app/maghirardelli-fix-ssh-key-route-mapping_2023-02-16-21-03.json
  solutions/swb-app/src/staticRouteConfig.ts
Labels: size/s

#853 ci: fix cfn_nag
  .github/workflows/cfn-nag.yml
  solutions/swb-reference/package.json
  workbench-core/example/infrastructure/package.json
Labels: size/s

#860 feat: implement dynamic authz middleware
  common/changes/@aws/workbench-core-authorization/topic-implementDynamicAuthzMiddleware_2023-02-17-05-52.json
  solutions/example-ui-app/cache/config.json
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/models/getDynamicOperationsByRoute.ts
  workbench-core/authorization/src/index.ts
  workbench-core/example/app/src/configs/dynamicRouteConfig.ts
  workbench-core/example/app/src/configs/dynamicRoutesIgnored.ts
  workbench-core/example/app/src/generateRouter.ts
  workbench-core/example/app/src/routes/auditRoutes.ts
  workbench-core/example/app/src/routes/sampleRoutes.ts
  workbench-core/example/app/src/routes/staticAuthorizationRoutes.ts
Labels: size/m

#851 feat(app registry): create app registry application for swb
  deployment/solution_config
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/index.ts
Labels: size/s

#856 refactor: removing error codes from payloads
  .prettierignore
  .viperlightignore
  common/changes/@aws/swb-app/kevpark-remove-status-codes_2023-02-16-23-18.json
  solutions/swb-app/src/errorHandlers.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/connections.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/stop.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/assignUserToProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/activateDeactivateUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userApi.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
Labels: size/m

#863 fix: env integ tests wait for environment to stop and terminate durin…
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
Labels: size/s

#861 feat: Remove dataset endpoints
  common/changes/@aws/swb-app/atmikev-GALI-2121_ExtraEndpoints_2023-02-17-16-19.json
  common/changes/@aws/workbench-core-authorization/atmikev-GALI-2121_ExtraEndpoints_2023-02-17-16-19.json
  common/changes/@aws/workbench-core-datasets/atmikev-GALI-2121_ExtraEndpoints_2023-02-17-16-19.json
  solutions/swb-app/README.md
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/removeDataSetRequestParser.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/authorization/src/staticPermissionsPlugin.test.ts
  workbench-core/authorization/src/staticPermissionsPlugin.ts
  workbench-core/datasets/src/dataSetService.ts
Labels: size/l

#858 fix(swb-reference): fix signed URL fails to download cfn template
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/postDeployment.ts
Labels: size/s

#864 chore: remove statusCode from delete dataset tests
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
Labels: size/xs

#859 test(ssh-api): Add helper methods to get non IT Admin Sessions for Integ Test
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/swbv2-private.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
Labels: size/m

#865 chore: fix dataset name randomization for tests
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
Labels: size/xs

#870 chore: rush node version update
  rush.json
Labels: size/xs

#866 fix(accounts): return URLs for vanilla, byon and tgw onboarding templates instead of just vanilla
  common/changes/@aws/workbench-core-accounts/topic-byon-account-url_2023-02-18-00-34.json
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  workbench-core/accounts/README.md
  workbench-core/accounts/src/services/hostingAccountService.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
Labels: size/s

#871 feat: add 'ALLOW_USER_PASSWORD_AUTH' cognito
  common/changes/@aws/workbench-core-infrastructure/janeyu-cognito-access_2023-02-20-20-35.json
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/s

#855 feat: Remove deprecated 'Admin' role/group
  common/changes/@aws/swb-app/topic-adminToITAdmin_2023-02-16-21-54.json
  common/changes/@aws/workbench-core-authentication/topic-adminToITAdmin_2023-02-16-21-54.json
  common/changes/@aws/workbench-core-authorization/topic-adminToITAdmin_2023-02-16-21-54.json
  common/changes/@aws/workbench-core-base/topic-adminToITAdmin_2023-02-16-21-54.json
  common/changes/@aws/workbench-core-environments/topic-adminToITAdmin_2023-02-16-21-54.json
  common/changes/@aws/workbench-core-swb-common-ui/topic-adminToITAdmin_2023-02-16-21-54.json
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userApi.test.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/environments/src/postDeployment/cognitoSetup.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/swb-common-ui/src/components/Navigation.tsx
  workbench-core/swb-common-ui/src/models/User.ts
Labels: size/m

#857 feat: get dataset file upload URL api
  common/changes/@aws/swb-app/topic-dataset-upload-file-api_2023-02-17-23-21.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/DataSetFileUploadRequestParser.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/integration-tests/support/complex/datasetHelper.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/m

#874 fix(integ tests): add afterEach step to cleanup environments
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
Labels: size/xs

#862 feat(ssk-keys): Send SSH Public Key
  common/changes/@aws/swb-app/maghirardelli-ssh-send-ssh-public-key_2023-02-17-17-42.json
  solutions/swb-app/src/errors/connectionInfoNotDefinedError.ts
  solutions/swb-app/src/errors/errors.test.ts
  solutions/swb-app/src/errors/noInstanceFoundError.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/sshKeyRoutes.ts
  solutions/swb-app/src/sshKeys/sendPublicKeyRequest.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/services/sshKeyService.test.ts
  solutions/swb-reference/src/services/sshKeyService.ts
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
Labels: size/l

#873 feat: list data set access permissions
  common/changes/@aws/swb-app/atmikev-GALI-2279_ListDataSetAccessPermissions_2023-02-20-22-54.json
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-2279_ListDataSetAccessPermissions_2023-02-20-23-01.json
  common/changes/@aws/workbench-core-datasets/atmikev-GALI-2279_ListDataSetAccessPermissions_2023-02-20-22-54.json
  solutions/swb-app/README.md
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/listDataSetAccessPermissionsRequestParser.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/accounts/README.md
  workbench-core/datasets/src/dataSetService.ts
Labels: size/m

#872 fix: authN middleware fix
  common/changes/@aws/workbench-core-authentication/fix-aunth-n-middleware-fix_2023-02-20-22-15.json
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.ts
Labels: size/s

#879 fix: datasets integ test fix
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
Labels: size/xs

#882 ci: fix JavaScript heap out of memory
  .github/workflows/deploy-integration-swb-reference.yml
Labels: size/xs

#885 test: datasets integ test fix
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
Labels: size/xs

#881 feat: Add AVAILABLE/DELETED status to environmentTypeConfig
  common/changes/@aws/swb-app/topic-addAvailableDeletedStatusToEtc_2023-02-21-22-07.json
  common/changes/@aws/workbench-core-environments/topic-addAvailableDeletedStatusToEtc_2023-02-21-22-07.json
  solutions/swb-app/src/envTypeConfigs/environmentTypeConfig.ts
  workbench-core/environments/src/constants/environmentTypeConfigStatus.ts
  workbench-core/environments/src/models/environmentTypeConfigs/environmentTypeConfig.ts
  workbench-core/environments/src/services/environmentTypeConfigService.test.ts
  workbench-core/environments/src/services/environmentTypeConfigService.ts
  workbench-core/environments/src/services/environmentTypeService.test.ts
Labels: size/s

#884 feat: Add pagination for list data sets
  common/changes/@aws/swb-app/atmikev-GALI-2287_PaginationForListDataSets_2023-02-21-23-02.json
  common/changes/@aws/workbench-core-datasets/atmikev-GALI-2287_PaginationForListDataSets_2023-02-21-23-02.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetMetadataPlugin.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/list.test.ts
Labels: size/m

#877 feat(App Registry): Add hosting account resources to App registry application
  common/changes/@aws/workbench-core-base/farandac-app-registry-hosting_2023-02-21-18-26.json
  common/changes/@aws/workbench-core-environments/farandac-app-registry-hosting_2023-02-21-18-26.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/README.md
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.test.ts
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
  workbench-core/base/README.md
  workbench-core/base/package.json
  workbench-core/base/src/aws/awsService.ts
  workbench-core/base/src/aws/helpers/appRegistryService.test.ts
  workbench-core/base/src/aws/helpers/appRegistryService.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/handlers/statusHandler.ts
Labels: size/l

#887 fix(integ tests): Update paab helper to develop
  solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
Labels: size/s

#888 chore: add BYON GH workflow
  .github/workflows/merge-develop-to-stage.yml
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
  solutions/swb-reference/src/SWBStack.ts
Labels: size/s

#889 fix: remove dependency on BYON workflow
  .github/workflows/merge-develop-to-stage.yml
Labels: size/xs

#878 test(accounts): add a test to verify structure of awsAccountTemplateU…
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/awsAccountTemplateUrls.test.ts
Labels: size/s

#891 fix: remove BYON workflow step
  .github/workflows/merge-develop-to-stage.yml
Labels: size/s

#868 feat: enable authz middleware
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.test.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.ts
Labels: size/l

#893 chore(api delete requests): standardize soft-delete and hard-delete Routes
  common/changes/@aws/swb-app/farandac-standardize-delete-requests_2023-02-23-03-19.json
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/sshKeyRoutes.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/base/resource.ts
  solutions/swb-reference/integration-tests/support/resources/costCenters/costCenter.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/support/resources/users/user.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/costCenter.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/project.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userApi.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
Labels: size/m

#892 fix: test cdk synth for BYON GH workflow
  .github/workflows/merge-develop-to-stage.yml
  solutions/swb-reference/src/SWBStack.ts
Labels: size/s

#883 fix: update SM autostop command for AL2
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
Labels: size/xs

#895 fix: onboard account presigned url fix
  common/changes/@aws/workbench-core-accounts/fix-onboard-account-url-fix_2023-02-23-21-50.json
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
Labels: size/s

#896 fix: Update delete permissions
  solutions/swb-reference/src/dynamicRouteConfig.ts
Labels: size/s

#897 feat: implement limit on number identity permissions retrieved
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/topic-pagingForDynamicAuthz_2023-02-23-22-46.json
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/models/getIdentityPermissionsByIdentity.ts
  workbench-core/authorization/src/dynamicAuthorization/models/getIdentityPermissionsBySubject.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
  workbench-core/example/infrastructure/src/index.ts
Labels: size/m

#894 fix(ssh-keys): integrate with project as a boundary and integ test boundary
  common/changes/@aws/swb-app/ssh-integ_2023-02-24-00-34.json
  common/changes/@aws/workbench-core-environments/ssh-integ_2023-02-23-21-31.json
  solutions/swb-app/README.md
  solutions/swb-app/src/errors/databaseError.ts
  solutions/swb-app/src/errors/errors.test.ts
  solutions/swb-app/src/index.ts
  solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/sshKeys.test.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/services/swbProjectService.test.ts
  solutions/swb-reference/src/services/swbProjectService.ts
Labels: size/l

#900 chore: update Project-users routes
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/projects/listUsersForRoleRequest.ts
Labels: size/s

#898 fix: list env type config should be using req.query
  common/changes/@aws/swb-app/fix-listEnvTypeConfig_2023-02-23-23-45.json
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
Labels: size/s

#903 fix(ssh-integ-test): move expect to beforeEach
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/sshKeys.test.ts
Labels: size/s

#899 fix: replace harcoded AZs for firewall
  solutions/swb-reference/src/templates/new-firewall-vpc.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
Labels: size/s

#886 feat: verify that the Project was not deleted before creating new env…
  common/changes/@aws/swb-app/topic-verifyProjectWasNotDeleted_2023-02-22-17-51.json
  solutions/swb-app/README.md
  solutions/swb-app/src/errors/errors.test.ts
  solutions/swb-app/src/errors/projectDeletedError.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/src/services/projectEnvService.test.ts
  solutions/swb-reference/src/services/projectEnvService.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.test.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.ts
Labels: size/m

#905 chore: merge develop to paab
  common/changes/@aws/swb-app/fix-listEnvTypeConfig_2023-02-23-23-45.json
  common/changes/@aws/workbench-core-environments/maghirardelli-project-test-cleanup_2023-02-24-14-52.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/costCenter.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/project.test.ts
  solutions/swb-reference/package.json
  workbench-core/environments/README.md
Labels: size/m

#890 fix: post deployment setup
  common/changes/@aws/workbench-core-environments/fix-postDeploymentSetup_2023-02-22-22-33.json
  workbench-core/environments/src/postDeployment/cognitoSetup.test.ts
  workbench-core/environments/src/postDeployment/cognitoSetup.ts
Labels: size/m

#906 refactor: Update existing integ tests except datasets to work with Project as a Boundary
  .viperlightignore
  solutions/swb-app/src/errorHandlers.ts
  solutions/swb-app/src/projects/projectPlugin.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environments.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/HttpError.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/support/utils/utilities.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/connections.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/stop.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/activateDeactivateUser.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/services/swbProjectService.test.ts
  solutions/swb-reference/src/services/swbProjectService.ts
  workbench-core/datasets/src/schemas/createDataSet.ts
  workbench-core/environments/README.md
Labels: size/xl

#908 chore: Project as a Boundary dataset integration tests
  common/changes/@aws/swb-app/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
  common/changes/@aws/workbench-core-accounts/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
  common/changes/@aws/workbench-core-datasets/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
  common/changes/@aws/workbench-core-environments/atmikev-paab-dataset-integration-tests_2023-02-25-00-36.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/dataset.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/m

#910 feat: project as a Boundary integ test and GetDataset route
  common/changes/@aws/swb-app/kevpark-paab-happy-path_2023-02-25-05-01.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-reference/integration-tests/support/models/environmentTypeConfigs.ts
  solutions/swb-reference/integration-tests/support/models/projects.ts
  solutions/swb-reference/integration-tests/support/resources/environmentTypeConfigs/environmentTypeConfig.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/support/utils/constants.ts
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.ts
  solutions/swb-reference/src/services/swbProjectService.ts
Labels: size/l

#909 feat: add list project datasets API
  common/changes/@aws/swb-app/bhudnell-list-project-datasets_2023-02-25-06-02.json
  common/changes/@aws/workbench-core-datasets/bhudnell-list-project-datasets_2023-02-25-06-02.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/createDataSetRequestParser.ts
  solutions/swb-app/src/dataSets/dataSet.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/tests/isolated/projects/listDataSetsForProject.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/datasets/src/dataSetService.ts
Labels: size/m

#913 fix: revert change to CreateDataSet schema object
  common/changes/@aws/workbench-core-datasets/fix-revert-create-dataset-schema-change_2023-02-27-18-32.json
  workbench-core/datasets/src/schemas/createDataSet.ts
Labels: size/s

#914 fix: update Setup to not be a singleton in order to avoid expired cre…
  solutions/swb-reference/integration-tests/support/setup.ts
Labels: size/xs

#912 feat: enabled pageSize for getAllDataSetAccessPermissions
  common/changes/@aws/workbench-core-datasets/topic-limitOnGetAllDataSetAccessPermissions_2023-02-27-13-04.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsAuthorizationPlugin.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
Labels: size/m

#915 fix: update Setup to refresh AWS credentials every time sessions are …
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/package.json
Labels: size/s

#916 chore: update account id used for byon integ tests
  solutions/swb-reference/integration-tests/config/swbv2-private.yaml
Labels: size/xs
