Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2023-05, with the labels that each got.

#1042 chore: update solution config
  deployment/solution_config
Labels: size/xs

#1041 chore: ETC zod updates
  common/changes/@aws/swb-app/chore-zod-updates_2023-05-01-20-05.json
  common/changes/@aws/workbench-core-base/chore-zod-updates_2023-05-01-20-05.json
  common/changes/@aws/workbench-core-environments/chore-zod-updates_2023-05-01-20-05.json
  solutions/swb-app/src/envTypeConfigs/createEnvironmentTypeConfigRequest.ts
  solutions/swb-app/src/envTypeConfigs/deleteEnvironmentTypeConfigRequest.ts
  solutions/swb-app/src/envTypeConfigs/environmentTypeConfig.ts
  solutions/swb-app/src/envTypeConfigs/getEnvironmentTypeConfigRequest.ts
  solutions/swb-app/src/envTypeConfigs/listEnvironmentTypeConfigsRequest.ts
  solutions/swb-app/src/envTypeConfigs/updateEnvironmentTypeConfigsRequest.ts
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
  workbench-core/environments/src/models/environmentTypeConfigs/createEnvironmentTypeConfigRequest.ts
  workbench-core/environments/src/models/environmentTypeConfigs/deleteEnvironmentTypeConfigRequest.ts
  workbench-core/environments/src/models/environmentTypeConfigs/environmentTypeConfig.ts
  workbench-core/environments/src/models/environmentTypeConfigs/listEnvironmentTypeConfigsRequest.ts
  workbench-core/environments/src/models/environmentTypeConfigs/updateEnvironmentTypeConfigsRequest.ts
  workbench-core/environments/src/services/environmentTypeConfigService.test.ts
Labels: size/m

#1043 chore(zod): add zod validation to account and cost center
  common/changes/@aws/swb-app/janeyu-ZodCostCenter_2023-05-04-01-03.json
  common/changes/@aws/workbench-core-accounts/janeyu-ZodCostCenter_2023-05-02-22-33.json
  common/changes/@aws/workbench-core-base/janeyu-ZodCostCenter_2023-05-02-22-33.json
  common/changes/@aws/workbench-core-environments/janeyu-ZodCostCenter_2023-05-04-01-03.json
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/envTypeConfigs/createEnvironmentTypeConfigRequest.ts
  solutions/swb-app/src/envTypeConfigs/environmentTypeConfig.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
  workbench-core/accounts/src/models/accounts/account.ts
  workbench-core/accounts/src/models/accounts/awsAccountTemplateUrlsRequest.ts
  workbench-core/accounts/src/models/accounts/createAccountRequest.ts
  workbench-core/accounts/src/models/accounts/getAccountRequest.ts
  workbench-core/accounts/src/models/accounts/updateAccountRequest.ts
  workbench-core/accounts/src/models/costCenters/costCenter.ts
  workbench-core/accounts/src/models/costCenters/createCostCenterRequest.ts
  workbench-core/accounts/src/models/costCenters/deleteCostCenterRequest.ts
  workbench-core/accounts/src/models/costCenters/updateCostCenterRequest.ts
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
  workbench-core/environments/src/models/environmentTypeConfigs/createEnvironmentTypeConfigRequest.ts
  workbench-core/environments/src/models/environmentTypeConfigs/environmentTypeConfig.ts
  workbench-core/environments/src/models/environmentTypes/updateEnvironmentTypeRequest.ts
Labels: size/m

#1045 chore: zod update projectenv
  common/changes/@aws/swb-app/chore-zod-update-projectenv_2023-05-04-15-18.json
  common/changes/@aws/workbench-core-base/chore-zod-update-projectenv_2023-05-04-15-18.json
  common/changes/@aws/workbench-core-environments/chore-zod-update-projectenv_2023-05-04-15-18.json
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/envTypeConfigs/createEnvironmentTypeConfigRequest.ts
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-app/src/projectEnvs/connectEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/createEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/getEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/listProjectEnvironmentsRequest.ts
  solutions/swb-app/src/projectEnvs/startEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/stopEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/terminateEnvironmentRequest.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.ts
  workbench-core/environments/src/models/environmentTypeConfigs/createEnvironmentTypeConfigRequest.ts
Labels: size/m

#1048 fix(swb-ref): make SageMaker IAM policy case insensitive
  solutions/swb-reference/src/SWBStack.ts
Labels: size/xs

#1044 chore(user-agent): add user agent
  common/changes/@aws/workbench-core-base/janeyu-metrics_2023-05-03-16-41.json
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/accountHandlerLambda.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/index.ts
  solutions/swb-reference/src/postDeployment.ts
  workbench-core/base/src/aws/awsService.ts
Labels: size/s

#1046 chore(zod): add zod regex to project routes && update generic zod
  common/changes/@aws/swb-app/janeyu-ZodProj_2023-05-05-01-53.json
  common/changes/@aws/workbench-core-accounts/janeyu-ZodProj_2023-05-04-17-20.json
  common/changes/@aws/workbench-core-accounts/janeyu-ZodProj_2023-05-05-01-53.json
  common/changes/@aws/workbench-core-base/janeyu-ZodProj_2023-05-04-17-20.json
  common/changes/@aws/workbench-core-base/janeyu-ZodProj_2023-05-05-01-53.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/projectEnvTypeConfigs/associateProjectEnvTypeConfigRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/disassociateProjectEnvTypeConfigRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/getProjectEnvTypeConfigRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listEnvTypeConfigProjectsRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listProjectEnvTypeConfigsRequest.ts
  solutions/swb-reference/integration-tests/support/utils/utilities.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/project.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
  workbench-core/accounts/src/models/accounts/account.ts
  workbench-core/accounts/src/models/accounts/getAccountRequest.ts
  workbench-core/accounts/src/models/accounts/updateAccountRequest.ts
  workbench-core/accounts/src/models/costCenters/costCenter.ts
  workbench-core/accounts/src/models/costCenters/createCostCenterRequest.ts
  workbench-core/accounts/src/models/costCenters/deleteCostCenterRequest.ts
  workbench-core/accounts/src/models/costCenters/updateCostCenterRequest.ts
  workbench-core/accounts/src/models/projects/assignUserToProjectRequest.ts
  workbench-core/accounts/src/models/projects/createProjectRequest.ts
  workbench-core/accounts/src/models/projects/deleteProjectRequest.ts
  workbench-core/accounts/src/models/projects/getProjectRequest.ts
  workbench-core/accounts/src/models/projects/getProjectsRequest.ts
  workbench-core/accounts/src/models/projects/listUsersForRoleRequest.ts
  workbench-core/accounts/src/models/projects/project.ts
  workbench-core/accounts/src/models/projects/updateProjectRequest.test.ts
  workbench-core/accounts/src/models/projects/updateProjectRequest.ts
  workbench-core/accounts/src/services/projectService.test.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/l

#1049 fix(swb-ref): remove Access for Project in DataSetService properly ha…
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/s

#1051 chore(docs update): minor updates for readme and postman collection
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
Labels: size/xs

#1053 fix(swb-ref): update integ tests impacted by zod
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
Labels: size/s

#1047 test: integ tests for temp project access
  solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
Labels: size/s

#1052 ci: codeowners update
  .github/CODEOWNERS
Labels: size/xs

#1050 chore: user routes zod validations
  .viperlightignore
  common/changes/@aws/swb-app/chore-zod-updates-user_2023-05-08-14-34.json
  common/changes/@aws/swb-app/chore-zod-updates-user_2023-05-08-14-49.json
  common/changes/@aws/workbench-core-accounts/chore-zod-updates-user_2023-05-08-14-49.json
  common/changes/@aws/workbench-core-base/chore-zod-updates-user_2023-05-08-14-34.json
  common/changes/@aws/workbench-core-base/chore-zod-updates-user_2023-05-08-14-49.json
  common/changes/@aws/workbench-core-environments/chore-zod-updates-user_2023-05-08-14-49.json
  solutions/example-ui-app/src/models/User.ts
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/envTypeConfigs/createEnvironmentTypeConfigRequest.ts
  solutions/swb-app/src/projectEnvs/connectEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/createEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/getEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/listProjectEnvironmentsRequest.ts
  solutions/swb-app/src/projectEnvs/startEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/stopEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/terminateEnvironmentRequest.ts
  solutions/swb-app/src/users/authenticatedUser.ts
  solutions/swb-app/src/users/createUserRequest.ts
  solutions/swb-app/src/users/deleteUserRequest.ts
  solutions/swb-app/src/users/getUserRequest.ts
  solutions/swb-app/src/users/updateUserRequest.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
  solutions/swb-reference/scripts/setupIntegTestEnv.sh
  solutions/swb-reference/scripts/solutions-implementation/baseResourceSetup.sh
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/environments/src/models/environmentTypeConfigs/createEnvironmentTypeConfigRequest.ts
Labels: size/m

#1054 chore(zod): update ssh key zod
  common/changes/@aws/swb-app/maghirardelli-ssh-key-zod-updates_2023-05-11-17-20.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-ssh-key-zod-updates_2023-05-11-17-20.json
  common/changes/@aws/workbench-core-authorization/maghirardelli-ssh-key-zod-updates_2023-05-11-17-20.json
  common/changes/@aws/workbench-core-base/maghirardelli-ssh-key-zod-updates_2023-05-11-17-20.json
  common/changes/@aws/workbench-core-environments/maghirardelli-ssh-key-zod-updates_2023-05-11-17-20.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/projects/disassociateUserFromProjectRequest.ts
  solutions/swb-app/src/sshKeys/createSshKeyRequest.ts
  solutions/swb-app/src/sshKeys/createSshKeyResponse.ts
  solutions/swb-app/src/sshKeys/deleteSshKeyRequest.ts
  solutions/swb-app/src/sshKeys/listUserSshKeysForProjectRequest.ts
  solutions/swb-app/src/sshKeys/listUserSshKeysForProjectResponse.ts
  solutions/swb-app/src/sshKeys/sendPublicKeyRequest.ts
  solutions/swb-app/src/sshKeys/sendPublicKeyResponse.ts
  solutions/swb-app/src/sshKeys/sshKey.ts
  solutions/swb-app/src/users/deleteUserRequest.ts
  solutions/swb-app/src/users/getUserRequest.ts
  solutions/swb-app/src/users/updateUserRequest.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/activateDeactivateUser.test.ts
  solutions/swb-reference/src/services/sshKeyService.test.ts
  workbench-core/accounts/src/models/projects/assignUserToProjectRequest.ts
  workbench-core/authorization/src/dynamicAuthorization/models/validateUserGroups.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
  workbench-core/example/app/src/models/datasets/createExternalEndpoint.ts
  workbench-core/example/app/src/models/dynamicAuthorization/addUserToGroup.ts
  workbench-core/example/app/src/models/dynamicAuthorization/removeUserFromGroup.ts
  workbench-core/example/app/src/models/user/activateUserRequest.ts
  workbench-core/example/app/src/models/user/addUserToRole.ts
  workbench-core/example/app/src/models/user/deactivateUserRequest.ts
  workbench-core/example/app/src/models/user/deleteUserRequest.ts
  workbench-core/example/app/src/models/user/getRolesRequest.ts
  workbench-core/example/app/src/models/user/getUserRequest.ts
Labels: size/m

#1058 fix: user integ tests
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
Labels: size/s

#1057 chore(zod): list empty name in filter status code 500 to 400
  common/changes/@aws/swb-app/janeyu-APIStatus_2023-05-11-18-33.json
  common/changes/@aws/workbench-core-accounts/janeyu-APIStatus_2023-05-11-18-33.json
  common/changes/@aws/workbench-core-base/janeyu-APIStatus_2023-05-11-18-33.json
  solutions/swb-app/src/environments/listEnvironmentsRequest.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/list.test.ts
  workbench-core/accounts/src/models/costCenters/listCostCentersRequest.ts
  workbench-core/accounts/src/models/projects/listProjectsRequest.ts
  workbench-core/base/src/interfaces/queryStringParamFilter.ts
Labels: size/m

#1061 chore: update CodeBuild and rush to >=node18
  buildspec.yml
  common/changes/@aws/workbench-core-infrastructure/node-version-update_2023-05-12-21-28.json
  rush.json
  workbench-core/infrastructure/src/workbenchDynamodb.test.ts
Labels: size/s

#1062 chore(user-management): add cognito group limit 25
  common/changes/@aws/workbench-core-user-management/janeyu-cognitoLimit_2023-05-12-23-46.json
  workbench-core/user-management/src/errors/errors.test.ts
  workbench-core/user-management/src/errors/userRolesExceedLimitError.ts
  workbench-core/user-management/src/index.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
Labels: size/s

#1060 chore(zod): filter between val1<=val2
  common/changes/@aws/workbench-core-base/janeyu-zodFilterBetween_2023-05-12-17-14.json
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/list.test.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/queryStringParamFilter.ts
  workbench-core/base/src/utilities/textUtil.ts
Labels: size/s

#1065 fix: remove deployment of example app from pipeline
  .github/workflows/integration-tests-release.yml
  .github/workflows/merge-develop-to-stage.yml
Labels: size/s

#1066 test: fix user integ tests with right error message
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
Labels: size/s

#1076 fix: unblock pipeline with longer ttl on temp creds and no account cleanup
  solutions/swb-reference/integration-tests/support/resources/accounts/account.ts
  solutions/swb-reference/src/backendAPI.ts
Labels: size/s

#1064 revert(chore user-management): add cognito group limit 25"
  common/changes/@aws/workbench-core-user-management/revert-1062-janeyu-cognitoLimit_2023-05-15-16-00.json
  workbench-core/user-management/src/errors/errors.test.ts
  workbench-core/user-management/src/errors/userRolesExceedLimitError.ts
  workbench-core/user-management/src/index.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
Labels: size/s

#1071 fix: remove log that might expose sensitive information
  common/changes/@aws/workbench-core-environments/yanyu-log-fix_2023-05-16-21-12.json
  solutions/swb-reference/src/environment/statusHandlerLambda.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/s

#1068 fix: env launch 500 error
  common/changes/@aws/swb-app/fix-env-ds-500_2023-05-15-21-56.json
  solutions/swb-app/src/projectEnvironmentRoutes.ts
Labels: size/s

#1059 feat: enhance validation for dataset routes
  common/changes/@aws/swb-app/yanyu-dataset-route-zod_2023-05-15-17-58.json
  common/changes/@aws/workbench-core-base/yanyu-dataset-route-zod_2023-05-15-17-58.json
  solutions/swb-app/src/dataSets/DataSetFileUploadRequestParser.ts
  solutions/swb-app/src/dataSets/addRemoveAccessPermissionRequest.ts
  solutions/swb-app/src/dataSets/createDataSetRequestParser.ts
  solutions/swb-app/src/dataSets/dataSetPermissionParser.ts
  solutions/swb-app/src/dataSets/listDataSetAccessPermissionsRequestParser.ts
  solutions/swb-app/src/dataSets/projectAddAccessRequestParser.ts
  solutions/swb-app/src/dataSets/projectRemoveAccessRequestParser.ts
  solutions/swb-app/src/dataSets/removeDataSetRequestParser.ts
  solutions/swb-app/src/users/authenticatedUser.ts
  solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
  solutions/swb-reference/integration-tests/support/resources/datasets/datasets.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/services/dataSetService.test.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/m

#1082 fix: fix integration test command
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/package.json
Labels: size/xs

#1079 revert(revert chore user-management): add cognito group limit 25
  common/changes/@aws/workbench-core-user-management/janeyu-cognitoLimit_2023-05-12-23-46.json
  workbench-core/user-management/src/errors/errors.test.ts
  workbench-core/user-management/src/errors/userRolesExceedLimitError.ts
  workbench-core/user-management/src/index.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
Labels: size/s

#1063 chore(boom): status code to 400
  common/changes/@aws/swb-app/janeyu-cognitoLimit_2023-05-13-03-48.json
  solutions/swb-app/src/projectRoutes.ts
Labels: size/s

#1070 chore: remove user roles field from update API
  common/changes/@aws/swb-app/chore-remove-user-roles_2023-05-16-18-47.json
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-app/src/users/updateUserRequest.ts
  solutions/swb-reference/SWBv2.openapi.json
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
Labels: size/s

#1077 fix(input validation): pagination token input validation
  common/changes/@aws/swb-app/maghirardelli-pag-token-validation_2023-05-18-15-17.json
  common/changes/@aws/workbench-core-base/maghirardelli-pag-token-validation_2023-05-18-15-17.json
  common/changes/@aws/workbench-core-environments/maghirardelli-pag-token-validation_2023-05-18-18-53.json
  solutions/swb-app/src/accountRoutes.ts
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/environmentRoutes.ts
  solutions/swb-app/src/environmentTypeConfigRoutes.ts
  solutions/swb-app/src/environmentTypeRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-reference/integration-tests/support/resources/environments/environments.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listDataSetsForProject.test.ts
  workbench-core/base/src/errors/errors.test.ts
  workbench-core/base/src/errors/invalidPaginationTokenError.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/paginationHelper.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentTypeConfigService.test.ts
  workbench-core/environments/src/services/environmentTypeService.test.ts
Labels: size/l

#1069 fix(environment): failed environment edge cases fixes
  common/changes/@aws/swb-app/thingut-start-env-fix_2023-05-17-15-24.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-reference/.depcheckrc
  solutions/swb-reference/integration-tests/support/complex/environmentHelper.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  solutions/swb-reference/package.json
Labels: size/m

#1080 chore(viperlight): replace with authorized creds
  .viperlightignore
  common/changes/@aws/workbench-core-environments/janeyu-viperignore_2023-05-18-19-33.json
  common/changes/@aws/workbench-core-infrastructure/janeyu-viperignore_2023-05-18-19-33.json
  solutions/swb-reference/scripts/setupIntegTestEnv.sh
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentConnectionService.test.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/infrastructure/src/workbenchAppRegistry.test.ts
Labels: size/s

#1081 fix(account-status): working account status update for byon
  common/changes/@aws/workbench-core-accounts/thingut-account-onboarding-status_2023-05-18-19-38.json
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
Labels: size/s

#1083 feat: Project / Dataset association check
  common/changes/@aws/swb-app/atmikev-CHAM-242_AssociateDataset_2023-05-19-21-39.json
  common/changes/@aws/workbench-core-base/atmikev-CHAM-242_AssociateDataset_2023-05-19-21-39.json
  common/changes/@aws/workbench-core-datasets/atmikev-CHAM-242_AssociateDataset_2023-05-19-21-39.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigs/projectEnvTypeConfigPlugin.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/mocks/mockDatabaseService.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  solutions/swb-reference/src/services/databaseService.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/base/src/services/metadataService.ts
Labels: size/m

#1084 feat: Revert "feat: Project / Dataset association check"
  common/changes/@aws/swb-app/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-21.json
  common/changes/@aws/swb-app/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/changes/@aws/workbench-core-accounts/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/changes/@aws/workbench-core-authorization/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/changes/@aws/workbench-core-base/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/changes/@aws/workbench-core-datasets/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/changes/@aws/workbench-core-environments/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/changes/@aws/workbench-core-infrastructure/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/changes/@aws/workbench-core-user-management/revert-1083-atmikev-CHAM-242_AssociateDataset_2023-05-22-20-24.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigs/projectEnvTypeConfigPlugin.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/mocks/mockDatabaseService.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  solutions/swb-reference/src/services/databaseService.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/base/src/services/metadataService.ts
Labels: size/m

#1085 chore: fix integration test
  solutions/swb-reference/integration-tests/config/release-candidate-private.yaml
  solutions/swb-reference/integration-tests/config/release-candidate.yaml
Labels: size/s

#1086 feat: RSW Associate Dataset
  common/changes/@aws/swb-app/atmikev-CHAM-242_AssociateDataset_2023-05-19-21-39.json
  common/changes/@aws/workbench-core-base/atmikev-CHAM-242_AssociateDataset_2023-05-19-21-39.json
  common/changes/@aws/workbench-core-datasets/atmikev-CHAM-242_AssociateDataset_2023-05-19-21-39.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigs/projectEnvTypeConfigPlugin.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/src/mocks/mockDatabaseService.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  solutions/swb-reference/src/services/databaseService.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/base/src/services/metadataService.ts
Labels: size/m

#1055 docs: minor updates to README for install
  solutions/swb-reference/README.md
Labels: size/s

#1072 feat: implement tokenRevocationService
  common/changes/@aws/swb-app/topic-tokenRevocationService_2023-05-17-01-12.json
  common/changes/@aws/workbench-core-authentication/topic-tokenRevocationService_2023-05-17-01-12.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/src/RSWStack.ts
  workbench-core/authentication/config/jest.config.json
  workbench-core/authentication/package.json
  workbench-core/authentication/src/__mocks__/authenticationService.ts
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationMiddleware.ts
  workbench-core/authentication/src/authenticationPlugin.ts
  workbench-core/authentication/src/authenticationService.test.ts
  workbench-core/authentication/src/authenticationService.ts
  workbench-core/authentication/src/errors/errors.test.ts
  workbench-core/authentication/src/errors/tokenRevocationServiceNotProvidedError.ts
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/plugins/__mocks__/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/tokenRevocationService.test.ts
  workbench-core/authentication/src/tokenRevocationService.ts
Labels: size/l

#1090 fix: Revert "feat: implement tokenRevocationService (#1072)"
  common/changes/@aws/swb-app/topic-revertTokenRevocationChanges_2023-05-23-20-41.json
  common/changes/@aws/workbench-core-authentication/topic-revertTokenRevocationChanges_2023-05-23-20-41.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/src/RSWStack.ts
  workbench-core/authentication/config/jest.config.json
  workbench-core/authentication/package.json
  workbench-core/authentication/src/__mocks__/authenticationService.ts
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationMiddleware.ts
  workbench-core/authentication/src/authenticationPlugin.ts
  workbench-core/authentication/src/authenticationService.test.ts
  workbench-core/authentication/src/authenticationService.ts
  workbench-core/authentication/src/errors/errors.test.ts
  workbench-core/authentication/src/errors/tokenRevocationServiceNotProvidedError.ts
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/plugins/__mocks__/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/tokenRevocationService.test.ts
  workbench-core/authentication/src/tokenRevocationService.ts
Labels: size/l

#1089 build(update): node version update 18
  buildspec.yml
Labels: size/xs

#1075 fix: map dataset error to 400s
  common/changes/@aws/swb-app/yanyu-dataset-500-fix_2023-05-17-19-55.json
  common/changes/@aws/workbench-core-datasets/yanyu-dataset-500-fix_2023-05-17-20-01.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/src/RSWStack.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/errors/accountNotFoundError.ts
  workbench-core/datasets/src/errors/errors.test.ts
  workbench-core/datasets/src/errors/storageNotFoundError.ts
  workbench-core/datasets/src/index.ts
Labels: size/m

#1088 chore: add limits for API GW and lambdas
  solutions/swb-reference/src/RSWStack.ts
Labels: size/xs

#1094 chore(rename): update solutionName in onboard hosting template
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
Labels: size/xs

#1091 feat: implement token revocation service
  common/changes/@aws/swb-app/topic-tokenRevocation_2023-05-24-09-43.json
  common/changes/@aws/workbench-core-authentication/topic-tokenRevocation_2023-05-24-09-43.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/src/RSWStack.ts
  workbench-core/authentication/config/jest.config.json
  workbench-core/authentication/package.json
  workbench-core/authentication/src/__mocks__/authenticationService.ts
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationMiddleware.ts
  workbench-core/authentication/src/authenticationPlugin.ts
  workbench-core/authentication/src/authenticationService.test.ts
  workbench-core/authentication/src/authenticationService.ts
  workbench-core/authentication/src/errors/errors.test.ts
  workbench-core/authentication/src/errors/tokenRevocationServiceNotProvidedError.ts
  workbench-core/authentication/src/index.ts
  workbench-core/authentication/src/plugins/__mocks__/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.ts
  workbench-core/authentication/src/tokenRevocationService.test.ts
  workbench-core/authentication/src/tokenRevocationService.ts
Labels: size/l

#1098 feat(user apis): add pagination to list users api
  .viperlightignore
  common/changes/@aws/swb-app/maghirardelli-pag-list-users_2023-05-26-06-53.json
  common/changes/@aws/workbench-core-accounts/maghirardelli-pag-list-users_2023-05-26-06-53.json
  common/changes/@aws/workbench-core-base/maghirardelli-pag-list-users_2023-05-26-06-53.json
  common/changes/@aws/workbench-core-user-management/maghirardelli-pag-list-users_2023-05-26-06-53.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-reference/RSW.openapi.json
  solutions/swb-reference/RSW.postman_collection.json
  solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/listUsers.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/user.test.ts
  workbench-core/accounts/src/services/projectService.ts
  workbench-core/example/app/src/routes/userRoutes.ts
  workbench-core/user-management/config/jest.config.json
  workbench-core/user-management/package.json
  workbench-core/user-management/src/index.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/user-management/src/user.ts
  workbench-core/user-management/src/userManagementPlugin.ts
  workbench-core/user-management/src/userManagementService.test.ts
  workbench-core/user-management/src/userManagementService.ts
  workbench-core/user-management/src/users/listUsersRequest.ts
  workbench-core/user-management/src/users/listUsersResponse.ts
Labels: size/l

#1100 test: proper test error
  common/changes/@aws/workbench-core-user-management/maghirardelli-fix-list-user-integ-test_2023-05-26-23-36.json
  solutions/swb-reference/integration-tests/tests/isolated/users/listUsers.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
Labels: size/s

#1099 test(account): redo account multistep integ test
  common/changes/@aws/workbench-core-accounts/maghirardelli-fix-account-test_2023-05-26-17-23.json
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/support/complex/accountHelper.ts
  solutions/swb-reference/integration-tests/support/resources/accounts/account.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
  solutions/swb-reference/scripts/setupIntegTestEnv.sh
  workbench-core/accounts/src/services/accountService.ts
Labels: size/m

#1101 chore(license): add 3rd party license
  .viperlightignore
  common/changes/@aws/swb-app/janeyu-license_2023-05-30-17-55.json
  solutions/swb-app/THIRD_PARTY_LICENSE.txt
  solutions/swb-reference/THIRD_PARTY_LICENSE.txt
Labels: size/xl
