Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2023-04, with the labels that each got.

#981 feat: listStorageLocations optimization
  common/changes/@aws/workbench-core-datasets/fix-list-storage-locations-optimization_2023-03-31-19-04.json
  common/changes/@aws/workbench-core-environments/fix-list-storage-locations-optimization_2023-03-31-19-04.json
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/constants.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/models/ddbMetadata.ts
  workbench-core/datasets/src/models/storageLocation.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
  workbench-core/example/app/src/configs/constants.ts
  workbench-core/example/app/src/services/datasetService.ts
  workbench-core/example/infrastructure/integration-tests/support/complex/datasetHelper.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/base/resource.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/fileUpload.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/list.test.ts
Labels: size/m

#984 chore: environment apis zod integration
  common/changes/@aws/swb-app/farandac-environmentAPIs-ZodIntegration_2023-04-03-16-26.json
  common/changes/@aws/workbench-core-environments/farandac-environmentAPIs-ZodIntegration_2023-04-03-16-26.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/example-ui-app/cache/config.json
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/environmentRoutes.ts
  solutions/swb-app/src/environments/environment.ts
  solutions/swb-app/src/environments/environmentItem.ts
  solutions/swb-app/src/environments/environmentPlugin.ts
  solutions/swb-app/src/environments/listEnvironmentsRequest.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-app/src/projectEnvs/connectEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/createEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/getEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/listProjectEnvironmentsRequest.ts
  solutions/swb-app/src/projectEnvs/projectEnvPlugin.ts
  solutions/swb-app/src/projectEnvs/startEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/stopEnvironmentRequest.ts
  solutions/swb-app/src/projectEnvs/terminateEnvironmentRequest.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/environment.test.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.test.ts
  solutions/swb-reference/src/services/projectEnvService.test.ts
  solutions/swb-reference/src/services/projectEnvService.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.ts
  solutions/swb-reference/src/services/sshKeyService.test.ts
  solutions/swb-reference/src/services/swbEnvironmentService.ts
  workbench-core/environments/config/jest.config.json
  workbench-core/environments/package.json
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/models/environments/environment.ts
  workbench-core/environments/src/models/environments/environmentItem.ts
  workbench-core/environments/src/models/environments/listEnvironmentsByProjectRequest.ts
  workbench-core/environments/src/models/environments/listEnvironmentsServiceRequest.ts
  workbench-core/environments/src/schemas/createEnvironment.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/xl

#985 test: replacing toMatchObject with toStrictEqual
  .viperlightignore
  common/changes/@aws/workbench-core-audit/topic-expectToStrictEqual_2023-04-04-14-47.json
  common/changes/@aws/workbench-core-authentication/topic-expectToStrictEqual_2023-04-04-14-47.json
  common/changes/@aws/workbench-core-authorization/topic-expectToStrictEqual_2023-04-04-14-47.json
  common/changes/@aws/workbench-core-base/topic-expectToStrictEqual_2023-04-04-14-47.json
  common/changes/@aws/workbench-core-datasets/topic-expectToStrictEqual_2023-04-04-14-47.json
  common/changes/@aws/workbench-core-environments/topic-expectToStrictEqual_2023-04-04-14-47.json
  common/changes/@aws/workbench-core-logging/topic-expectToStrictEqual_2023-04-04-14-47.json
  common/changes/@aws/workbench-core-user-management/topic-expectToStrictEqual_2023-04-04-14-47.json
  workbench-core/audit/src/plugins/baseAuditPlugin.test.ts
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationService.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/dynamoDBService.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/transactEdit.test.ts
  workbench-core/base/src/services/metadataService.test.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/audit/auditEntry.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/authorization/routeProtection.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/byob.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/delete.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/get.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/iamRoles.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/activateDeactivateUser.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/createUser.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/getUserRoles.test.ts
  workbench-core/logging/src/plugins/winstonPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
Labels: size/l

#907 chore: firewall and TGW template cleanup
  solutions/swb-reference/README_SOLUTIONS.md
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/templates/new-firewall-vpc.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
Labels: size/m

#944 feat: cypress integration test
  .github/workflows/deploy-integration-example-app.yml
  .gitignore
  common/changes/@aws/workbench-core-infrastructure/topic-cypressPrototype_2023-03-30-15-35.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/example/infrastructure/README.md
  workbench-core/example/infrastructure/cypress.config.ts
  workbench-core/example/infrastructure/cypress/e2e/routeHandler.cy.ts
  workbench-core/example/infrastructure/cypress/support/e2e.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
  workbench-core/example/infrastructure/package.json
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/m

#989 chore: validate environment belongs to project on APIs
  common/changes/@aws/swb-app/farandac-validate-env-project_2023-04-06-15-57.json
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
Labels: size/s

#991 chore(gh actions): remove unnecessary workflow config values
  .github/workflows/deploy-integration-swb-reference-byon.yml
Labels: size/xs

#987 chore: cdk and nodejs version update
  .github/actions/baseAction/action.yml
  .github/workflows/pnpm-audit.yml
  buildspec.yml
  common/changes/@aws/swb-app/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-accounts-ui/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-accounts/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-audit/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-authentication/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-authorization/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-base/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-datasets-ui/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-datasets/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-environments-ui/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-environments/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-infrastructure/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-logging/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-swb-common-ui/version-update_2023-04-06-19-23.json
  common/changes/@aws/workbench-core-user-management/version-update_2023-04-06-19-23.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  rush.json
  solutions/example-ui-app/cache/config.json
  solutions/example-ui-app/package.json
  solutions/swb-app/package.json
  solutions/swb-reference/package.json
  solutions/swb-reference/src/SWBStack.ts
  workbench-core/accounts-ui/package.json
  workbench-core/accounts/package.json
  workbench-core/audit/package.json
  workbench-core/authentication/package.json
  workbench-core/authorization/package.json
  workbench-core/base/package.json
  workbench-core/datasets-ui/package.json
  workbench-core/datasets/package.json
  workbench-core/environments-ui/package.json
  workbench-core/environments/package.json
  workbench-core/eslint-custom/package.json
  workbench-core/example/app/package.json
  workbench-core/example/infrastructure/package.json
  workbench-core/infrastructure/package.json
  workbench-core/logging/package.json
  workbench-core/repo-scripts/repo-toolbox/package.json
  workbench-core/swb-common-ui/package.json
  workbench-core/user-management/package.json
Labels: size/m

#992 chore(get environment api): restrict Environment dependencies response
  .viperlightignore
  common/changes/@aws/swb-app/farandac-fix-environment-dependencies-models_2023-04-07-01-47.json
  common/changes/@aws/workbench-core-accounts/farandac-fix-environment-dependencies-models_2023-04-07-01-47.json
  common/changes/@aws/workbench-core-environments/farandac-fix-environment-dependencies-models_2023-04-07-01-47.json
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.test.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.ts
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/handlers/statusHandler.ts
  workbench-core/environments/src/models/environments/environment.ts
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/m

#998 chore: xml2js pnpm audit fix
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
Labels: size/xs

#1001 feat: automate merge release to develop
  .github/workflows/create-release-pr-to-develop.yml
Labels: size/s

#1004 test(dataset integ test): update dataset integ tests
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
Labels: size/s

#1005 chore: fix s3 bucket object ownership
  common/changes/@aws/workbench-core-infrastructure/fix-s3-object-ownership_2023-04-12-19-28.json
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.test.ts
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/infrastructure/src/workbenchSecureS3Bucket.test.ts
  workbench-core/infrastructure/src/workbenchSecureS3Bucket.ts
Labels: size/s

#1006 fix: sonarqube config
  sonar-project.properties
Labels: size/s

#1009 feat: add automerge labeler
  .github/workflows/automerge-release-pr-to-develop.yml
  .github/workflows/create-release-pr-to-develop.yml
Labels: size/s

#1010 fix: remove preference for release
  .github/workflows/create-release-pr-to-develop.yml
Labels: size/s

#1011 fix: remove checkout ours
  .github/workflows/create-release-pr-to-develop.yml
Labels: size/xs

#995 feat: add OpenAPI collection for swb-reference
  solutions/swb-reference/SWBv2.openapi.json
  solutions/swb-reference/SWBv2.postman_collection.json
Labels: size/xl

#1015 fix: reorder create-release-pr-to-develop workflow
  .github/workflows/create-release-pr-to-develop.yml
Labels: size/s

#1016 fix: label name
  .github/workflows/automerge-release-pr-to-develop.yml
Labels: size/xs

#1014 chore: allow NodeJS 16, solutions pipeline does not support NodeJS 18…
  rush.json
Labels: size/xs

#1012 fix: aws cdk iam
  common/changes/@aws/workbench-core-accounts/fix-aws-cdk-iam_2023-04-13-17-40.json
  common/changes/@aws/workbench-core-datasets/fix-aws-cdk-iam_2023-04-13-17-40.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/integration-tests/support/complex/accountHelper.ts
  solutions/swb-reference/package.json
  workbench-core/accounts/package.json
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/datasets/package.json
  workbench-core/datasets/src/awsUtilities/iamHelper.test.ts
  workbench-core/datasets/src/awsUtilities/iamHelper.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
Labels: size/s

#1018 fix: code smell
  solutions/swb-reference/scripts/buildLambda.js
  workbench-core/example/infrastructure/scripts/generateCognitoTokens.js
Labels: size/xs

#1017 fix(pa-permission): add missing PA permission and update integ test
  .viperlightignore
  solutions/swb-reference/integration-tests/tests/isolated/projects/assignUserToProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/user.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userApi.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.ts
  solutions/swb-reference/src/services/swbProjectService.test.ts
  solutions/swb-reference/src/services/swbProjectService.ts
Labels: size/m

#996 test: end to end tests for authentication
  common/changes/@aws/workbench-core-authentication/topic-cypressLoginLogout_2023-04-10-21-32.json
  common/changes/@aws/workbench-core-datasets-ui/topic-cypressLoginLogout_2023-04-10-21-32.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationMiddleware.ts
  workbench-core/datasets-ui/package.json
  workbench-core/example/infrastructure/cypress.config.ts
  workbench-core/example/infrastructure/cypress/app/App.tsx
  workbench-core/example/infrastructure/cypress/app/LoginCallback.tsx
  workbench-core/example/infrastructure/cypress/app/api.ts
  workbench-core/example/infrastructure/cypress/app/constants.ts
  workbench-core/example/infrastructure/cypress/app/index.tsx
  workbench-core/example/infrastructure/cypress/e2e/authRoutes.cy.tsx
  workbench-core/example/infrastructure/cypress/e2e/routeHandler.cy.ts
  workbench-core/example/infrastructure/package.json
Labels: size/l

#1022 fix(swb-ref): adjust sagemaker iam policy
  solutions/swb-reference/src/SWBStack.ts
Labels: size/xs

#1019 chore(dataset apis): add zod to missing routes
  common/changes/@aws/swb-app/farandac-list-dataset-zod-validation_2023-04-17-06-55.json
  common/changes/@aws/workbench-core-base/farandac-list-dataset-zod-validation_2023-04-17-06-55.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/getDataSetByProjectRequestParser.ts
  solutions/swb-app/src/dataSets/getDataSetRequestParser.ts
  solutions/swb-app/src/dataSets/listDataSetRequestParser.ts
  solutions/swb-reference/integration-tests/support/utils/utilities.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/getDataSetForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listDataSetsForProject.test.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/m

#1024 fix: sonar exclusions
  sonar-project.properties
Labels: size/xs

#1025 fix: ignore js files from sonar scans
  sonar-project.properties
Labels: size/s

#1021 chore: automate SWB integration test environment setup
  .viperlightignore
  solutions/swb-reference/README.md
  solutions/swb-reference/scripts/setupIntegTestEnv.sh
Labels: size/m

#1027 fix: ignore build folders for sonar scan
  sonar-project.properties
Labels: size/xs

#1028 fix: add sonar exclusions
  sonar-project.properties
Labels: size/s

#1023 feat: allow/revoke temp group access
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/topic-tempGroupAccess_2023-04-18-08-47.json
  common/changes/@aws/workbench-core-user-management/topic-tempGroupAccess_2023-04-18-08-47.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/models/validateUserGroups.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/example/app/src/services/userManagementService.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/user-management/config/jest.config.json
  workbench-core/user-management/package.json
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/user-management/src/plugins/tempRoleAccessEntry.ts
  workbench-core/user-management/src/userManagementPlugin.ts
  workbench-core/user-management/src/userManagementService.test.ts
  workbench-core/user-management/src/userManagementService.ts
Labels: size/m

#1029 chore(zod): add zod model for regex
  common/changes/@aws/workbench-core-base/janeyu-zodModel_2023-04-19-21-57.json
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/m

#1030 feat: enable rate limiter in dynamic authz middleware
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/topic-dAuthzRateLimiter_2023-04-20-23-21.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/authorization/package.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Labels: size/s

#1032 chore(project-etc routes): add format,length and required validations
  common/changes/@aws/swb-app/farandac-project-etc-input-validations_2023-04-24-03-01.json
  common/changes/@aws/workbench-core-authorization/farandac-project-etc-input-validations_2023-04-24-03-01.json
  common/changes/@aws/workbench-core-base/farandac-project-etc-input-validations_2023-04-24-03-01.json
  solutions/swb-app/src/projectEnvTypeConfigs/associateProjectEnvTypeConfigRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/disassociateProjectEnvTypeConfigRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/getProjectEnvTypeConfigRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listEnvTypeConfigProjectsRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listProjectEnvTypeConfigsRequest.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/projectEnvService.test.ts
  solutions/swb-reference/src/services/projectEnvTypeConfigService.test.ts
  solutions/swb-reference/src/services/swbProjectService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationMiddleware.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/models/authenticatedUser.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/m

#1034 chore: auth user fix validation
  common/changes/@aws/workbench-core-authorization/farandac-authUser-fix-validation_2023-04-24-18-47.json
  workbench-core/authorization/src/models/authenticatedUser.ts
Labels: size/s

#1036 fix(swb datsets): shorten TTL for 2 min for upload to dataset
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/xs

#1037 feat(swb-ref): adding auth APIs to postman/openapi collections
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/SWBv2.openapi.json
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/package.json
  solutions/swb-reference/scripts/generateCodeChallenge.js
Labels: size/m

#1039 chore(env list, et routes): add input length and format validation
  common/changes/@aws/swb-app/farandac-et-input-validation_2023-04-26-05-30.json
  common/changes/@aws/workbench-core-base/farandac-et-input-validation_2023-04-26-05-30.json
  common/changes/@aws/workbench-core-environments/farandac-et-input-validation_2023-04-26-05-30.json
  solutions/swb-app/src/environmentRoutes.ts
  solutions/swb-app/src/environmentTypeRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-reference/integration-tests/support/utils/utilities.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
  workbench-core/base/config/jest.config.json
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/queryStringParamFilter.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
  workbench-core/environments/config/jest.config.json
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/models/environmentTypes/getEnvironmentTypesRequest.ts
  workbench-core/environments/src/models/environmentTypes/listEnvironmentTypesRequest.ts
  workbench-core/environments/src/models/environmentTypes/updateEnvironmentTypeRequest.ts
Labels: size/m

#1038 fix(AppSec): s3 accesslog bucket only accept HTTPS
  solutions/swb-reference/src/SWBStack.ts
Labels: size/s

#1040 fix(swb): adding permission to allow calling Send SSH Public Key and …
  common/changes/@aws/swb-app/kevpark-update-send-ssh-key-permission_2023-04-27-19-17.json
  solutions/swb-app/src/sshKeyRoutes.ts
  solutions/swb-app/src/sshKeys/sendPublicKeyRequest.ts
  solutions/swb-reference/SWBv2.openapi.json
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/services/sshKeyService.test.ts
  solutions/swb-reference/src/services/sshKeyService.ts
Labels: size/s
