Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2023-01, with the labels that each got.

#724 feat: Stub out DataSets authz plugin and add to DataSetsService
  common/changes/@aws/workbench-core-datasets/topic-datasets-wbcauthplugin_2022-12-23-01-30.json
  common/changes/@aws/workbench-core-environments/topic-datasets-wbcauthplugin_2022-12-23-01-30.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/package.json
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/environments/README.md
  workbench-core/environments/package.json
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
  workbench-core/example/app/src/services/datasetService.ts
Labels: size/m

#733 feat: Implement isUserAssignedToGroup API
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/topic-implement-is-user-assigned-to-group_2022-12-31-00-34.json
  workbench-core/authorization/README.md
  workbench-core/authorization/config/jest.config.json
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isUserAssignedToGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/group.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/groups.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
Labels: size/l

#722 chore: create GH workflow for BYON pipeline
  .github/workflows/deploy-integration-swb-reference-byon.yml
  .github/workflows/merge-develop-to-stage.yml
  .gitignore
  solutions/swb-reference/src/config/swbv2-private.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
  solutions/swb-ui/ui/README.md
  solutions/swb-ui/ui/scripts/deploy.sh
Labels: size/m

#736 fix: group management fixes
  common/changes/@aws/workbench-core-authorization/fix-group-management-fixes_2023-01-04-00-10.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
Labels: size/m

#734 feat: add getIdentityPermissionsByIdentity
  common/changes/@aws/workbench-core-authorization/topic-getIdentityPermissionsByIdentity_2022-12-31-05-46.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/src/SWBStack.ts
  workbench-core/authorization/README.md
  workbench-core/authorization/package.json
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsByIdentity.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/index.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
  workbench-core/example/infrastructure/src/example-stack.ts
Labels: size/m

#727 feat: enable customer managed encryption of DDB table
  solutions/swb-reference/src/SWBStack.ts
Labels: size/s

#738 feat: getIdentityPermissionsBySubject implemented
  common/changes/@aws/workbench-core-authorization/topic-getIdentityPermissionsBySubject_2023-01-05-08-28.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getIdentityPermissionsBySubject.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/index.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Labels: size/l

#740 fix: permissions collision for integration test
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Labels: size/s

#739 feat: verify group status for addUserToGroup
  common/changes/@aws/workbench-core-authorization/topic-verify-group-status-for-addUserToGroup_2023-01-05-19-00.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
Labels: size/s

#741 feat: deleteIdentityPermissions implemented
  common/changes/@aws/workbench-core-authorization/topic-deleteIdentityPermissions_2023-01-06-12-26.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/createIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/identityPermission.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/errors/errors.test.ts
  workbench-core/authorization/src/errors/retryError.ts
  workbench-core/authorization/src/index.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Labels: size/m

#748 feat(swb-ref): add roleUtils
  solutions/swb-reference/src/errors.ts
  solutions/swb-reference/src/utils/roleUtils.test.ts
  solutions/swb-reference/src/utils/roleUtils.ts
Labels: size/s

#750 chore: disable telemetry for nextjs project builds
  solutions/example-ui-app/package.json
  solutions/swb-ui/ui/package.json
Labels: size/xs

#749 test(projects): integ tests
  common/changes/@aws/workbench-core-base/maghirardelli-gali-1925-integ-tests_2023-01-10-17-51.json
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/resources.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/support/resources/projects/projects.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/project.test.ts
  workbench-core/base/README.md
  workbench-core/base/src/aws/helpers/dynamoDB/updater.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/updater.ts
Labels: size/l

#752 docs: improve ssm document
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookLaunchSSM.yaml
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookTerminateSSM.yaml
Labels: size/s

#745 docs: add securitygroup description
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
Labels: size/xs

#753 fix(backendapi.ts): add requiredAuditValues and fieldsToMask to dataS…
  common/changes/@aws/workbench-core-environments/topic-datasets-auditfix_2023-01-10-21-31.json
  solutions/swb-reference/src/backendAPI.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/s

#743 fix: renamed AddExternalEndpoint to AddExternalEndpointForUser and updated for AuthZ
  .viperlightignore
  common/changes/@aws/swb-app/fix-update-add-external-endpoint-for-authZ_2023-01-09-17-56.json
  common/changes/@aws/workbench-core-datasets/fix-update-add-external-endpoint-for-authZ_2023-01-09-17-56.json
  common/changes/@aws/workbench-core-environments/fix-update-add-external-endpoint-for-authZ_2023-01-09-17-56.json
  common/config/rush/pnpm-config.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/createExternalEndpointRequestParser.ts
  solutions/swb-app/src/dataSets/dataSetAccessLevelParser.ts
  solutions/swb-app/src/dataSets/dataSetAddExternalEndpointResponseParser.ts
  solutions/swb-app/src/dataSets/dataSetExternalEndpointRequest.ts
  solutions/swb-app/src/dataSets/dataSetMountObjectParser.ts
  solutions/swb-app/src/dataSets/dataSetPermissionParser.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/dataSetStoragePlugin.ts
  solutions/swb-app/src/index.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsStoragePlugin.ts
  workbench-core/datasets/src/errors/errors.test.ts
  workbench-core/datasets/src/errors/notAuthorizedError.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/models/addDataSetExternalEndpoint.ts
  workbench-core/datasets/src/models/addStorageExternalEndpoint.ts
  workbench-core/datasets/src/models/dataSetMountObject.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.test.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
Labels: size/l

#746 feat: getOperationsByRoute, isRouteProtected, and isRouteIgnored implemented
  common/changes/@aws/workbench-core-authorization/topic-isRouteProtected_2023-01-09-19-07.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/authorization/README.md
  workbench-core/authorization/package.json
  workbench-core/authorization/src/authorizationMiddleware.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/dynamicOperation.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getDynamicOperationsByRoute.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/identityPermission.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteIgnored.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/isRouteProtected.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/errors/errors.test.ts
  workbench-core/authorization/src/errors/routeMapError.ts
  workbench-core/authorization/src/errors/routeNotFoundError.ts
  workbench-core/authorization/src/index.ts
  workbench-core/authorization/src/routesMap.ts
  workbench-core/example/app/src/configs/dynamicRouteConfig.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/app/src/services/dynamicAuthorizationService.ts
  workbench-core/example/infrastructure/integration-tests/support/resources.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/routeProtection.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/routesProtection.test.ts
Labels: size/l

#757 feat: implementation of dynamicAuthorization.deleteGroup
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/feat-dynamicAuthzDeleteGroup_2023-01-10-23-14.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteGroup.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/base/resource.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
Labels: size/m

#758 feat(swb-ref): add SwbAuthZSubject enum and fix roleUtils to expect l…
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/utils/roleUtils.test.ts
  solutions/swb-reference/src/utils/roleUtils.ts
Labels: size/s

#762 fix(e2e environment): fix issue with studies blocking clicking ETC
  solutions/swb-ui/ui/end-to-end-tests/cypress/support/common-utils.ts
  solutions/swb-ui/ui/end-to-end-tests/cypress/support/environments-utils.ts
Labels: size/s

#729 chore: moved handler/envTypeHandler to postDeployment/envTypeSetup
  common/changes/@aws/workbench-core-environments/chore-envTypeHandler-refactor_2022-12-29-16-24.json
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-reference/src/accountHandlerLambda.ts
  solutions/swb-reference/src/postDeployment.ts
  workbench-core/environments/src/index.ts
  workbench-core/environments/src/postDeployment/environmentTypeSetup.test.ts
  workbench-core/environments/src/postDeployment/environmentTypeSetup.ts
Labels: size/s

#765 feat(datasets): implement getDataSetsAccessPermissions and getAllDataSetsAccessPermissions
  .viperlightignore
  common/changes/@aws/swb-app/topic-datasets-getAllAccess_2023-01-12-00-51.json
  common/changes/@aws/workbench-core-datasets/topic-datasets-getAllAccess_2023-01-12-00-51.json
  solutions/swb-app/src/dataSets/getAccessPermissionRequestParser.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsAuthorizationPlugin.ts
  workbench-core/datasets/src/models/getAccessPermissionRequest.ts
  workbench-core/datasets/src/schemas/createExternalEndpoint.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/delete.test.ts
Labels: size/l

#751 feat: update account APIs to Zod for validation
  common/changes/@aws/swb-app/thingut-GALI-2085-account-zod_2023-01-10-22-33.json
  common/changes/@aws/workbench-core-accounts/thingut-GALI-2085-account-zod_2023-01-10-22-33.json
  solutions/swb-app/src/accountRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/config/jest.config.json
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/accounts/awsAccountTemplateUrlsRequest.ts
  workbench-core/accounts/src/models/accounts/createAccountRequest.ts
  workbench-core/accounts/src/models/accounts/getAccountRequest.ts
  workbench-core/accounts/src/models/accounts/updateAccountRequest.ts
  workbench-core/accounts/src/schemas/createAccount.ts
  workbench-core/accounts/src/schemas/updateAccount.ts
  workbench-core/accounts/src/services/accountService.test.ts
  workbench-core/accounts/src/services/accountService.ts
  workbench-core/accounts/src/services/hostingAccountService.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
Labels: size/l

#768 fix: get swb integration tests working again
  common/changes/@aws/swb-app/topic-datasets-swbfix_2023-01-12-22-20.json
  common/changes/@aws/workbench-core-datasets/topic-datasets-swbfix_2023-01-12-22-20.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/createDataSetRequestParser.ts
  solutions/swb-app/src/dataSets/createProvisionDatasetRequest.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.ts
Labels: size/s

#769 test: account integ tests
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts
Labels: size/xs

#773 test(e2e tests): update project name for e2e tests
  solutions/swb-ui/ui/end-to-end-tests/config/testEnv.yaml
Labels: size/xs

#747 feat: Implement addExternalEndpointForGroup API
  .viperlightignore
  common/changes/@aws/workbench-core-authorization/topic-implement-add-external-endpoint-for-group_2023-01-11-18-03.json
  common/changes/@aws/workbench-core-datasets/topic-implement-add-external-endpoint-for-group_2023-01-11-18-03.json
  common/changes/@aws/workbench-core-environments/topic-implement-add-external-endpoint-for-group_2023-01-11-18-03.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/authorization/src/index.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetMetadataPlugin.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsStoragePlugin.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/errors/dataSetNotFoundError.ts
  workbench-core/datasets/src/errors/errors.test.ts
  workbench-core/datasets/src/errors/invalidArnError.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/models/addDataSetExternalEndpoint.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.test.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
  workbench-core/example/app/src/models/datasets/createExternalEndpoint.ts
  workbench-core/example/app/src/models/datasets/createPresignedFileUpload.ts.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/randomTextGenerator.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/regExpressions.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/delete.test.ts
  workbench-core/example/infrastructure/package.json
Labels: size/l

#774 chore: ma-foundation-600: update CODEOWNERS
  .github/CODEOWNERS
Labels: size/s

#756 feat(datasets): implement removeDataSetAccessPermissions
  common/changes/@aws/workbench-core-datasets/topic-datasets-removeAccessPermission_2023-01-11-01-47.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
Labels: size/l

#776 fix(datasets): update example app return values to match expected 404…
  workbench-core/example/app/src/routes/datasetRoutes.ts
Labels: size/xs

#767 feat(dynamicauthorizationservice.ts): remove delete_pending status information
  common/changes/@aws/workbench-core-authorization/topic-dynamicAuthzRemovePendingDeleteStatus_2023-01-12-19-20.json
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/getGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/setGroupStatus.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/models/GetGroupMetadata.ts
  workbench-core/authorization/src/dynamicAuthorization/models/GroupMetadata.ts
  workbench-core/authorization/src/dynamicAuthorization/models/SetGroupMetadata.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/authorization/src/index.ts
Labels: size/m

#779 feat: dynamic authz - implement deleteSubjectIdentityPermissions
  common/changes/@aws/workbench-core-authorization/topic-dynamicAuthzDeleteSubjectIdentityPermissions_2023-01-19-17-17.json
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/ddbDynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/deleteSubjectIdentityPermissions.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationPermissionsPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/identityPermissions.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Labels: size/m

#781 chore: update no-response.yml workflow, the github apps seems to be n…
  .github/no-reponsel.yml
  .github/no-response.yml
Labels: size/s

#777 feat(datasets): add access permissions at dataset creation
  .viperlightignore
  common/changes/@aws/workbench-core-datasets/topic-datasets-updateCreate_2023-01-18-18-15.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSet.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/models/addRemoveAccessPermissionRequest.ts
  workbench-core/datasets/src/schemas/createDataSet.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/delete.test.ts
Labels: size/l

#782 test(accesspermissions.test.ts): update getDatasetAllAccessPermission…
  workbench-core/example/infrastructure/integration-tests/tests/datasets/accessPermissions.test.ts
Labels: size/s

#778 feat(key-pairs): key pair service and skeleton code
  common/changes/@aws/swb-app/maghirardelli-ssh-gali-1758-service_2023-01-19-16-13.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/keyPairRoutes.ts
  solutions/swb-app/src/keyPairs/createKeyPairRequest.ts
  solutions/swb-app/src/keyPairs/createKeyPairResponse.ts
  solutions/swb-app/src/keyPairs/deleteKeyPairRequest.ts
  solutions/swb-app/src/keyPairs/getKeyPairRequest.ts
  solutions/swb-app/src/keyPairs/getKeyPairResponse.ts
  solutions/swb-app/src/keyPairs/keyPair.ts
  solutions/swb-app/src/keyPairs/keyPairPlugin.ts
  solutions/swb-app/src/keyPairs/listKeyPairsRequest.test.ts
  solutions/swb-app/src/keyPairs/listKeyPairsRequest.ts
  solutions/swb-app/src/keyPairs/sendPublicKeyRequest.ts
  solutions/swb-app/src/keyPairs/sendPublicKeyResponse.ts
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-reference/src/services/keyPairService.ts
Labels: size/m

#783 chore: add AppRegistry Construct, integrate AppRegistry with ExampleS…
  .viperlightignore
  common/changes/@aws/workbench-core-infrastructure/AppRegistryConstruct_2023-01-20-08-41.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/example-ui-app/cache/config.json
  solutions/swb-reference/package.json
  solutions/swb-ui/infrastructure/package.json
  solutions/swb-ui/ui/cache/config.json
  workbench-core/example/infrastructure/package.json
  workbench-core/example/infrastructure/src/config/appReg.env
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/example/infrastructure/src/index.ts
  workbench-core/infrastructure/README.md
  workbench-core/infrastructure/config/jest.config.json
  workbench-core/infrastructure/docs/workbenchAppRegistry.md
  workbench-core/infrastructure/docs/workbenchAssociateStackToExistingAppRegistryApplication.md
  workbench-core/infrastructure/package.json
  workbench-core/infrastructure/src/index.ts
  workbench-core/infrastructure/src/workbenchAppRegistry.test.ts
  workbench-core/infrastructure/src/workbenchAppRegistry.ts
  workbench-core/infrastructure/src/workbenchApplyTags.ts
  workbench-core/infrastructure/src/workbenchAssociateStackToExistingAppRegistryApplication.test.ts
  workbench-core/infrastructure/src/workbenchAssociateStackToExistingAppRegistryApplication.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
  workbench-core/infrastructure/src/workbenchDynamodb.test.ts
  workbench-core/infrastructure/src/workbenchSecureS3Bucket.test.ts
Labels: size/l

#780 feat: enable s3 bucket version
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
  solutions/swb-ui/infrastructure/src/SWBUIStack.ts
Labels: size/s

#772 fix: updated getDataSetMountObject to check for DataSets permissions
  .viperlightignore
  common/changes/@aws/swb-app/fix-update-get-mount-object-for-authz_2023-01-19-23-20.json
  common/changes/@aws/workbench-core-datasets/fix-update-get-mount-object-for-authz_2023-01-18-23-48.json
  common/changes/@aws/workbench-core-environments/fix-update-get-mount-object-for-authz_2023-01-18-23-48.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/example-ui-app/cache/config.json
  solutions/swb-app/src/dataSets/endpointConnectionStrings.ts
  solutions/swb-app/src/dataSets/externalEndpoint.ts
  solutions/swb-ui/ui/cache/config.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetMetadataPlugin.ts
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsStoragePlugin.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.test.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/errors/dataSetExistsError.ts
  workbench-core/datasets/src/errors/endPointExistsError.ts
  workbench-core/datasets/src/errors/endpointExistsError.ts
  workbench-core/datasets/src/errors/endpointNotFoundError.ts
  workbench-core/datasets/src/errors/errors.test.ts
  workbench-core/datasets/src/errors/invalidEndpointError.ts
  workbench-core/datasets/src/externalEndpoint.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/models/dataSet.ts
  workbench-core/datasets/src/models/externalEndpoint.ts
  workbench-core/datasets/src/models/getDataSetMountPoint.ts
  workbench-core/datasets/src/models/getDataSetMountPointRequest.ts
  workbench-core/datasets/src/models/storageLocation.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.test.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/example/app/src/configs/constants.ts
  workbench-core/example/app/src/configs/staticPermissionsConfig.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/app/src/services/datasetService.ts
  workbench-core/example/infrastructure/integration-tests/support/clientSession.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/base/resource.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/endpoint.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/regExpressions.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/get.test.ts
  workbench-core/example/infrastructure/package.json
Labels: size/xl

#784 fix: fixed broken tests
  workbench-core/example/infrastructure/integration-tests/tests/datasets/get.test.ts
Labels: size/s

#786 feat(datasets): implement removeAllAccessPermissions and update removeDataSet
  .viperlightignore
  common/changes/@aws/workbench-core-datasets/topic-datasets-removeDataSet_2023-01-20-21-58.json
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsAuthorizationPlugin.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/delete.test.ts
Labels: size/m

#790 chore: add ApplicationInsightsConfiguration, update removalPolicy
  .github/CODEOWNERS
  common/changes/@aws/workbench-core-infrastructure/AppInsight_2023-01-25-18-26.json
  solutions/example-ui-app/cache/config.json
  solutions/swb-ui/ui/cache/config.json
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/example/infrastructure/src/index.ts
  workbench-core/infrastructure/README.md
  workbench-core/infrastructure/src/helpers/index.ts
  workbench-core/infrastructure/src/helpers/workbenchAppRegistryHelperFunctions.ts
  workbench-core/infrastructure/src/workbenchAppRegistry.ts
  workbench-core/infrastructure/src/workbenchApplyTags.ts
  workbench-core/infrastructure/src/workbenchAssociateStackToExistingAppRegistryApplication.ts
Labels: size/m

#791 feat: bootstrap it admin
  common/changes/@aws/workbench-core-environments/sevu-features-bootstrap-it-admin_2023-01-25-23-21.json
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/postDeployment.ts
  workbench-core/environments/src/postDeployment/authorizationSetup.test.ts
  workbench-core/environments/src/postDeployment/authorizationSetup.ts
  workbench-core/environments/src/postDeployment/cognitoSetup.ts
Labels: size/m

#792 feat(swb): Merge BYON into develop
  .github/CODEOWNERS
  .github/workflows/deploy-integration-swb-reference-byon.yml
  .github/workflows/deploy-integration-swb-reference.yml
  .github/workflows/enable-feat-protection.yml
  .github/workflows/feat-deletion.yml
  .github/workflows/merge-develop-to-stage.yml
  .gitignore
  .viperlightignore
  common/changes/@aws/workbench-core-swb-common-ui/kevpark-merge-swb-byon_2023-01-26-10-44.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/example-ui-app/src/context/NotificationContext.tsx
  solutions/swb-reference/README.md
  solutions/swb-reference/config/jest.config.json
  solutions/swb-reference/integration-tests/support/utils/HttpError.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/package.json
  solutions/swb-reference/scripts/buildLambda.js
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/swbv2-private.yaml
  solutions/swb-reference/src/config/testEnv.yaml
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.test.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
  solutions/swb-reference/src/infra/SWBVpc.test.ts
  solutions/swb-reference/src/infra/SWBVpc.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
  solutions/swb-reference/src/templates/README.md
  solutions/swb-reference/src/templates/new-firewall-vpc.yaml
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-ui/infrastructure/src/SWBUIStack.ts
  solutions/swb-ui/infrastructure/src/constants.ts
  solutions/swb-ui/infrastructure/src/hosting-infra/ecs-cluster.ts
  solutions/swb-ui/infrastructure/src/index.ts
  solutions/swb-ui/ui/Dockerfile
  solutions/swb-ui/ui/README.md
  solutions/swb-ui/ui/package.json
  solutions/swb-ui/ui/scripts/image-deploy.sh
  workbench-core/swb-common-ui/src/common/utils.ts
  workbench-core/swb-common-ui/src/index.tsx
Labels: size/xl

#785 feat: update listDatasets for authZ
  common/changes/@aws/workbench-core-datasets/fix-update-list-datasets-for-authZ_2023-01-25-01-03.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/dataSetsAuthorizationPlugin.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.test.ts
  workbench-core/datasets/src/wbcDataSetsAuthorizationPlugin.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/clientSession.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/get.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/list.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/identityPermissions.test.ts
Labels: size/l

#793 feat(datasets): grant implicit permission to dataset 'owner' when no explicit permissions are given
  .viperlightignore
  common/changes/@aws/workbench-core-datasets/topic-datasets-createAccessFix_2023-01-26-21-14.json
  workbench-core/datasets/README.md
  workbench-core/datasets/src/dataSetService.test.ts
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/errors/dataSetInvalidParameterError.ts
  workbench-core/datasets/src/errors/errors.test.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/models/createProvisionDatasetRequest.ts
  workbench-core/datasets/src/models/dataSet.ts
  workbench-core/datasets/src/schemas/createDataSet.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
Labels: size/m

#794 feat: implement doesGroupExist and refactor setGroupStatus
  common/changes/@aws/workbench-core-authorization/topic-doesGroupExist_2023-01-26-23-56.json
  common/changes/@aws/workbench-core-environments/topic-doesGroupExist_2023-01-27-00-34.json
  workbench-core/authorization/README.md
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationInputs/doesGroupExist.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.test.ts
  workbench-core/authorization/src/dynamicAuthorization/dynamicAuthorizationService.ts
  workbench-core/authorization/src/dynamicAuthorization/groupManagementPlugin.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/authorization/src/index.ts
  workbench-core/environments/src/postDeployment/authorizationSetup.test.ts
  workbench-core/example/app/src/configs/staticRouteConfig.ts
  workbench-core/example/app/src/routes/dynamicAuthorizationRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/dynamicAuthorization/group.ts
  workbench-core/example/infrastructure/integration-tests/tests/dynamicAuthorization/group.test.ts
Labels: size/m

#796 fix: spelling issue with deploy-swb-reference-byon
  .github/workflows/merge-develop-to-stage.yml
Labels: size/xs

#795 feat: user to project association api
  .viperlightignore
  common/changes/@aws/swb-app/sevu-features-user-management_2023-01-27-18-06.json
  common/changes/@aws/workbench-core-accounts/sevu-features-user-management_2023-01-27-18-06.json
  common/changes/@aws/workbench-core-base/sevu-features-user-management_2023-01-27-18-06.json
  solutions/example-ui-app/cache/config.json
  solutions/swb-app/src/apiRouteConfig.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/staticPermissionsConfig.ts
  solutions/swb-app/src/staticRouteConfig.ts
  solutions/swb-app/tsconfig.json
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/integration-tests/support/clientSession.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/assignUserToProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
  solutions/swb-reference/src/backendAPI.ts
  solutions/swb-ui/ui/cache/config.json
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/projects/assignUserToProjectRequest.ts
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/promiseUtils.test.ts
  workbench-core/base/src/utilities/promiseUtils.ts
  workbench-core/base/src/utilities/textUtil.ts
Labels: size/l

#799 chore: remove instances of environment costCenterId from code
  .viperlightignore
  solutions/swb-reference/integration-tests/tests/isolated/projects/assignUserToProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
Labels: size/s

#798 fix: add domainName and hostedZoneId to testEnv and demo configs
  .github/workflows/deploy-integration-swb-reference.yml
  .github/workflows/deploy-swb-reference-demo.yml
  solutions/swb-reference/src/config/demo.yaml
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/config/testEnv.yaml
Labels: size/s

#801 fix: fix byon integ config
  .github/workflows/merge-develop-to-stage.yml
Labels: size/xs

#802 fix: cleanup github workflows
  .github/workflows/deploy-integration-swb-reference-byon.yml
  .github/workflows/deploy-integration-swb-reference.yml
  .github/workflows/deploy-swb-reference-demo.yml
  .github/workflows/merge-develop-to-stage.yml
Labels: size/s

#804 fix: fix swbv2 private config
  solutions/swb-reference/src/config/swbv2-private.yaml
Labels: size/xs

#800 refactor: remove cloud front
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-ui/infrastructure/src/SWBUIStack.ts
  solutions/swb-ui/infrastructure/src/constants.ts
  solutions/swb-ui/infrastructure/src/redirectFunction.js
Labels: size/m
