Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2023-07, with the labels that each got.

#1150 fix: delete all temp role access when role is deleted
  .github/workflows/pnpm-audit.yml
  common/changes/@aws/workbench-core-user-management/topic-fixTempRoleAccess_2023-06-20-20-58.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  workbench-core/user-management/package.json
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/user-management/src/plugins/tempRoleAccessEntry.ts
Labels: size/m

#1165 test(ssh key integ tests): send ssh key negative tests
  common/changes/@aws/swb-reference/maghirardelli-add-ssh-key-integ-test_2023-07-03-21-01.json
  solutions/swb-reference/integration-tests/support/resources/environments/environment.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/sendSshKey.test.ts
Labels: size/m

#1164 feat: main equal to hosting
  common/changes/@aws/swb-reference/chore-main-hosting-same_2023-07-05-18-07.json
  common/changes/@aws/workbench-core-accounts/chore-main-hosting-same_2023-07-05-18-07.json
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
Labels: size/m

#1168 chore: merge main to develop
  .github/workflows/npm-publish.yml
  deployment/build-s3-dist.sh
  solutions/swb-reference/README.md
  solutions/swb-reference/README_SOLUTIONS.md
  solutions/swb-reference/RSW.openapi.json
  solutions/swb-reference/RSW.postman_collection.json
  solutions/swb-reference/scripts/solutions-implementation/baseResourceSetup.sh
  solutions/swb-reference/scripts/solutions-implementation/postSolutionDeployment.sh
Labels: size/m, skip-verify-changefiles

#1169 feat(ALB): delete protection
  common/changes/@aws/swb-reference/janeyu-ALBDelete_2023-07-25-22-19.json
  solutions/swb-reference/src/infra/RSWApplicationLoadBalancer.test.ts
  solutions/swb-reference/src/infra/RSWApplicationLoadBalancer.ts
Labels: size/s
