Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2023-03, with the labels that each got.

#919 chore: use Zod in Create Cost Center API
  common/changes/@aws/swb-app/atmikev-GALI-2084_ZodCostCenterAPIs_2023-02-28-22-58.json
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-2084_ZodCostCenterAPIs_2023-02-28-22-58.json
  solutions/swb-app/src/costCenterRoutes.ts
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/costCenters/createCostCenterRequest.ts
  workbench-core/accounts/src/schemas/createCostCenter.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
Labels: size/s

#921 chore: cost center test fix
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
Labels: size/xs

#923 fix: allow other users in same project to see environments
  common/changes/@aws/workbench-core-environments/farandac-fix-listEnvs-paab_2023-03-02-17-45.json
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/services/environmentService.test.ts
  workbench-core/environments/src/services/environmentService.ts
Labels: size/s

#917 feat: add purge of ITAdmin permissions
  solutions/swb-reference/README.md
  solutions/swb-reference/src/postDeployment/authorizationSetup.test.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.ts
Labels: size/s

#924 feat: increase github workflow assume role for swb-reference to 2 hours
  .github/workflows/deploy-integration-swb-reference-byon.yml
  .github/workflows/deploy-integration-swb-reference.yml
Labels: size/xs

#922 test(dataset): unit test for listDataSetsForProject
  solutions/swb-reference/README.md
  solutions/swb-reference/src/services/dataSetService.test.ts
Labels: size/m

#926 chore: remove unnecessary log
  solutions/swb-reference/src/services/dataSetService.test.ts
Labels: size/xs

#931 chore(project routes): add zod to disassociate user to proj
  common/changes/@aws/swb-app/farandac-add-Zod-to-UserProj_2023-03-08-20-33.json
  solutions/swb-app/README.md
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/projects/disassociateUserFromProjectRequest.ts
Labels: size/s

#930 feat: change release stategy
  .github/workflows/check-and-add-license-header.yml
  .github/workflows/create-release-branch.yml
  .github/workflows/merge-develop-to-stage.yml
  .github/workflows/merge-release-pr-to-main.yml
  .github/workflows/merge-release-to-develop.yml
  .github/workflows/readme-commit.yml
  .github/workflows/security-code-scanning.yml
  .github/workflows/verify-changefiles.yml
Labels: size/m

#932 fix: with instead of inputs
  .github/workflows/merge-release-to-develop.yml
Labels: size/xs

#933 fix: stage requires with
  .github/workflows/merge-develop-to-stage.yml
Labels: size/xs

#934 fix: release strategy
  .github/workflows/create-release-branch.yml
  .github/workflows/merge-release-pr-to-main.yml
  .github/workflows/merge-release-to-develop.yml
  .github/workflows/readme-commit.yml
Labels: size/s

#935 chore: Add Zod validation to user APIs
  common/changes/@aws/swb-app/farandac-userAPIs-zod-integration_2023-03-09-22-09.json
  common/changes/@aws/workbench-core-user-management/farandac-userAPIs-zod-integration_2023-03-09-22-09.json
  solutions/swb-app/README.md
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-app/src/users/createRoleRequest.ts
  solutions/swb-app/src/users/createUserRequest.ts
  solutions/swb-app/src/users/deleteUserRequest.ts
  solutions/swb-app/src/users/getUserRequest.ts
  solutions/swb-app/src/users/updateRoleRequest.ts
  solutions/swb-app/src/users/updateUserRequest.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  workbench-core/example/app/src/models/user/activateUserRequest.ts
  workbench-core/example/app/src/models/user/addUserToRole.ts
  workbench-core/example/app/src/models/user/createRoleRequest.ts
  workbench-core/example/app/src/models/user/createUserRequest.ts
  workbench-core/example/app/src/models/user/deactivateUserRequest.ts
  workbench-core/example/app/src/models/user/deleteUserRequest.ts
  workbench-core/example/app/src/models/user/getRolesRequest.ts
  workbench-core/example/app/src/models/user/getUserRequest.ts
  workbench-core/example/app/src/routes/userRoutes.ts
  workbench-core/user-management/src/index.ts
  workbench-core/user-management/src/schemas/createRole.ts
  workbench-core/user-management/src/schemas/createUser.ts
  workbench-core/user-management/src/schemas/updateRole.ts
Labels: size/m

#927 chore: parameterize stack for solutions
  common/changes/@aws/workbench-core-infrastructure/chore-parameterize-stack-for-solutions_2023-03-06-19-12.json
  deployment/build-s3-dist.sh
  deployment/solution_config
  deployment/testEnv.json
  solutions/swb-reference/README.md
  solutions/swb-reference/README_SINGLE_CLICK.md
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
  workbench-core/infrastructure/README.md
Labels: size/m

#936 fix(appSec): main account S3 Key separation
  common/changes/@aws/workbench-core-accounts/janeyu-key-rotation_2022-12-30-21-11.json
  common/changes/@aws/workbench-core-accounts/janeyu-key-rotation_2023-01-12-23-58.json
  common/changes/@aws/workbench-core-environments/janeyu-key-rotation_2023-01-12-23-58.json
  common/changes/@aws/workbench-core-infrastructure/janeyu-key-rotation_2022-12-30-21-11.json
  solutions/example-ui-app/cache/config.json
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/config/swbv2-private.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/complex/accountHelper.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookEnvironmentLifecycleService.ts
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebookLaunchSSM.yaml
  workbench-core/accounts/README.md
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
  workbench-core/infrastructure/src/workbenchEncryptionKeyWithRotation.ts
Labels: size/m

#938 refactor(swb): remove share and import dataset routes and update Post…
  common/changes/@aws/swb-app/kevpark-update-postman_2023-03-13-09-15.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-reference/SWBv2.postman_collection.json
Labels: size/m

#941 chore: Add Zod validation to user APIs
  common/changes/@aws/swb-app/farandac-userAPIs-zod-integration_2023-03-09-22-09.json
  common/changes/@aws/workbench-core-user-management/farandac-userAPIs-zod-integration_2023-03-09-22-09.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-app/src/users/createRoleRequest.ts
  solutions/swb-app/src/users/createUserRequest.ts
  solutions/swb-app/src/users/deleteUserRequest.ts
  solutions/swb-app/src/users/getUserRequest.ts
  solutions/swb-app/src/users/updateRoleRequest.ts
  solutions/swb-app/src/users/updateUserRequest.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  workbench-core/example/app/src/models/user/activateUserRequest.ts
  workbench-core/example/app/src/models/user/addUserToRole.ts
  workbench-core/example/app/src/models/user/createRoleRequest.ts
  workbench-core/example/app/src/models/user/createUserRequest.ts
  workbench-core/example/app/src/models/user/deactivateUserRequest.ts
  workbench-core/example/app/src/models/user/deleteUserRequest.ts
  workbench-core/example/app/src/models/user/getRolesRequest.ts
  workbench-core/example/app/src/models/user/getUserRequest.ts
  workbench-core/example/app/src/routes/userRoutes.ts
  workbench-core/user-management/src/index.ts
  workbench-core/user-management/src/schemas/createRole.ts
  workbench-core/user-management/src/schemas/createUser.ts
  workbench-core/user-management/src/schemas/updateRole.ts
Labels: size/m

#945 chore: rebase release da93c65 to develop
  README.md
  common/changes/@aws/swb-app/kevpark-update-postman_2023-03-13-09-15.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-reference/README.md
  solutions/swb-reference/SWBv2.postman_collection.json
Labels: size/m

#947 test(sshkeys): fix create test and delete
  solutions/swb-reference/integration-tests/support/resources/sshKeys/sshKey.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
Labels: size/s

#948 chore: rebase release aa56a8d to develop
  README.md
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/support/resources/sshKeys/sshKey.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
Labels: size/s

#943 fix: solutions resource collision
  common/changes/@aws/workbench-core-infrastructure/chore-parameterize-stack-for-solutions_2023-03-06-19-12.json
  deployment/build-s3-dist.sh
  deployment/solution_config
  deployment/testEnv.json
  solutions/swb-reference/README.md
  solutions/swb-reference/README_SOLUTIONS.md
  solutions/swb-reference/scripts/solutions-implementation/baseResourceSetup.sh
  solutions/swb-reference/scripts/solutions-implementation/createEnvironment.sh
  solutions/swb-reference/scripts/solutions-implementation/postSolutionDeployment.sh
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
  workbench-core/environments/README.md
  workbench-core/environments/src/postDeployment/cognitoSetup.test.ts
  workbench-core/environments/src/postDeployment/cognitoSetup.ts
Labels: size/l

#955 chore: fix github workflow
  .github/workflows/readme-commit.yml
  .github/workflows/verify-changefiles.yml
Labels: size/s

#956 chore: fix workflow
  .github/actions/enableBranchProtectionAction/action.yml
  .github/workflows/enable-feat-protection.yml
  .github/workflows/enable-release-protection.yml
  .github/workflows/main-protection.yml
  .github/workflows/merge-release-to-develop.yml
  .github/workflows/readme-commit.yml
  .github/workflows/release-deletion.yml
  .github/workflows/stage-protection.yml
Labels: size/m

#957 fix(appSec): set CWL Retention Period to 10 years
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/infra/SWBVpc.ts
Labels: size/xs

#960 fix: cognito pool id retrieval
  common/changes/@aws/workbench-core-environments/fix-cognito-pool-id-retrieval_2023-03-21-20-19.json
  solutions/swb-reference/src/postDeployment.ts
  workbench-core/environments/README.md
  workbench-core/environments/src/postDeployment/cognitoSetup.test.ts
  workbench-core/environments/src/postDeployment/cognitoSetup.ts
Labels: size/s

#962 chore: Add Zod generic pagination
  common/changes/@aws/swb-app/farandac-zod-generic-pagination_2023-03-21-22-38.json
  common/changes/@aws/workbench-core-accounts/farandac-zod-generic-pagination_2023-03-21-22-38.json
  common/changes/@aws/workbench-core-base/farandac-zod-generic-pagination_2023-03-21-22-38.json
  common/changes/@aws/workbench-core-environments/farandac-zod-generic-pagination_2023-03-21-22-38.json
  solutions/swb-app/README.md
  solutions/swb-app/config/jest.config.json
  solutions/swb-app/src/envTypeConfigs/listEnvironmentTypeConfigsRequest.test.ts
  solutions/swb-app/src/envTypeConfigs/listEnvironmentTypeConfigsRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigRoutes.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listEnvTypeConfigProjectsRequest.test.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listEnvTypeConfigProjectsRequest.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listProjectEnvTypeConfigsRequest.test.ts
  solutions/swb-app/src/projectEnvTypeConfigs/listProjectEnvTypeConfigsRequest.ts
  solutions/swb-app/src/validatorHelper.test.ts
  solutions/swb-app/src/validatorHelper.ts
  workbench-core/accounts/README.md
  workbench-core/accounts/config/jest.config.json
  workbench-core/accounts/src/models/accounts/listAccountsRequest.test.ts
  workbench-core/accounts/src/models/accounts/listAccountsRequest.ts
  workbench-core/accounts/src/models/costCenters/listCostCentersRequest.test.ts
  workbench-core/accounts/src/models/costCenters/listCostCentersRequest.ts
  workbench-core/accounts/src/models/projects/listProjectsRequest.test.ts
  workbench-core/accounts/src/models/projects/listProjectsRequest.ts
  workbench-core/base/README.md
  workbench-core/base/src/index.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
  workbench-core/environments/README.md
  workbench-core/environments/config/jest.config.json
  workbench-core/environments/src/models/environmentTypeConfigs/listEnvironmentTypeConfigsRequest.test.ts
  workbench-core/environments/src/models/environmentTypeConfigs/listEnvironmentTypeConfigsRequest.ts
  workbench-core/environments/src/models/environmentTypes/listEnvironmentTypesRequest.test.ts
  workbench-core/environments/src/models/environmentTypes/listEnvironmentTypesRequest.ts
Labels: size/xl

#949 fix: remove AuthenticatedUser from datasets DDB entries
  .viperlightignore
  common/changes/@aws/workbench-core-datasets/fix-remove-authenticated-user-from-datasets-ddb_2023-03-15-19-20.json
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/models/ddbMetadata.ts
  workbench-core/example/infrastructure/integration-tests/support/complex/datasetHelper.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
Labels: size/m

#965 ci: example app deployment/integration-test fix
  .github/workflows/deploy-integration-example-app.yml
Labels: size/xs

#966 chore: fix example app integration test
  .github/workflows/deploy-integration-example-app.yml
  .viperlightignore
  workbench-core/example/app/src/models/datasets/createExternalEndpoint.ts
  workbench-core/example/app/src/models/datasets/createImportDataSet.ts
  workbench-core/example/app/src/models/datasets/createPresignedFileUpload.ts.ts
  workbench-core/example/app/src/routes/datasetRoutes.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/dataset.ts
  workbench-core/example/infrastructure/integration-tests/support/resources/datasets/datasets.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/byob.test.ts
  workbench-core/example/infrastructure/src/example-hosting-stack.ts
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/example/infrastructure/src/index.ts
Labels: size/s

#968 chore(cfn-nag): suppress .cfn.yaml files
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
Labels: size/s

#967 feat: add SWB_DATASET_UPLOAD permissions
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/m

#970 chore: Rebase release 9765ff6 to develop
  .github/workflows/cfn-nag.yml
  .github/workflows/deploy-integration-example-app.yml
  .github/workflows/merge-develop-to-stage.yml
  .viperlightignore
  common/changes/@aws/workbench-core-datasets/fix-remove-authenticated-user-from-datasets-ddb_2023-03-15-19-20.json
  deployment/solution_config
  solutions/swb-reference/README.md
  solutions/swb-reference/SETUP_v2p1.md
  solutions/swb-reference/src/environment/sagemakerNotebook/sagemakerNotebook.cfn.yaml
  solutions/swb-reference/src/templates/README.md
  solutions/swb-reference/src/templates/onboard-account-byon.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  solutions/swb-reference/src/templates/onboard-account.cfn.yaml
  workbench-core/datasets/src/dataSetService.ts
  workbench-core/datasets/src/ddbDataSetMetadataPlugin.ts
  workbench-core/datasets/src/index.ts
  workbench-core/datasets/src/models/ddbMetadata.ts
  workbench-core/example/infrastructure/integration-tests/support/complex/datasetHelper.ts
  workbench-core/example/infrastructure/integration-tests/tests/datasets/create.test.ts
Labels: size/xl

#972 chore: Rebase release ed6881fb to develop
  solutions/swb-reference/README.md
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/m

#971 chore: adding sonarqube coverage paths
  sonar-project.properties
Labels: size/s

#973 chore: Rebase release faa15187 to develop
  sonar-project.properties
Labels: size/s

#969 test(paab test): add project filtered test in multistep
  solutions/swb-reference/integration-tests/support/complex/paabHelper.ts
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
Labels: size/m

#978 feat: removed API roles from routes, updated tests
  common/changes/@aws/swb-app/atmikev-GALI-2373_RemoveUserApiRoutes_2023-03-29-16-20.json
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-2373_RemoveUserApiRoutes_2023-03-29-16-20.json
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-app/src/users/createRoleRequest.ts
  solutions/swb-app/src/users/updateRoleRequest.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userApi.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/users/getUserRoles.test.ts
Labels: size/s

#918 feat: multiple app client ids
  common/changes/@aws/swb-app/topic-multipleAppClientIds_2023-02-28-19-23.json
  common/changes/@aws/workbench-core-authentication/topic-multipleAppClientIds_2023-02-28-19-23.json
  common/changes/@aws/workbench-core-base/topic-multipleAppClientIds_2023-02-28-19-23.json
  common/changes/@aws/workbench-core-infrastructure/topic-multipleAppClientIds_2023-02-28-19-23.json
  common/config/rush/browser-approved-packages.json
  common/config/rush/pnpm-lock.yaml
  common/config/rush/repo-state.json
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-reference/integration-tests/support/setup.ts
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/scripts/generateCognitoTokens.js
  solutions/swb-reference/src/SWBStack.ts
  solutions/swb-reference/src/config/example.yaml
  solutions/swb-reference/src/constants.ts
  workbench-core/authentication/README.md
  workbench-core/authentication/docs/authenticationMiddleware.md
  workbench-core/authentication/src/authenticationMiddleware.test.ts
  workbench-core/authentication/src/authenticationService.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.test.ts
  workbench-core/authentication/src/plugins/cognitoAuthenticationPlugin.ts
  workbench-core/base/src/cognitoTokenService.ts
  workbench-core/example/app/src/services/authenticationService.ts
  workbench-core/example/infrastructure/integration-tests/support/setup.ts
  workbench-core/example/infrastructure/integration-tests/support/utils/settings.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/routeHandler.test.ts
  workbench-core/example/infrastructure/integration-tests/tests/authentication/webUiAppClient.test.ts
  workbench-core/example/infrastructure/package.json
  workbench-core/example/infrastructure/src/example-stack.ts
  workbench-core/infrastructure/docs/workbenchCognito.md
  workbench-core/infrastructure/src/workbenchCognito.test.ts
  workbench-core/infrastructure/src/workbenchCognito.ts
Labels: size/l

#976 chore(dataset permissions): add pagination to dataset permissions list
  common/changes/@aws/swb-app/farandac-datasetPermissions-pagination_2023-03-29-18-03.json
  solutions/swb-app/src/dataSets/listDataSetAccessPermissionsRequestParser.ts
  solutions/swb-reference/SWBv2.postman_collection.json
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/s

#980 chore(cfn-nag): supress APIGateway Auth type warning with explanation
  solutions/swb-reference/src/SWBStack.ts
Labels: size/xs

#964 docs: update TGW firewall user steps
  solutions/swb-reference/README_SOLUTIONS.md
  solutions/swb-reference/src/templates/README.md
Labels: size/s

#983 fix(appsec): update listener SSL policy
  solutions/swb-reference/src/SWBStack.ts
Labels: size/s

#982 docs: instructions for ALB access log in solutions
  solutions/swb-reference/README_SOLUTIONS.md
  solutions/swb-reference/src/infra/SWBApplicationLoadBalancer.ts
Labels: size/s
