Repository aws-solutions/research-service-workbench-on-aws, pull requests merged in 2023-06, with the labels that each got.

#1095 ci: configure release integration pipeline for release/v2.0.0
  .github/workflows/integration-tests-release.yml
  solutions/swb-reference/README_SOLUTIONS.md
Labels: size/xs

#1103 feat: list users by role pagination
  .viperlightignore
  common/changes/@aws/swb-app/atmikev-GALI-2494_ListUsersByRolePagination_2023-06-01-00-22.json
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-2494_ListUsersByRolePagination_2023-06-01-00-22.json
  common/changes/@aws/workbench-core-authorization/atmikev-GALI-2494_ListUsersByRolePagination_2023-06-01-19-52.json
  common/changes/@aws/workbench-core-base/atmikev-GALI-2494_ListUsersByRolePagination_2023-06-01-00-22.json
  common/changes/@aws/workbench-core-user-management/atmikev-GALI-2494_ListUsersByRolePagination_2023-06-01-00-22.json
  solutions/swb-app/src/projectRoutes.ts
  solutions/swb-app/src/userRoutes.ts
  solutions/swb-reference/integration-tests/support/resources/projects/project.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/listUsers.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/userProject.test.ts
  workbench-core/accounts/src/index.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.test.ts
  workbench-core/authorization/src/dynamicAuthorization/wbcGroupManagementPlugin.ts
  workbench-core/base/config/jest.config.json
  workbench-core/base/src/index.ts
  workbench-core/base/src/interfaces/listUsersForRoleRequest.ts
  workbench-core/user-management/config/jest.config.json
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
  workbench-core/user-management/src/userManagementPlugin.ts
  workbench-core/user-management/src/userManagementService.test.ts
  workbench-core/user-management/src/userManagementService.ts
Labels: size/m

#1105 refactor: add s3 bucket owner to service calls
  common/changes/@aws/swb-app/yanyu-s3-bucket-owner_2023-06-01-23-59.json
  common/changes/@aws/workbench-core-accounts/yanyu-s3-bucket-owner_2023-06-01-23-59.json
  common/changes/@aws/workbench-core-base/yanyu-s3-bucket-owner_2023-06-01-23-59.json
  common/changes/@aws/workbench-core-datasets/yanyu-s3-bucket-owner_2023-06-01-23-59.json
  common/changes/@aws/workbench-core-environments/yanyu-s3-bucket-owner_2023-06-01-23-59.json
  solutions/swb-reference/integration-tests/support/complex/accountHelper.ts
  solutions/swb-reference/integration-tests/support/complex/datasetHelper.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/base/src/aws/helpers/s3Service.ts
  workbench-core/datasets/src/s3DataSetStoragePlugin.ts
  workbench-core/environments/src/postDeployment/serviceCatalogSetup.ts
Labels: size/m

#1107 fix: create account should throw 400 error instead of 500 errors for incorrect accountId and arns
  common/changes/@aws/swb-app/thingut-hosting-account-validation_2023-06-04-16-21.json
  common/changes/@aws/workbench-core-accounts/thingut-hosting-account-validation_2023-06-04-16-13.json
  common/changes/@aws/workbench-core-base/thingut-hosting-account-validation_2023-06-04-16-21.json
  solutions/swb-app/src/accountRoutes.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
  workbench-core/accounts/src/errors/InvalidAwsAccountIdError.ts
  workbench-core/accounts/src/errors/errors.test.ts
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/models/accounts/createAccountRequest.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/m

#1108 fix: fix Dataset Edge Cases
  common/changes/@aws/swb-app/release-v2.0.0_2023-06-05-09-05.json
  common/changes/@aws/workbench-core-base/release-v2.0.0_2023-06-05-09-05.json
  common/changes/@aws/workbench-core-environments/release-v2.0.0_2023-06-05-09-05.json
  solutions/swb-app/src/dataSetRoutes.ts
  solutions/swb-app/src/dataSets/dataSetPlugin.ts
  solutions/swb-app/src/dataSets/isProjectAuthorizedForDatasetsParser.ts
  solutions/swb-app/src/generateRouter.ts
  solutions/swb-app/src/index.ts
  solutions/swb-app/src/projectEnvironmentRoutes.ts
  solutions/swb-app/src/schemas/projects/projectMetadataParser.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
  workbench-core/base/src/aws/helpers/dynamoDB/ddbUtil.test.ts
  workbench-core/base/src/aws/helpers/dynamoDB/ddbUtil.ts
  workbench-core/base/src/index.ts
  workbench-core/environments/src/services/environmentService.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.test.ts
  workbench-core/environments/src/utilities/environmentLifecycleHelper.ts
Labels: size/l

#1110 fix: set maximum input length for create account requests
  common/changes/@aws/workbench-core-accounts/thingut-hosting-account-text-limit_2023-06-05-17-34.json
  common/changes/@aws/workbench-core-base/thingut-hosting-account-text-limit_2023-06-05-17-34.json
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
  workbench-core/accounts/src/models/accounts/createAccountRequest.ts
  workbench-core/base/src/utilities/textUtil.test.ts
  workbench-core/base/src/utilities/textUtil.ts
  workbench-core/base/src/utilities/validatorHelper.test.ts
  workbench-core/base/src/utilities/validatorHelper.ts
Labels: size/m

#1111 fix: address edge cases for adding/removing owning project to dataset
  solutions/swb-reference/integration-tests/tests/multiStep/dataset.test.ts
  solutions/swb-reference/src/services/dataSetService.test.ts
  solutions/swb-reference/src/services/dataSetService.ts
Labels: size/s

#1114 fix: increase byon integ test workflow memory
  .github/workflows/deploy-integration-swb-reference-byon.yml
Labels: size/xs

#1106 chore: add limits on names when creating or updating objects
  common/changes/@aws/swb-app/atmikev-CostCenterFixes_2023-06-02-22-06.json
  common/changes/@aws/workbench-core-accounts-ui/atmikev-CostCenterFixes_2023-06-02-22-07.json
  common/changes/@aws/workbench-core-accounts/atmikev-CostCenterFixes_2023-06-02-22-07.json
  common/changes/@aws/workbench-core-base/atmikev-CostCenterFixes_2023-06-02-22-07.json
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
  solutions/swb-reference/src/proxyHandlerLambda.ts
  workbench-core/accounts/src/models/costCenters/updateCostCenterRequest.ts
Labels: size/m

#1112 fix: add pagination to get user roles call
  common/changes/@aws/workbench-core-base/yanyu-cognito-fix_2023-06-05-19-46.json
  common/changes/@aws/workbench-core-user-management/yanyu-cognito-fix_2023-06-05-19-46.json
  workbench-core/base/src/aws/awsService.ts
  workbench-core/base/src/aws/helpers/cognitoService.test.ts
  workbench-core/base/src/aws/helpers/cognitoService.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.test.ts
  workbench-core/user-management/src/plugins/cognitoUserManagementPlugin.ts
Labels: size/m

#1115 chore: update cost center integ test error message
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
Labels: size/xs

#1118 docs(readme): update main readme
  README.md
Labels: size/s

#1120 chore: update notice file in parent directory and remove from subpack…
  NOTICE
  README.md
  solutions/swb-app/NOTICE
  solutions/swb-app/THIRD_PARTY_LICENSE.txt
  solutions/swb-reference/NOTICE
  solutions/swb-reference/THIRD_PARTY_LICENSE.txt
  workbench-core/accounts/NOTICE
  workbench-core/audit/NOTICE
  workbench-core/authentication/NOTICE
  workbench-core/authorization/NOTICE
  workbench-core/base/NOTICE
  workbench-core/datasets/NOTICE
  workbench-core/environments/NOTICE
  workbench-core/infrastructure/NOTICE
  workbench-core/logging/NOTICE
  workbench-core/user-management/NOTICE
Labels: size/xl, skip-verify-changefiles

#1121 test: aws account authZ test
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/awsAccountTemplateUrls.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts
Labels: size/m, skip-verify-changefiles

#1136 fix: update list env test paab constructor
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
Labels: size/xs, skip-verify-changefiles

#1135 test: add AuthZ test for create environment
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
Labels: size/s, skip-verify-changefiles

#1139 chore: adding integ test cases for PAAB
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
Labels: size/m, skip-verify-changefiles

#1140 test(userapi): integ test
  .viperlightignore
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/listUsers.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/user.test.ts
Labels: size/m, skip-verify-changefiles

#1133 feat: CostCenter auth tests
  solutions/swb-reference/integration-tests/support/resources/base/resource.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/costCenter.test.ts
Labels: size/m, skip-verify-changefiles

#1131 test(integ): integ test for project boundary
  solutions/swb-reference/integration-tests/tests/multiStep/sshKeys.test.ts
  solutions/swb-reference/src/services/sshKeyService.ts
Labels: size/m, skip-verify-changefiles

#1134 test: add getEnvironmentType as PA and Researcher
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
Labels: size/m, skip-verify-changefiles

#1142 test(swb-ref): fix paab state change polling
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
Labels: size/s, skip-verify-changefiles

#1124 test: add more negative testing to listUserForProjects and listUsers
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/listUsers.test.ts
Labels: size/m, skip-verify-changefiles

#1138 test: add more integ tests for datasets API
  solutions/swb-reference/integration-tests/tests/isolated/datasets/associate.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/permissions.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/remove.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
Labels: size/l, skip-verify-changefiles

#1141 fix: only allow ITAdmin to list projects by ETC
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/integration-tests/tests/multiStep/et-etc.test.ts
  solutions/swb-reference/src/constants.ts
  solutions/swb-reference/src/dynamicRouteConfig.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.test.ts
  solutions/swb-reference/src/postDeployment/authorizationSetup.ts
Labels: size/s, skip-verify-changefiles

#1144 test: add unauthenticated user tests
  .viperlightignore
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/awsAccountTemplateUrls.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/costCenter/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/associate.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/listPermissions.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/remove.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/datasets/uploadFile.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypeConfigs/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environmentTypes/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/connections.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/launch.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/start.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/stop.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/environments/terminate.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projectEnvTypeConfigs/listProjects.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/assignUserToProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/get.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/getDataSetForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/list.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listDataSetsForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/listUsersForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/removeUserFromProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/softDelete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/projects/update.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/create.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/sshKeys/listUserSshKeysForProject.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/activateDeactivateUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/createUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/delete.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/getUser.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/listUsers.test.ts
  solutions/swb-reference/integration-tests/tests/isolated/users/updateUser.test.ts
Labels: size/xl, skip-verify-changefiles

#1145 chore: harden paab tests
  solutions/swb-reference/integration-tests/tests/multiStep/paab.test.ts
Labels: size/m, skip-verify-changefiles

#1147 chore: update test description
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/create.test.ts
Labels: size/xs, skip-verify-changefiles

#1151 feat: removing tgw and firewall templates
  .github/workflows/pnpm-audit.yml
  solutions/swb-reference/integration-tests/tests/isolated/awsAccounts/awsAccountTemplateUrls.test.ts
  solutions/swb-reference/src/postDeployment.ts
  solutions/swb-reference/src/templates/README.md
  solutions/swb-reference/src/templates/new-firewall-vpc.yaml
  solutions/swb-reference/src/templates/onboard-account-tgw.cfn.yaml
  workbench-core/accounts/CHANGELOG.json
  workbench-core/accounts/CHANGELOG.md
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.test.ts
  workbench-core/accounts/src/utilities/hostingAccountLifecycleService.ts
Labels: size/xl, skip-verify-changefiles

#1154 fix: collection examples
  solutions/swb-reference/README.md
  solutions/swb-reference/RSW.openapi.json
  solutions/swb-reference/RSW.postman_collection.json
Labels: size/s, skip-verify-changefiles

#1157 chore: add back ts to jest options for moduleFileExtensions
  solutions/swb-reference/jest.config.js
Labels: size/xs, skip-verify-changefiles

#1156 fix: solutions template name
  deployment/build-s3-dist.sh
  solutions/swb-reference/README_SOLUTIONS.md
  solutions/swb-reference/scripts/solutions-implementation/baseResourceSetup.sh
  solutions/swb-reference/scripts/solutions-implementation/postSolutionDeployment.sh
Labels: size/s, skip-verify-changefiles

#1158 chore: update resources used by stage integ tests
  solutions/swb-reference/integration-tests/config/swbv2-private.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
Labels: size/s, skip-verify-changefiles

#1129 ci: enable npm publish for main
  .github/workflows/npm-publish.yml
Labels: size/s

#1159 feat: cost center account status error
  common/changes/@aws/swb-app/atmikev-GALI-2336-CostCenterAccountStatus_2023-06-21-18-24.json
  common/changes/@aws/swb-reference/atmikev-GALI-2336-CostCenterAccountStatus_2023-06-22-18-28.json
  common/changes/@aws/workbench-core-accounts/atmikev-GALI-2336-CostCenterAccountStatus_2023-06-21-18-24.json
  common/config/rush/pnpm-config.json
  solutions/swb-app/src/costCenterRoutes.ts
  solutions/swb-reference/scripts/runLocally.sh
  workbench-core/accounts/src/errors/InvalidAccountStateError.ts
  workbench-core/accounts/src/errors/errors.test.ts
  workbench-core/accounts/src/index.ts
  workbench-core/accounts/src/services/costCenterService.test.ts
  workbench-core/accounts/src/services/costCenterService.ts
Labels: size/m

#1149 chore: mask externalId
  common/changes/@aws/swb-reference/janeyu-externalID_2023-06-15-18-26.json
  common/changes/@aws/workbench-core-environments/janeyu-externalID_2023-06-15-18-26.json
  solutions/swb-reference/integration-tests/config/example.yaml
  solutions/swb-reference/integration-tests/config/release-candidate-private.yaml
  solutions/swb-reference/integration-tests/config/release-candidate.yaml
  solutions/swb-reference/integration-tests/config/swbv2-private.yaml
  solutions/swb-reference/integration-tests/config/testEnv.yaml
  solutions/swb-reference/integration-tests/support/utils/settings.ts
  solutions/swb-reference/integration-tests/tests/multiStep/awsAccount.test.ts
  workbench-core/environments/src/handlers/statusHandler.test.ts
  workbench-core/environments/src/services/environmentService.test.ts
Labels: size/m

#1160 chore: remove example UI
  .github/workflows/build-and-test.yml
  codecov.yml
  solutions/example-ui-app/.depcheckrc
  solutions/example-ui-app/.eslintignore
  solutions/example-ui-app/.eslintrc.js
  solutions/example-ui-app/LICENSE
  solutions/example-ui-app/NOTICE
  solutions/example-ui-app/README.md
  solutions/example-ui-app/babel.config.js
  solutions/example-ui-app/cache/config.json
  solutions/example-ui-app/jest.config.js
  solutions/example-ui-app/jest.setup.js
  solutions/example-ui-app/license-add-config.json
  solutions/example-ui-app/next-env.d.ts
  solutions/example-ui-app/next-i18next.config.js
  solutions/example-ui-app/next.config.js
  solutions/example-ui-app/package.json
  solutions/example-ui-app/public/favicon.svg
  solutions/example-ui-app/public/image.png
  solutions/example-ui-app/public/locales/en/common.json
  solutions/example-ui-app/public/locales/es/common.json
  solutions/example-ui-app/public/logo.svg
  solutions/example-ui-app/public/vercel.svg
  solutions/example-ui-app/src/components/BaseLayout.tsx
  solutions/example-ui-app/src/components/Header.tsx
  solutions/example-ui-app/src/components/Hero.tsx
  solutions/example-ui-app/src/components/Navigation.tsx
  solutions/example-ui-app/src/context/AuthenticationContext.tsx
  solutions/example-ui-app/src/context/NotificationContext.tsx
  solutions/example-ui-app/src/context/SettingsContext.tsx
  solutions/example-ui-app/src/models/AppSettings.ts
  solutions/example-ui-app/src/models/User.ts
  solutions/example-ui-app/src/pages/_app.tsx
  solutions/example-ui-app/src/pages/api/hello.ts
  solutions/example-ui-app/src/pages/index.tsx
  solutions/example-ui-app/src/sanity.test.ts
  solutions/example-ui-app/src/styles/BaseLayout.module.scss
  solutions/example-ui-app/src/styles/Header.module.scss
  solutions/example-ui-app/src/styles/Hero.module.scss
  solutions/example-ui-app/src/styles/globals.scss
  solutions/example-ui-app/tsconfig.json
Labels: size/xl

#1161 chore(list-env): add integ test for pageSize exceed max
  common/changes/@aws/swb-reference/janeyu-pageSize_2023-06-27-20-55.json
  solutions/swb-reference/integration-tests/tests/isolated/environments/list.test.ts
Labels: size/s
